chore: surface webcontents load error more readily
electron/electron pull request #22824
Opened 2020-03-24 22:53 UTC by loc

#### Description of Change
Surface failed load error messages a little more readily so that new folks aren't left as confused. 

e.g. https://github.com/electron/electron/issues/5107#issuecomment-281200144

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: no-notes

2020-03-24 23:21 UTC, nornagon submitted a review, later dismissed
Hm, I don't think `LOG(ERROR)` is the right place for a load failure. Things can fail to load for a variety of reasons and it's not generally an application error when they do. Further, `LOG` is often not easy to see on Windows.

Can you expand a bit on what your goal is here?

2020-03-25 00:17 UTC, loc commented
Sure. I believe it's too easy to make a pretty reasonable mistake (misspelling or otherwise getting your file wrong for loadFile/loadURL) and not get an actionable error from it. The error that you do get comes in the renderer console, and it's a side-effect with a pretty obtuse and misdirecting error: `Not allowed to load local resource: file://misspelled-file.html/`.

There are two ways to get the correct error, `ERR_FILE_NOT_FOUND`, neither of which are immediately obvious, nor currently "recommended" by [electron-quick-start](https://github.com/electron/electron-quick-start/blob/master/main.js#L16):
1. You can `.catch()` the error from the loadFile promise or
2. You can subscribe to the webContents's `did-fail-load` event.

_A_ satisfactory solution could be to change our examples to include error handling, but I think that expecting log output when a webcontents fails to load is pretty reasonable. Ideally, actually, would be to surface `ERR_FILE_NOT_FOUND` in the renderer console too, but there doesn't seem to be that much prior art for doing that elsewhere.

2020-03-30 18:10 UTC, nornagon commented
Can we have this be a `console.warn` (in JS) instead of `LOG(ERROR)` in C++?

And can we make it dev-only?

2020-07-21 05:41 UTC, zcbenz commented
@loc Do you still plan to work on this PR?

2020-07-21 20:02 UTC, loc commented
I should! I wasn't immediately sure how to ferry the error to the renderer to console.warn in JS. Any thoughts on how I should approach? Naively I want to set up an IPC handler n window-setup.ts in the renderer, but not sure if there's a cleaner way?

2020-07-21 20:13 UTC, MarshallOfSound commented
@loc you can use the `EmitWarning` helper from `process_util.cc`

2021-01-11 05:46 UTC, zcbenz approved these changes

2021-01-11 05:50 UTC, zcbenz requested changes
@loc The "app module getGPUInfo() API succeeds with basic GPUInfo" test keeps failing on Windows CI, which I believe it is caused by the warning message leaked to the output of `gpu-info.js`, can you fix it?

2021-01-11 17:40 UTC, codebytere commented
@zcbenz Andy no longer works at Slack and hasn't for some time - i can try to fix this up.

2021-01-12 23:26 UTC, codebytere approved these changes

2021-01-13 09:01 UTC, zcbenz approved these changes

2021-01-13 09:01 UTC, merged