fix: honor pageRanges when printing
electron/electron pull request #25064
Opened 2020-08-20 18:09 UTC by codebytere

#### Description of Change

Closes https://github.com/electron/electron/issues/25013.

The print ranges in Chromium's print job settings were not being properly
plumbed through to PMPrintSettings. This fixes that by setting
them should they exist.

This will be upstreamed.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [x] relevant documentation is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).
- [x] This is **NOT A BREAKING CHANGE**. Breaking changes may not be merged to master until 11-x-y is branched.

#### Release Notes

Notes: Fixed an issue where pageRanges was not properly honored when printing.

2020-08-25 11:03 UTC, zcbenz requested changes

2020-08-25 11:03 UTC, zcbenz commented on patches/chromium/fix_properly_honor_printing_page_ranges.patch
> ++    ranges = g_new (GtkPageRange, print_ranges.size());
`ranges` should be freed after use.

2020-08-25 17:52 UTC, codebytere commented on docs/api/webview-tag.md
> +  * `pageRanges` Record<string, number> (optional) - The page range to print. On macOS, only the first range is honored.
this shouldn't be `Object[]` - in printToPDF it only accepts one range so we would need to have a breaking change to make them the same

2020-08-26 00:50 UTC, zcbenz approved these changes

2020-08-28 03:21 UTC, merged