feat: [net] change "useSessionCookies" to "credentials"
electron/electron pull request #25284
Opened 2020-09-02 18:25 UTC by nornagon

#### Description of Change
This deprecates the "useSessionCookies" property of `net.request()` and replaces it with a new property, "credentials", which more closely matches the behavior of `fetch()`.

The "useSessionCookies" property will be removed in Electron 13.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [x] relevant documentation is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: Added a new "credentials" option for `net.request()`, replacing the now-deprecated "useSessionCookies" option.

2020-09-02 18:25 UTC, nornagon commented
NB. this change depends on the current master roll: https://github.com/electron/electron/pull/24984

2020-09-02 18:50 UTC, deepak1556 approved these changes
Api looks better now 👍 

Also `useSessionCookies` was added for https://github.com/electron/electron/issues/8891 where users where only concerned with whether the cookies are completely handled by the store or not. So this change is reasonable for that too.

2020-09-03 16:43 UTC, nornagon commented
@MarshallOfSound this is not semver/major because it doesn't break old behavior. it'll be semver/major when we remove the old one.

2020-09-17 06:25 UTC, deepak1556 approved these changes
LGTM

2020-09-17 06:25 UTC, deepak1556 commented on shell/browser/api/electron_api_url_loader.cc
> +  LOG(INFO) << "credentials_specified = " << credentials_specified;
log can be removed ?

2020-09-22 00:24 UTC, jkleinsc commented
The API WG approved this at the Sept 21, 2020 meeting.

2020-09-24 15:25 UTC, jkleinsc requested changes
This needs a rebase from master to fix the mac arm64 compile issues.

2020-09-28 23:44 UTC, nornagon commented
@jkleinsc ping

2020-09-28 23:55 UTC, jkleinsc approved these changes

2020-09-29 16:03 UTC, merged