fix: multiple fixes to redirects in intercepted requests
electron/electron pull request #25297
Opened 2020-09-03 06:29 UTC by marcin-prochownik

#### Description of Change
Minor fixes to handling intercepted requests:

- 'content-length' wasn't passed down the stream
- for redirects,  methods were not converted to 'GET' and caused too many redirects
- intermittent access violation during redirects

#### Checklist
- [x ] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [ ] relevant documentation is changed or added
- [x ] PR title follows semantic
- [ x] [PR release notes]

#### Release Notes

Notes: Fixed following issues for intercepted requests:
- Fixed issue where on redirects methods were not converted to 'GET' and caused too many redirects
- Fixed 'content-length' not being passed down the stream 
- Fixed intermittent access violation that could occur during handling redirects

2020-09-03 18:58 UTC, nornagon requested changes
This appears to be three separate changes. Would it be possible to break this apart into 3 PRs so they can be reviewed independently?

2020-09-03 18:58 UTC, nornagon commented on shell/browser/net/proxying_url_loader_factory.h
> +  std::set<int32_t> intercepted_requests_;
I think this set grows without bound? Which would be a memory leak and thus not acceptable to merge.

2020-09-03 18:58 UTC, nornagon commented on shell/browser/net/electron_url_loader_factory.cc
> +  // See: https://tools.ietf.org/html/rfc7231#section-6.4
I believe this should be implemented upstream, not by us.

See https://source.chromium.org/chromium/chromium/src/+/master:services/network/cors/cors_url_loader.cc;l=359-367;drc=e3aec06168fddef3f2a085fb1f6282b2b9920480

2020-09-04 06:49 UTC, closed without merging

2020-09-04 06:50 UTC, marcin-prochownik commented
I'll create three separate PRs.