feat: allow setting SSL config
electron/electron pull request #25461
Opened 2020-09-14 23:16 UTC by nornagon

#### Description of Change
This allows apps to configure min and max supported SSL versions. Chromium currently uses a minimum of TLS1.2 by default, whereas Electron defaults to TLS1.0 by default. This gives apps the ability to control supported TLS versions according to their needs.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [x] relevant documentation is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: Added `session.setSSLConfig()` to allow configuring SSL.

2020-09-15 05:43 UTC, deepak1556 approved these changes
Implementation looks good.

One thing to make sure is that this doesn't configure the ssl client for the system network context, before network s13n the system network context was dependency for network fetching code of OCSP/CRL/AIA data but now the code path has been modified to use per-profile network context https://bugs.chromium.org/p/chromium/issues/detail?id=829029, so it should not be an issue. The only other use cases of system network context I was able to find was the one used for device_service (for fetching geolocation data) and creating tcp connection for viz devtools, both of which are fine without this change. Might want to ensure any other code paths I might have missed.

2020-09-15 20:14 UTC, nornagon commented
@deepak1556 hm, I'm not sure what I should be searching for. Can you give me some pointers?

Do you think we should add a `session.setDefaultSSLConfig()` method as well/instead?

2020-09-15 21:31 UTC, deepak1556 commented
> I'm not sure what I should be searching for. Can you give me some pointers?

Checking for the usages of these apis https://github.com/electron/electron/blob/master/shell/browser/net/system_network_context_manager.h#L72-L82 should do.

> Do you think we should add a session.setDefaultSSLConfig() method as well/instead?

If there is no usage other than the ones I mentioned then its not required to add this, geolocation service is usually a google maps endpoint which the app doesn't have to control.

2020-09-16 04:11 UTC, MarshallOfSound approved these changes

2020-09-16 19:34 UTC, nornagon commented
I looked and I could only find those two as well.

As a precaution, what do you think about setting up the system network context to support the same TLS versions that Chrome does (without adding a new API to edit them)? i.e. min_version = TLS1.2.

2020-09-17 05:13 UTC, deepak1556 commented
yeah that would be a good thing to do

2020-09-22 00:28 UTC, jkleinsc commented
The API WG approved this at the Sept 21, 2020 meeting.

2020-09-22 00:29 UTC, jkleinsc requested changes
Just a small nit - can we note in the documentation what the defaults are if you do not set this config?

2020-09-22 18:22 UTC, nornagon commented
@jkleinsc NB. these defaults are set by a mojom file inside chromium and we don't have tests that will notify us if they change. So this documentation may go out of date.

2020-09-22 18:44 UTC, jkleinsc approved these changes

2020-09-23 20:22 UTC, jkleinsc commented
Merging as WOA failure is flake unrelated to this change.

2020-09-23 20:22 UTC, merged