fix: honor pageRanges when printing
electron/electron pull request #25600
Opened 2020-09-23 18:18 UTC by codebytere

Backport of https://github.com/electron/electron/pull/25064.

See that PR for more details.

Notes: Fixed an issue where pageRanges was not properly honored when printing.

2020-10-06 00:43 UTC, zcbenz requested changes
There are typescript errors:

```
ERROR in /Users/distiller/project/src/electron/lib/browser/api/web-contents.ts
[tsl] ERROR in /Users/distiller/project/src/electron/lib/browser/api/web-contents.ts(280,27)
      TS2339: Property 'from' does not exist on type 'PageRanges[]'.

ERROR in /Users/distiller/project/src/electron/lib/browser/api/web-contents.ts
[tsl] ERROR in /Users/distiller/project/src/electron/lib/browser/api/web-contents.ts(285,27)
      TS2339: Property 'to' does not exist on type 'PageRanges[]'.

ERROR in /Users/distiller/project/src/electron/lib/browser/api/web-contents.ts
[tsl] ERROR in /Users/distiller/project/src/electron/lib/browser/api/web-contents.ts(292,24)
      TS2339: Property 'from' does not exist on type 'PageRanges[]'.

ERROR in /Users/distiller/project/src/electron/lib/browser/api/web-contents.ts
[tsl] ERROR in /Users/distiller/project/src/electron/lib/browser/api/web-contents.ts(293,22)
      TS2339: Property 'to' does not exist on type 'PageRanges[]'.
```

2020-10-28 17:57 UTC, ckerr commented
@codebytere is this PR still live?

2020-10-28 18:49 UTC, codebytere commented
@ckerr i need to figure out the TS stuff but yes!

2020-11-03 22:17 UTC, jkleinsc requested changes
Looks like a doc change was missed - other than that LGTM

2020-11-03 22:17 UTC, jkleinsc commented on docs/api/web-contents.md
> +  * `pageRanges` Object[] (optional) - The page range to print.
```suggestion
  * `pageRanges` Object[] (optional) - The page range to print. On macOS, only one range is honored.
```

2020-11-09 23:55 UTC, 46967357 approved these changes

2020-11-10 09:15 UTC, zcbenz approved these changes

2020-11-10 15:06 UTC, jkleinsc approved these changes

2020-11-10 15:06 UTC, merged