refactor: use aws-sdk-js instead of boto
electron/electron pull request #25693
Opened 2020-09-29 21:43 UTC by nornagon

#### Description of Change
This was originally landed in #24863, then reverted in 1646f93.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)

#### Release Notes

Notes: none

2020-09-29 21:44 UTC, MarshallOfSound requested changes
This was reverted as it caused certain files to not be uploaded, that should be rectified before we can reland or it will just break nightlies again

2020-09-29 21:44 UTC, nornagon commented
@MarshallOfSound can you provide any more information about the failures? It's hard to fix it with a vague "some things didn't work".

2020-09-29 22:39 UTC, MarshallOfSound approved these changes

2020-09-30 20:30 UTC, nornagon commented
Build failures unrelated; merging.

2020-09-30 20:30 UTC, merged