fix: delay emitting powerMonitor events on windows
electron/electron pull request #25836
Opened 2020-10-08 23:10 UTC by nornagon

#### Description of Change
This delays emitting certain powerMonitor events on Windows to avoid entering V8 during a WndProc callback, which can cause crashes.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: Fixed a rare crash on Windows that could occur when emitting certain powerMonitor events.

2020-10-08 23:12 UTC, MarshallOfSound approved these changes

2020-10-13 01:57 UTC, zcbenz requested changes
Build is failing.

2020-10-15 00:57 UTC, zcbenz commented on shell/browser/api/electron_api_power_monitor_win.cc
> +            base::BindOnce(&Emit, base::Unretained(this), "lock-screen"));
Template functions can not be bound without specifying types of parameters.

```
../../electron/shell/browser/api/electron_api_power_monitor_win.cc(88,13): error: no matching function for call to 'BindOnce'
35798            base::BindOnce(&Emit, base::Unretained(this), "lock-screen"));
35799            ^~~~~~~~~~~~~~
35800../..\base/bind.h(243,59): note: candidate template ignored: couldn't infer template argument 'Functor'
35801inline OnceCallback<MakeUnboundRunType<Functor, Args...>> BindOnce(
35802
```

2020-10-26 19:24 UTC, nornagon commented
@zcbenz should be fixed now.

2020-10-27 01:24 UTC, zcbenz approved these changes

2020-10-27 01:25 UTC, merged