feat: add focus and blur events for WebContents
electron/electron pull request #25873
Opened 2020-10-10 08:29 UTC by samuelmaddock

#### Description of Change

Adds 'focus' and 'blur' events to `WebContents`.

solves #22201

cc @electron/wg-api 

#### Checklist

- [x] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [x] relevant documentation is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: Added 'focus' and 'blur' events to `WebContents`

2020-10-13 02:03 UTC, zcbenz approved these changes

2020-10-13 17:19 UTC, samuelmaddock commented
@electron/wg-releases requesting to add 11-x-y backport label 🙇

2020-10-19 23:32 UTC, nornagon requested changes
Let's have a test :)

2020-10-19 23:53 UTC, jkleinsc commented
The API WG approved this at our Oct 19 2020 meeting.

2020-10-20 06:07 UTC, samuelmaddock commented
@nornagon Tests added

2020-10-20 19:53 UTC, nornagon approved these changes

2020-10-20 19:53 UTC, nornagon commented
Just to clarify, does this event also trigger when the browserwindow is focused (e.g. through alt+tab)? or only when focus stays in the browser window and switches between webcontentses?

2020-10-21 04:34 UTC, samuelmaddock commented
> 
> 
> Just to clarify, does this event also trigger when the browserwindow is focused (e.g. through alt+tab)? or only when focus stays in the browser window and switches between webcontentses?

It does trigger when focusing the `BrowserWindow`. I've added a test to confirm: 89ad21d

2020-10-21 18:31 UTC, nornagon commented
@samuelmaddock it looks like the new test is failing on macOS.

2020-10-28 23:26 UTC, jkleinsc commented
The releases WG approved this PR for backport to 11-x-y at the Oct 28, 2020 meeting

2020-11-02 16:21 UTC, jkleinsc commented
@samuelmaddock any updates on this?  Looks like we are close to being able to merge this if the test failures can be resolved.

2020-11-02 16:44 UTC, samuelmaddock commented
> 
> 
> @samuelmaddock any updates on this? Looks like we are close to being able to merge this if the test failures can be resolved.

No updates, I'll see if I can get around to this by the end of the week.

2021-11-18 22:12 UTC, lockieluke commented
please get this merged asap

2021-12-28 07:32 UTC, jolindroth commented
https://github.com/electron/electron/issues/22201

Any updates?

@samuelmaddock @jkleinsc @nornagon

2022-01-29 21:25 UTC, miniak approved these changes

2022-02-01 10:28 UTC, merged