docs: revised Notifications feature page
electron/electron pull request #25901
Opened 2020-10-12 22:21 UTC by bandantonio

#### Description of Change
Revised Notifications feature page:
* improved page structure
* added examples of notifications for both Main and Renderer processes

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] relevant documentation is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: revised and restructured Notifications feature page

2020-10-13 18:32 UTC, erickzhao requested changes

2020-10-13 18:32 UTC, erickzhao commented on docs/tutorial/notifications.md
> +### Show notifications in the Renderer process
The part above here:

> Electron conveniently allows developers to send notifications with the [HTML5 Notification API](https://notifications.spec.whatwg.org/), using the currently running operating system's native notification APIs to display it

should be listed under the `Renderer process` part. The overview should also mention in brief that the technique for renderer and main processes is different before jumping into each example.

2020-10-15 21:43 UTC, erickzhao commented on docs/tutorial/notifications.md
> +To detect whether or not you're allowed to send a notification, use the
I don't think `userland` should be in code blocks here. Maybe replace with "third-party" to avoid confusion with `electron-userland`?

2020-10-20 02:15 UTC, erickzhao approved these changes

2020-10-20 02:24 UTC, zcbenz approved these changes

2020-10-20 02:24 UTC, merged