docs: revised the web embeds feature page
electron/electron pull request #26008
Opened 2020-10-16 23:36 UTC by bandantonio

#### Description of Change

Revised the web embeds feature page

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] relevant documentation is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: Revised the web embeds feature page

2020-10-20 01:42 UTC, zcbenz requested changes
Can you make mention that we do not recommend using webview?
https://www.electronjs.org/docs/api/webview-tag#warning

2020-10-20 02:55 UTC, erickzhao requested changes

2020-10-20 02:55 UTC, erickzhao commented on docs/tutorial/web-embeds.md
>  # Web embeds in Electron
Do we want to keep `In Electron` here? All our are features are technically "in Electron". 😅

2020-10-20 02:55 UTC, erickzhao commented on docs/tutorial/web-embeds.md
> +explains the differences and capabilities of each option.
```suggestion
If you want to embed (third-party) web content in an Electron `BrowserWindow`,
there are three options available to you: `<iframe>` tags, `<webview>` tags,
and `BrowserViews`. Each one offers slightly different functionality and is
useful in different situations. To help you choose between these, this guide
explains the differences and capabilities of each option.
```

2020-10-20 02:55 UTC, erickzhao commented on docs/tutorial/web-embeds.md
> +## BrowserViews
```suggestion
### BrowserViews
```

2020-10-20 02:55 UTC, erickzhao commented on docs/tutorial/web-embeds.md
> +of them, which means that you will have to manage their position manually.
```suggestion
However, as `BrowserViews` are not a part of your DOM, but are rather overlaid on top
of them, you will have to manage their position manually.
```

2020-10-20 23:26 UTC, erickzhao requested changes

2020-10-20 23:26 UTC, erickzhao commented on docs/tutorial/web-embeds.md
> +> Important Note:
The note might fit better here right above the `webview` section

2020-10-21 17:06 UTC, erickzhao approved these changes

2020-10-21 17:06 UTC, erickzhao commented on docs/tutorial/web-embeds.md
> +by design.
```suggestion
> Important Note:
[we do not recommend you to use use WebViews](https://www.electronjs.org/docs/api/webview-tag#warning),
as this tag undergoes dramatic architectural changes that may affect stability
of your application. Consider switching to alternatives, like `iframe` and
Electron's `BrowserView`, or an architecture that avoids embedded content
by design.
```

A few extra commas and we're good, I think.

2020-10-21 23:58 UTC, erickzhao approved these changes

2020-10-22 00:34 UTC, zcbenz approved these changes

2020-10-22 02:08 UTC, merged