docs: revised the online-offline event detection feature page
electron/electron pull request #26017
Opened 2020-10-17 12:55 UTC by bandantonio

#### Description of Change
Revised the online-offline event detection feature page, reworked code samples, added screenshot that corresponds to the code sample

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] relevant documentation is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: Revised the online-offline event detection feature page, reworked code samples, added screenshot that corresponds to the code sample

2020-10-20 01:49 UTC, zcbenz requested changes
We are going to add an API to return online status in the main process, I think we can use the new API in this doc and merge after the API gets merged.

https://github.com/electron/electron/pull/21004

2020-10-20 02:14 UTC, erickzhao reviewed
Comments for change.

@zcbenz: does this mean that we should wait for the next Electron release to land in stable? I think `/docs/guides/` fetches its data from `master`, so the `net.online` API won't be usable for most users for a while after it lands.

2020-10-20 02:14 UTC, erickzhao commented on docs/tutorial/online-offline-events.md
> +## Event detection in the Renderer process
```suggestion
### Event detection in the Renderer process
```

2020-10-20 02:14 UTC, erickzhao commented on docs/tutorial/online-offline-events.md
> +## Event detection in the Main process
```suggestion
### Event detection in the Main process
```

2020-10-20 02:14 UTC, erickzhao commented on docs/tutorial/online-offline-events.md
> +offline (disconnected from the network).
```suggestion
The `navigator.onLine` attribute returns:
* `false` if all network requests are guaranteed to fail (e.g. when disconnected
from the network).
```

2020-10-20 02:23 UTC, zcbenz commented
> @zcbenz: does this mean that we should wait for the next Electron release to land in stable? I think `/docs/guides/` fetches its data from `master`, so the `net.online` API won't be usable for most users for a while after it lands.

Hmm I am fine landing current document first and then update it after the new API is stable, it would require some extra work though.

2020-10-20 17:34 UTC, erickzhao commented
Sounds good to me. @bandantonio's Season of Docs term is only until December, so let's ship faster and revisit later.

2020-10-20 23:24 UTC, erickzhao approved these changes

2020-10-21 06:46 UTC, zcbenz approved these changes

2020-10-21 06:46 UTC, merged