build: rename the v8 context snapshot on arm64 macOS builds
electron/electron pull request #26086
Opened 2020-10-21 19:54 UTC by MarshallOfSound

As in the patch description, in order to generate universal builds on macOS both the arm64 and x64 snapshots need to be available, this is only possible if they have unique filenames.  This adds a patch which I intend to upstream to Chromium to make this the default behavior (and make the filename powered by GN instead of being hardcoded everywhere)

Notes: no-notes

2020-10-21 20:40 UTC, jkleinsc approved these changes

2020-10-21 22:59 UTC, codebytere approved these changes

2020-10-26 03:31 UTC, zcbenz requested changes
arm64 build is failing with a strange error:

```
chruby: unknown Ruby: ruby-2.7
```

2020-10-27 19:09 UTC, MarshallOfSound commented
Looks like this is gonna land upstream, updated the patch to exactly match upstream

2020-10-27 20:50 UTC, merged