chore: use auto to avoid repeating type
electron/electron pull request #26113
Opened 2020-10-22 18:36 UTC by dsanders11

#### Description of Change
Another `clang-tidy` suggestion. Use `auto` when the type is already specified elsewhere in the statement.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)

#### Release Notes

Notes: none

2020-10-22 18:58 UTC, ckerr approved these changes

2020-10-22 18:59 UTC, ckerr commented
@dsanders11  We usually backport changes like this to older supported branches to reduce code shear between branches -- but this touches so many unrelated pieces, I'm curious to see how trop does with it :smile:

2020-10-22 19:27 UTC, dsanders11 commented
I think the answer to that is... not well, judging by the failed checks. 😄

2020-10-22 20:15 UTC, nornagon requested changes
I'm 👎  on this. Sometimes `auto` is better, but sometimes I specifically use the type name as documentation. I don't think being consistent across our codebase helps much here.

2020-10-22 20:20 UTC, ckerr commented
> I'm  on this. Sometimes `auto` is better, but sometimes I specifically use the type name as documentation. I don't think being consistent across our codebase helps much here.

@nornagon I think you might be misunderstanding PR? This is removing _redundant_ information, e.g.

```diff
- SomeTypeName* foo = static_cast<SomeTypeName*>(bar);
+ auto* foo = static_cast<SomeTypeName*>(bar);
```

s.t. only the redundancy is removed, not the explicit typing. I don't think you'd be losing any self-documenting properties with this use of `auto`.

2020-10-22 22:23 UTC, nornagon approved these changes
... you're right, sorry. 👍

2020-10-26 18:56 UTC, MarshallOfSound approved these changes

2020-10-26 18:56 UTC, merged