ci: cleanup up test app directories
electron/electron pull request #26122
Opened 2020-10-23 01:37 UTC by codebytere

Backport of #25145

See that PR for details.

Notes: none

2020-10-24 23:11 UTC, ckerr requested changes
Looks like this diff has a conflict?

2020-10-25 00:07 UTC, xdumsidedx approved these changes

2020-10-28 07:44 UTC, zcbenz approved these changes

2020-10-28 18:59 UTC, ckerr approved these changes

2020-10-28 19:00 UTC, merged