docs: revised windows taskbar page
electron/electron pull request #26120
Opened 2020-10-23 00:21 UTC by bandantonio

#### Description of Change

Revised windows taskbar page

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] relevant documentation is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: Revised windows taskbar page, unified structure of the sections

2020-10-24 00:06 UTC, erickzhao requested changes

2020-10-24 00:06 UTC, erickzhao commented on docs/tutorial/windows-taskbar.md
>  right-click the app's icon in the task bar. That context menu is called
```suggestion
right-click the app's icon in the taskbar. That context menu is called
```
spelling consistency

2020-10-24 00:06 UTC, erickzhao commented on docs/tutorial/windows-taskbar.md
> +In Windows, you can add a thumbnail toolbar with specified buttons to a taskbar
```suggestion
On Windows, you can add a thumbnail toolbar with specified buttons to a taskbar
```

2020-10-24 00:06 UTC, erickzhao commented on docs/tutorial/windows-taskbar.md
> +In Windows, you can highlight the taskbar button to get the user's attention.
```suggestion
On Windows, you can highlight the taskbar button to get the user's attention.
```

2020-10-24 00:06 UTC, erickzhao commented on docs/tutorial/windows-taskbar.md
> +> NOTE: Don't forget to call the `flashFrame` method with `false` to turn off
```suggestion
> NOTE: Don't forget to call `win.flashFrame(false)` to turn off
```

conciseness

2020-10-24 00:06 UTC, erickzhao commented on docs/tutorial/windows-taskbar.md
> +In Windows, a taskbar button can use a small overlay to display application
```suggestion
On Windows, a taskbar button can use a small overlay to display application
```

2020-10-25 00:39 UTC, taylorreilly1231 approved these changes

2020-10-25 23:35 UTC, erickzhao approved these changes

2020-10-27 01:31 UTC, zcbenz approved these changes

2020-10-27 01:31 UTC, merged

2020-10-27 15:16 UTC, taylorreilly1231 commented
Hi, I'm not sure if this is a person or a bot. I don't know alot at all
about phone's, encryption or cyber malware, but all of this is located on
my phone by an ex who stalks me and he also uses python I don't know what
that is and can literally control my phone. I have never gave permission or
granted access to my phone. I have Verizon and my own phone company can't
detect or take it off. I'm going to attach a file and if you would please
try to drcrypt it.

On Mon, Oct 26, 2020, 9:31 PM release-clerk[bot] <notifications@github.com>
wrote:

> *Release Notes Persisted*
>
> Revised windows taskbar page, unified structure of the sections
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/electron/electron/pull/26120#issuecomment-716919156>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARNB3TMP3WE5SAV3Y64UWGTSMYPI5ANCNFSM4S34GMUQ>
> .
>