docs: update issue template
electron/electron pull request #26293
Opened 2020-10-31 06:24 UTC by dsanders11

#### Description of Change
The issue template shown in the docs was outdated.

#### Checklist
- [x] PR description included and stakeholders cc'd

#### Release Notes

Notes: none

2020-11-02 16:37 UTC, ckerr reviewed
I really like the way this adds more structure to the template.

1. IMO it would make sense to reconcile this file with the template in `~/.github/ISSUE_TEMPLATE/`. (Actually... since everyone automatically sees the latter when they file a ticket, maybe we should focus on that one and remove this one from docs? I think the reason this one exists is because it predates the other.)

2. I suspect that people ignore instructions that are too long, so I like the issue template to be short and clear. To that end, most of my suggested changes are word golf -- and are therefore subjective, so feel free to push back if you like.

2020-11-02 16:37 UTC, ckerr commented on docs/development/issues.md
> +<!--  As an open source project with a dedicated but small maintainer team, it can sometimes take a long time for issues to be addressed so please be patient and we will get back to you as soon as we
```suggestion
<!--  Please be patient! We are a small team.
```

2020-11-02 16:37 UTC, ckerr commented on docs/development/issues.md
> +<!-- Please ensure you've completed the following steps by replacing [ ] with [x]-->
```suggestion
<!-- Please replace [ ] with [x] after completing each step -->
```

2020-11-02 16:37 UTC, ckerr commented on docs/development/issues.md
> +For bugs that can be encapsulated in a small experiment, you can use Electron Fiddle (https://github.com/electron/fiddle) to publish your example to a GitHub Gist and link it your bug report.
```suggestion
For bugs that can be encapsulated in a small experiment, please use Electron Fiddle (https://github.com/electron/fiddle) to publish your example to a GitHub Gist and link it your bug report.
```

2020-11-02 16:37 UTC, ckerr commented on docs/development/issues.md
> +* [ ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
```suggestion
* [ ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md).
```

2020-11-02 16:37 UTC, ckerr commented on docs/development/issues.md
> +* [ ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
```suggestion
* [ ] I will follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md).
```

2020-11-02 16:37 UTC, ckerr commented on docs/development/issues.md
> +* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success.
```suggestion
* [ ] I looked but did not find this issue in the [issue tracker](https://github.com/electron/electron/issues).
```

2020-11-02 16:37 UTC, ckerr commented on docs/development/issues.md
> +  * <!-- (Platform and Version) e.g. macOS 10.13.6 / Windows 10 (1803) / Ubuntu 18.04 x64 -->
```suggestion
  * <!-- (Platform and Version) e.g. macOS 10.13.6 / Windows 10 (1803) / Ubuntu 20.04 x64 -->
```

2020-11-02 16:37 UTC, ckerr commented on docs/development/issues.md
> +  * <!-- (if applicable) e.g. 3.1.0 -->
```suggestion
  * <!-- (if applicable) e.g. 10.1.5 -->
```

2020-11-02 16:37 UTC, ckerr commented on docs/development/issues.md
> +<!-- A clear and concise description of what you expected to happen. -->
```suggestion
<!-- Describe what you expected to happen. -->
```

2020-11-02 16:37 UTC, ckerr commented on docs/development/issues.md
> +<!-- A clear and concise description of what actually happened. -->
```suggestion
<!-- Describe what actually happened. -->
```

2020-11-02 16:37 UTC, ckerr commented on docs/development/issues.md
> +-->
These paragraphs could probably all go in one `<!--` ... `-->` block to reduce the visual nosiness

2020-11-02 16:37 UTC, ckerr commented on docs/development/issues.md
> +<!-- If applicable, add screenshots to help explain your problem. -->
```suggestion
<!-- If applicable, add screenshots to help explain the issue. -->
```

2020-11-02 16:37 UTC, ckerr commented on docs/development/issues.md
> +<!-- Add any other context about the problem here. -->
```suggestion
<!-- Add any other context about the issue here. -->
```

2020-11-02 16:37 UTC, ckerr commented on docs/development/issues.md
>  If you provide a URL, please list the commands required to clone/setup/run your repo e.g.
```suggestion
If you provide a URL, please list the steps to use your repo e.g.
```

2020-11-02 17:21 UTC, dsanders11 commented
> 1. IMO it would make sense to reconcile this file with the template in `~/.github/ISSUE_TEMPLATE/`. (Actually... since everyone automatically sees the latter when they file a ticket, maybe we should focus on that one and remove this one from docs? I think the reason this one exists is because it predates the other.)

I think there may be some crossed wires on the communication here. I simply copy-and-pasted the one from `.github/ISSUE_TEMPLATE/Bug_Report.md` here. I assumed that originally it was an exact copy and they've since diverged.

As you said, it might make sense to remove from the docs, since it will inevitably always diverge.

2020-11-11 15:37 UTC, jkleinsc requested changes
I read through the comments on this PR and I think we should remove this section and replace it with a link to https://github.com/electron/electron/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md

2020-11-11 19:28 UTC, dsanders11 commented
@jkleinsc, dropped the embedded text and put in a link instead.

2020-11-12 14:11 UTC, jkleinsc approved these changes

2020-11-12 14:12 UTC, jkleinsc commented
Merging as CI failure unrelated to doc change.

2020-11-12 14:12 UTC, merged