feat: add support for spelling panel on macOS
electron/electron pull request #26332
Opened 2020-11-04 01:18 UTC by zcbenz

#### Description of Change

Close #3211.

This PR adds 2 menu item roles `showSpellingPanel ` and `checkSpelling`, which map to the "Show Spelling and Grammar" and "Check Document Now" menu items on macOS.

There are also lots of code added to make the spelling panel work.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [x] relevant documentation is changed or added
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: Add `showSpellingPanel ` and `checkSpelling` menu item roles.

2020-11-10 00:52 UTC, MarshallOfSound requested changes
Just requesting changes so I can remember why I didn't do this (use the panel host)

2020-11-10 01:35 UTC, jkleinsc commented
The API WG approved this PR at our Nov 9, 2020 meeting

2020-11-10 01:52 UTC, zcbenz commented
@MarshallOfSound One annoying problem I met was, once the spelling panel was opened it would persist every time when the program started. Not sure if you met the same one.

2021-01-25 17:52 UTC, codebytere commented
@zcbenz would you please rebase this?

2021-01-26 00:37 UTC, codebytere commented
@MarshallOfSound do you still have concerns about this one?

2022-03-19 22:50 UTC, miniak commented
@zcbenz are you still planning to land this PR?

2022-03-21 00:46 UTC, closed without merging