fix: crash when invoking app.quit()
electron/electron pull request #26435
Opened 2020-11-10 21:48 UTC by codebytere

#### Description of Change

Closes https://github.com/electron/electron/issues/26423.

Fixes a crash seen when calling `app.quit()` inside navigation events like `did-finish-load`, `did-fail-load`, etc. This was happening because we were quitting synchronously in the same tick before all observers had finished notifying, as confirmed by the fact that calling `setTimeout(() => { app.quit() })` also solved the problem. We fix this by delaying a tick.

cc @MarshallOfSound @nornagon @jkleinsc 

<details>
<Summary>Stacktrace</Summary>

```
55429:1110/134149.999064:FATAL:web_contents_impl.cc(879)] Check failed: !observers_.is_notifying_observers(). 
0   Electron Framework                  0x00000001143d3769 base::debug::CollectStackTrace(void**, unsigned long) + 9
1   Electron Framework                  0x00000001142c7c63 base::debug::StackTrace::StackTrace() + 19
2   Electron Framework                  0x00000001142e8115 logging::LogMessage::~LogMessage() + 261
3   Electron Framework                  0x00000001142e8fde logging::LogMessage::~LogMessage() + 14
4   Electron Framework                  0x00000001133c0360 content::WebContentsImpl::~WebContentsImpl() + 352
5   Electron Framework                  0x00000001133c278e content::WebContentsImpl::~WebContentsImpl() + 14
6   Electron Framework                  0x000000010eb55396 electron::InspectableWebContents::~InspectableWebContents() + 262
7   Electron Framework                  0x000000010eb5560e electron::InspectableWebContents::~InspectableWebContents() + 14
8   Electron Framework                  0x000000010ea27651 electron::api::BrowserWindow::Cleanup() + 193
9   Electron Framework                  0x000000010ea285cb electron::api::BrowserWindow::OnWindowClosed() + 27
10  Electron Framework                  0x000000010eb18363 electron::NativeWindow::NotifyWindowClosed() + 323
11  Electron Framework                  0x000000010ebfe7ad -[ElectronNSWindowDelegate windowWillClose:] + 45
```
</details>

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: Fixes a crash seen when calling `app.quit()` inside some navigation events.

2020-11-10 22:05 UTC, nornagon requested changes
isn't this what the `is_shutting_down` check is supposed to catch?

I'm not a fan of adding more PostTasks to shutdown. It's already an extremely complex and fragile process and this makes it worse.

2020-11-10 22:23 UTC, codebytere commented
@nornagon the way this was previously means that it would destroy synchronously if it _was_ shutting down - perhaps it should just unilaterally do so

2020-11-10 22:31 UTC, codebytere commented on shell/browser/browser.h
> -  bool is_quiting() const { return is_quiting_; }
unused

2020-11-11 03:12 UTC, deepak1556 requested changes
This change brings back https://github.com/electron/electron/pull/15541 , please refer https://github.com/electron/electron/issues/15133#issuecomment-434966976 thread for context.

I wouldn't encourage this api usage pattern from users, we can instead document how `app.quit` behaves and why it is not safe to call from within webContent event handlers.

2020-11-11 03:14 UTC, codebytere commented
@deepak1556 fair - i'd like to somehow prevent a hard crash though

2020-11-11 04:04 UTC, deepak1556 commented
The shutdown behavior in chromium changes over versions, there are hard expectations from the runtime for the tasks that can be posted during shutdown and we have aligned our api with it. At the same time, webContents observers also has expectations about synchronous destructions. The case in question should be treated as a bad `CHECK`, we can instead throw an error for such use cases and have documentation for better design.

2020-11-13 23:16 UTC, nornagon commented
Should `app.quit()` be deprecated and replaced with, e.g. `app.quitSoon()` that calls `PostTask()`?

2020-11-18 01:34 UTC, zcbenz requested changes
This is not a problem of `app.quit`, the same crash happens if you call `win.close()` or `win.webContents.destroy()`.

We usually solve this kind of crashes by delaying the event, for example https://github.com/electron/electron/pull/3643. But I'm fine documenting the crash to let users avoid it themselves, since the behavior may change after every Chromium upgrade.

2021-02-09 16:46 UTC, closed without merging