feat: add support for DOM elements going over the context bridge
electron/electron pull request #26776
Opened 2020-12-01 23:30 UTC by MarshallOfSound

As in title and as in notes, uses blink APIs to safely transfer a WebElement reference from one context to another

Notes: Added support for passing DOM elements over the context bridge

2020-12-01 23:44 UTC, nornagon requested changes
needs docs.

do these tests already include sending WebElements in both directions across the bridge?

2020-12-01 23:58 UTC, MarshallOfSound commented
@nornagon Docs updated, tests go both ways 👍

2020-12-07 21:57 UTC, MarshallOfSound commented on docs/api/context-bridge.md
> +| `HTMLElement` | Complex | ✅ | ✅ | Prototype modifications are dropped.  Sending custom elements will not work. |
@nornagon The "FromV8" part of this comes from `WebElement` and the "ToV8" comes from `WebNode`.  So I think that means we can't support `Node`'s 🤔

2020-12-07 23:39 UTC, nornagon approved these changes

2020-12-08 01:49 UTC, miniak approved these changes

2020-12-10 20:41 UTC, codebytere approved these changes

2020-12-10 21:03 UTC, merged