fix: add missing 'context-menu' values
electron/electron pull request #26788
Opened 2020-12-02 05:28 UTC by codebytere

#### Description of Change

This PR fills in a nontrivial amount of data missing from the object emitted by the 'context-menu' event. It'd been a significant amount of time since this was last updated, so a number of fields have been added to the object which may be useful to users handling the event and which we should therefore expose.

cc @zcbenz @jkleinsc @MarshallOfSound 

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] relevant documentation is changed or added
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: Add missing fields to the parameters emitted as part of the `context-menu` event.

2020-12-02 15:44 UTC, jkleinsc requested changes
LGTM apart from a small doc change needed

2020-12-02 15:44 UTC, jkleinsc commented on docs/api/web-contents.md
`canSave` is missing from docs here

2020-12-02 18:57 UTC, MarshallOfSound requested changes
Can we make sure this is tagged as `feat:`

2020-12-02 18:57 UTC, MarshallOfSound commented on docs/api/web-contents.md
> +    * `canTranslate` Boolean - Whether the renderer believes it can perform translation.
This will never be `true` in Electron as we don't (and won't) have a translation service

2020-12-02 19:59 UTC, MarshallOfSound approved these changes

2020-12-03 06:57 UTC, zcbenz approved these changes

2020-12-07 12:48 UTC, jkleinsc approved these changes

2020-12-07 12:49 UTC, jkleinsc commented
API LGTM

2020-12-08 19:16 UTC, nornagon reviewed
There are a few fields that still aren't exposed here, e.g. [writing_direction_*](https://source.chromium.org/chromium/chromium/src/+/master:content/public/common/untrustworthy_context_menu_params.h;l=127;drc=02f28360f2f6588ca2428ef93c8129e0a8cc231c), [impression](https://source.chromium.org/chromium/chromium/src/+/master:content/public/common/untrustworthy_context_menu_params.h;l=75;drc=02f28360f2f6588ca2428ef93c8129e0a8cc231c). Are there any particular reasons for these omissions?

2020-12-10 21:43 UTC, miniak approved these changes

2020-12-10 21:45 UTC, sick78 commented
so what i not get paid ? 

Sent from my iPhone

> On Dec 10, 2020, at 4:45 PM, Milan Burda <notifications@github.com> wrote:
> 
> ﻿
> @miniak approved this pull request.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2020-12-10 21:45 UTC, sick78 commented
so what i not get paid ? 


Sent from my iPhone

> On Dec 10, 2020, at 4:45 PM, Milan Burda <notifications@github.com> wrote:
> 
> ﻿
> @miniak approved this pull request.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2020-12-16 05:32 UTC, merged