feat: add support for webContents option in BrowserView
electron/electron pull request #26802
Opened 2020-12-02 17:32 UTC by sentialx

#### Description of Change
This PR adds support for `webContents` option in BrowserView, which works similarly as in BrowserWindow. Since the new `webContents.setWindowOpenHandler` doesn't support BrowserViews, we can at least listen to the internal `-add-new-contents` event and create a BrowserView with provided `webContents`. This PR will also help in adding support for BrowserView in `setWindowOpenHandler` in the future.

Closes #24833

Could this be backported to 12-x-y?

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

Since it's a hidden API, I think it's not worth mentioning this change in the release notes.

2020-12-08 19:44 UTC, nornagon commented
I'm not sure how I understand the way this would work—would you pass `show: false` in the BrowserWindowConstructor options in `setWindowOpenOverrideHandler`, so the BrowserWindow would still be created behind the scenes but hidden, and then yank the WebContents out of it and put it in a BrowserView? That seems like it might cause other problems 🤔

2020-12-08 21:12 UTC, sentialx commented
It allows us to override the internal `-add-new-contents` event and implement our own way to create a BrowserView
```ts
tab.webContents.removeAllListeners('-add-new-contents' as any);
  tab.webContents.on(
    '-add-new-contents' as any,
    (
      event: any,
      webContents: Electron.WebContents,
      disposition: string,
      _userGesture: boolean,
      _left: number,
      _top: number,
      _width: number,
      _height: number,
      url: string,
      frameName: string,
      referrer: Electron.Referrer,
      rawFeatures: string,
      postData: PostData,
    ) => {
      if (
        disposition !== 'foreground-tab' &&
        disposition !== 'new-window' &&
        disposition !== 'background-tab'
      ) {
        event.preventDefault();
        return;
      }
      new BrowserView({ webContents });
    },
  );
```

2020-12-09 00:32 UTC, nornagon commented
Given this API is intended to be undocumented, I'm downgrading from `semver/minor` to `semver/patch` and removing the API review request.

JFYI, we don't support overriding `-add-new-contents` and it's entirely possible that this workaround will break in future. I'd encourage you to define and document a public API that accomplishes this if you want this functionality to be stable.

2020-12-09 00:32 UTC, nornagon requested changes
Please add some tests, thanks!

2020-12-14 11:17 UTC, sentialx commented
@nornagon done.

2020-12-14 16:38 UTC, jkleinsc approved these changes

2020-12-14 18:23 UTC, nornagon approved these changes

2020-12-14 23:17 UTC, sentialx commented
Sorry for changing my mind, but would it be possible to also backport to 10 and 11?

2020-12-15 23:47 UTC, zcbenz approved these changes

2020-12-15 23:47 UTC, zcbenz commented
> Sorry for changing my mind, but would it be possible to also backport to 10 and 11?

This is for @electron/wg-releases to decide, I'll add related tags.

2020-12-15 23:52 UTC, merged

2020-12-17 00:17 UTC, VerteDinde commented
Hey folks, the Releases WG approved this for backport - we wanted to confirm, this backport will result in a patch bump, not a minor bump, right? Thanks!

2021-01-05 04:58 UTC, PalmerAL commented
Is there any plan to turn this into a public API? This would be really useful for me, but I'm concerned about depending on it as long as it remains undocumented.

2021-05-08 11:56 UTC, pOoOf commented
Hey guys, i am trying to use this API to open a browserview as a guest window upon window.open and this is what i am doing to make it work

``` 
rightPaneWindowRef.webContents.removeAllListeners('-add-new-contents');
rightPaneWindowRef.webContents.on(
  '-add-new-contents',
  (
    newViewevent,
    webContents,
    disposition,
    _userGesture,
    _left,
    _top,
    _width,
    _height,
    newViewurl
  ) => {
    console.log({ disposition, newViewurl });
    const newView = new BrowserView({
      ...browserViewConfig,
      webContents,
    });
    mainWindow.addBrowserView(newView);
    newView.setBounds({
      x: leftViewWidth + 100,
      y: HEADER_HEIGHT + 100,
      width: 600,
      height: 600,
    });
  }
);
```

Now this works fine but when i try to close the BrowserView by clicking on any option on the UI(it may be calling `window.opener`), the application crashes.

Can anyone tell me what i could be doing wrong here?

Also what @sentialx suggested doesn't work, this code below doesn't open any `BrowserView` and nothing is visible on the UI utill i add this `BrowserView` into the BrowserWindow using `addBrowserWindow` method
```
tab.webContents.removeAllListeners('-add-new-contents' as any);
  tab.webContents.on(
    '-add-new-contents' as any,
    (
      event: any,
      webContents: Electron.WebContents,
      disposition: string,
      _userGesture: boolean,
      _left: number,
      _top: number,
      _width: number,
      _height: number,
      url: string,
      frameName: string,
      referrer: Electron.Referrer,
      rawFeatures: string,
      postData: PostData,
    ) => {
      if (
        disposition !== 'foreground-tab' &&
        disposition !== 'new-window' &&
        disposition !== 'background-tab'
      ) {
        event.preventDefault();
        return;
      }
      new BrowserView({ webContents });
    },
  );
```

2021-05-12 05:38 UTC, PalmerAL commented
In my case, removing the view from the window and calling `webContents.destroy()` ([code](https://github.com/minbrowser/min/blob/3dfc06bbe7e71eceb85312d0e6400c520f39fde6/main/viewManager.js#L111)). It doesn’t crash every time though, so there may be something else going on. I’ll put together a testcase sometime in the next couple days and see what I can figure out.

2021-05-12 08:12 UTC, pOoOf commented
> Now this works fine but when i try to close the BrowserView by clicking on any option on the UI(it may be calling `window.opener`), the application crashes.

When i said the application crashes, the application wasn't actually crashing which i later realized, what actually was happening was that, the new BrowserView(new Guest window) was closing the mainWindow upon calling window.close, i guess this is also an [existing issue](https://github.com/electron/electron/issues/28260) when we use BrowserView as a guest window

2021-05-14 21:46 UTC, PalmerAL commented
In my case, it is actually crashing, but after testing it again, I'm only seeing the crash infrequently (maybe 1/20 view closes?). I may still try to make a testcase at some point, but I don't think I can until I find a way to reproduce it consistently.

I don't have an actual crash report; this is what I get as console output:
```
[0514/162332.291416:WARNING:process_memory_mac.cc(93)] mach_vm_read(0x7ffee6d15000, 0x2000): (os/kern) invalid address (1)
[1] [0514/162332.520512:WARNING:crash_report_exception_handler.cc(240)] UniversalExceptionRaise: (os/kern) failure (5)
```
But that's probably not very helpful for diagnosing.