Add port / user information is standard schemes
electron/electron pull request #26803
Opened 2020-12-02 19:59 UTC by RangerMauve

#### Description of Change

Fixes #24725 by registering standard schemes as having host and username fields.

This issue was breaking support for `gemini://` URLs

What's the best way to add a test for this use case?

#### Checklist

- [ ] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [ ] relevant documentation is changed or added
- [ ] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: 

Custom protocol schemes can now have ports and user information

2020-12-04 21:18 UTC, RangerMauve commented
I don't think the CI error is related to this PR, but I'm not sure how to verify

`not ok 1127 session.serviceWorkers getFromVersionID() should report the correct script url and scope
  Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (C:\projects\src\electron\spec-main\api-service-workers-spec.ts)`

2020-12-04 21:30 UTC, MarshallOfSound commented
@RangerMauve for some reason CircleCI didn't kick off builds for this PR, can you sign in here --> https://app.circleci.com/pipelines/github/electron/electron

And then push a new commit to this branch to re-trigger CI?

2020-12-08 03:42 UTC, RangerMauve commented
@MarshallOfSound Logged into the CI and pushed a docs commit. 😁

2020-12-08 04:43 UTC, zcbenz requested changes
Requesting changes since a test needs to be added. You can find examples of tests in `spec-main/api-protocol-spec.ts`.

2021-01-19 11:20 UTC, zcbenz commented
I'm closing this PR since it does not work.

2021-01-19 11:20 UTC, closed without merging

2021-02-10 23:20 UTC, RangerMauve commented
I'd really like to take another shot at this but sadly I'm having trouble compiling electron from source on Pop OS.

Is there a way to set up build tools without manually setting up depot_tools and the such? maybe a docker container?

2021-02-10 23:35 UTC, RangerMauve commented
Gonna try again and investigate the error that was found by @zcbenz

2021-02-11 08:30 UTC, zcbenz commented
> I'd really like to take another shot at this but sadly I'm having trouble compiling electron from source on Pop OS.
> 
> Is there a way to set up build tools without manually setting up depot_tools and the such? maybe a docker container?

You can use this tool to make building electron easier: https://github.com/electron/build-tools

2021-02-11 22:48 UTC, RangerMauve commented
@zcbenz Thanks! I actually tried that out and it helped, however I ran into this issue due to me running Ubuntu 20. 😅 https://github.com/electron/electron/issues/27704#issuecomment-777683733

2021-08-02 02:37 UTC, clekili commented
@RangerMauve were you able to get electron to build on pop os at the end? I am hitting the same issue with `libgnome-keyring-dev` and `python-dbusmock`