docs: NSVisualEffectMaterialDark has been deprecated and removed as of macOS 10.15
electron/electron pull request #27125
Opened 2020-12-25 18:18 UTC by theLMGN

#### Description of Change
When using a depreciated vibrancy style in your app, the following message is printed to console. This PR updates so it matches the docs.
`(node:33818) electron: NSVisualEffectMaterialDark has been deprecated and removed as of macOS 10.15.`

#### Checklist

- [x] PR description included and stakeholders cc'd (unsure what this means)

#### Release Notes

Notes: none

2020-12-28 18:55 UTC, codebytere requested changes

2020-12-28 18:55 UTC, codebytere commented on docs/api/browser-window.md
> +    `menu`, `popover`, `sidebar`, `medium-light`, `ultra-dark`, `header`, `sheet`, `window`, `hud`, `fullscreen-ui`, `tooltip`, `content`, `under-window`, or `under-page`.  Please note that using `fr
Let's make this: 

> Also note that `appearance-based`, `light`, `dark`, `medium-light`, and `ultra-dark` are deprecated and have been removed in macOS Catalina (10.15).

2021-01-05 02:33 UTC, zcbenz approved these changes

2021-01-05 21:39 UTC, codebytere approved these changes

2021-01-05 21:39 UTC, merged