docs: fix header level of some events in app.md
electron/electron pull request #27860
Opened 2021-02-22 19:13 UTC by nornagon

Makes the TOC look weird

![image](https://user-images.githubusercontent.com/172800/108757676-00924300-74ff-11eb-8b14-caf444e62fa6.png)

Notes: none

2021-02-22 19:25 UTC, Jkweeks requested changes
Why is it gone I need it to be put intoy bank account

2021-02-22 20:29 UTC, MarshallOfSound approved these changes

2021-02-22 20:54 UTC, codebytere approved these changes

2021-02-24 09:04 UTC, zcbenz approved these changes

2021-02-24 09:04 UTC, merged