docs: suspend and resume are available on Linux #27761
electron/electron pull request #27958
Opened 2021-03-02 12:22 UTC by ssiatras

#### Description of Change
Closes #27761. 

Updates accordingly PowerMonitor documentation for `suspend` and `resume`, which were added on Linux by #25149.

#### Checklist
- [x] relevant documentation is changed or added

#### Release Notes

Notes: None

2021-03-02 17:40 UTC, codebytere submitted a review, later dismissed
-

2021-03-02 17:41 UTC, codebytere requested changes

2021-03-02 17:41 UTC, codebytere commented on docs/api/power-monitor.md
> +### Event: 'suspend' _Linux_ _macOS_ _Windows_
We only add platforms when there's partial support - this can now just be `### Event: 'suspend'`

2021-03-02 17:41 UTC, codebytere commented on docs/api/power-monitor.md
> +### Event: 'resume' _Linux_ _macOS_ _Windows_
Same as above

2021-03-02 18:36 UTC, codebytere approved these changes

2021-03-03 20:09 UTC, ckerr approved these changes

2021-03-04 08:10 UTC, zcbenz approved these changes

2021-03-05 01:11 UTC, merged