test: running child app under ASan might receive SIGKILL
electron/electron pull request #28156
Opened 2021-03-12 12:24 UTC by zcbenz

#### Description of Change

Under ASan build, the tests that spawn child Electron apps may receive SIGKILL because of out of memory.

I believe Circle CI does not allow enabling swap space, so disabling those tests under ASan build seems to be the best choice.

This PR also moves some tests to `spec-main/fixtures/crash-cases`.

#### Release Notes

Notes: none

2021-03-12 17:19 UTC, codebytere approved these changes

2021-03-15 17:31 UTC, jkleinsc requested changes
Looks like some of the newly enabled tests are failing

2021-03-16 01:35 UTC, zcbenz commented
@jkleinsc This PR only disables more tests, so it is not responsible for the new failing tests.

I have pushed another commit to also disable webview tests for ASan, which has the same problem that the renderer process of webview are being killed because of out of memory.

The asan tests are green now.

2021-03-16 20:51 UTC, jkleinsc approved these changes

2021-03-16 21:02 UTC, merged