docs: Update Quick Start Guide for Electron 12
electron/electron pull request #28223
Opened 2021-03-16 18:00 UTC by itsananderson

#### Description of Change

With `contextIsolation` enabled by default in Electron 12, the Getting Started Guide no longer works as it is written. In order for the basic example to display values from `process.versions`, this change adds a `preload.js` to the example.

Adding a preload script does increase the complexity of the "hello world" example, but setting `contextIsolation: false` in the example code seemed like a less ideal solution since it encourages insecure practices

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] relevant documentation is changed or added

#### Release Notes

Notes: no-notes

2021-03-16 21:06 UTC, jkleinsc requested changes
Overall, looks good to me - just a few tweaks.

2021-03-16 21:06 UTC, jkleinsc commented on docs/tutorial/quick-start.md
> +> NOTE: To access the Node.js API from the Renderer process, you need to set the `nodeIntegration` preference to `true` and the `contextIsolation` preference to `false`.
```suggestion
> NOTE: To access the Node.js API from the Renderer process, you need to set the `nodeIntegration` preference to `true` and the `contextIsolation` preference to `false`.  Please note that access to the Node.js API in any renderer that loads remote content is not recommended for [security reasons](../tutorial/security.md#2-do-not-enable-nodejs-integration-for-remote-content).
```

2021-03-16 21:22 UTC, jkleinsc approved these changes

2021-03-16 21:35 UTC, erickzhao approved these changes

2021-03-16 23:45 UTC, merged

2026-02-15 05:20 UTC, MGO288LNE3BG commented on docs/tutorial/quick-start.md
For how long

2026-02-15 05:28 UTC, MGO288LNE3BG commented on docs/tutorial/quick-start.md
> -app.whenReady().then(createWindow)
Put money in PayPal account

2026-02-15 05:28 UTC, MGO288LNE3BG commented on docs/tutorial/quick-start.md
> +2. Line 2: Second, you import the `path` package which provides utility functions for file paths.
Put money in PayPal account amount of 3.0000

2026-02-15 05:30 UTC, MGO288LNE3BG commented on docs/tutorial/quick-start.md
> +This is the web page you want to display once the application is initialized. This web page represents the Renderer process. You can create multiple browser windows, where each window uses its own in
29.0000 put money in PayPal account at 11:30pm

2026-02-15 05:33 UTC, MGO288LNE3BG commented on docs/tutorial/quick-start.md
```suggestion
To use a Node.js module, you first need to install it as a dependency:
```here put money in PayPal account $39.0000 then we introduce

2026-02-15 05:35 UTC, MGO288LNE3BG commented on docs/fiddles/quick-start/main.js
#49747

2026-05-25 20:42 UTC, njarhoho1-a11y commented
~~~~b6ff12ef7f07b1ee2e7bcdca0d4b1d20c815e77b