doc: desktopCapturer only for renderer process
electron/electron pull request #28262
Opened 2021-03-18 03:38 UTC by xland

#### Description of Change
One can require `desktopCapturer` in main process
but when run these code in main process app will crash silently.
```js
desktopCapturer
  .getSources({
    types: ['screen'],
    thumbnailSize: { width: 1920, height: 1080 }, //实际屏幕尺寸可以通过主进程的screen模块获得
  })
  .then((imgs) => {
    console.log(imgs[0].thumbnail.toDataURL())
  })
```
#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [x] relevant documentation is changed or added
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: doc: desktopCapturer only for renderer process

2021-03-18 08:18 UTC, codebytere commented
@xland what operating system are you using? This sample you provided works as intended on macOS

2021-03-18 08:18 UTC, codebytere reviewed
@xland what operating system are you using? This [sample](https://gist.github.com/6cec06d62cd5099973c43e2dab134616) you provided works as intended on macOS 🤔

2021-03-18 11:42 UTC, miniak requested changes
@xland changing documentation is not the correct way to fix such issue

2021-03-19 01:18 UTC, xland commented
@codebytere @miniak 

1: `desktopCapturer.getSources` can only be used when app ready in main process.
2: `docs/README.md`'s API References section said `desktopCapturer` is only for renderer process

This pr can be closed and I will create a new pr to update the document.

2021-03-21 04:14 UTC, closed without merging