build: add boringssl headers to node_headers tarball
electron/electron pull request #28288
Opened 2021-03-19 05:21 UTC by seesemichaelj

#### Description of Change

NodeJS adds OpenSSL headers to the header tarball, but Electron
currently doesn't add the BoringSSL headers to the header tarball.
This patch adds the necessary build commands to copy the headers
into the `node_headers` directory prior to tarballing.

This PR resolves #27751

CC'ing others interested in this PR: @davidmurdoch @alexhultman

#### Checklist

- [x] PR description included and stakeholders cc'd (I'm not sure who the Electron maintainer stakeholders would be)
- [ ] `npm test` passes (have not been able to run them yet)
    - I'm not sure if these need to pass for this PR, but I'm having issues running the tests due to issues with dbusmock (similar to #27704, but I was able to install dbusmock using pip, but it throws an exception).
    - I will try to resolve these issues tomorrow and see if I get tests to run.
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: Added BoringSSL headers to node_headers tarball.

2021-03-19 18:13 UTC, seesemichaelj commented
@codebytere Do you know if the errors in the CI builds are applicable? Seems like the errors that are actually being reported are credential issues, is  this correct or is there something I can/should do to fix these errors?

```
GOMA:clang++ compiling ../../third_party/jsoncpp/source/src/lib_json/json_writer.cpp:*ERROR*: compiler_proxy [478.4521ms]: 
**************************************************************
Not logged in. Run this command and retry the build:
    pushd $GOMACLIENTDIR && vpython goma_auth.py login && popd
**************************************************************
```

Thanks!

2021-03-19 21:42 UTC, seesemichaelj commented
I've tried to run tests, but the issues at #27704 are preventing me from running the tests on my Ubuntu 20.04 setup. I can try getting a Windows environment set up to run the tests there if requested by the maintainers? I'm not sure how necessary this PR is to have tests, so don't want to put forward the effort unless explicitly requested.

Thanks for your time and consideration!

2021-03-21 18:55 UTC, alexhultman commented
Another question is whether the node.lib on Windows and node.exe exports the BoringSSL **symbols** or not. On regular Node.js it did not, so back in 2016 I PR:ed this.

Also I wonder how it is possible for Electron to have introduced a new ABI numbering system **only based on the fact BoringSSL is used**, while not even exporting said BoringSSL support to begin with - feels like a thought was dropped halfway through here - or am I missing something?

2021-03-22 17:24 UTC, nornagon commented
@alexhultman the main reason for the different ABI numbering is that we build a different version of V8 than Node.js, and apply patches as needed to accommodate.

2021-03-22 17:30 UTC, nornagon commented
and, also to @alexhultman's point, we do not export BoringSSL symbols, so this PR is somewhat useless without that.

Exporting BoringSSL symbols has been [discussed in the past](https://github.com/electron/electron/issues/13176#issuecomment-610501697) and decided against, so unless something significant has changed since then, I'm still 👎  on exporting these symbols.

2021-03-22 17:30 UTC, nornagon requested changes
(as above)

2021-03-22 17:50 UTC, alexhultman commented
> so this PR is somewhat useless without that.

This PR is **entirely useless, dangerous and invalid** unless you also export the matching symbols.

2021-03-22 17:53 UTC, nornagon commented
@alexhultman thanks, I've already stated that, please keep things calm and professional here as this is a workplace :)

2021-03-22 17:59 UTC, alexhultman commented
From where did you get the impression I was not calm? I added more information. You said it was "somewhat useless" I said it is entirely useless and also dangerous (since people can end up linking against wrong version, which breaks everything in subtle ways). You do not need to tell me how to act in public, I am not an animal.

2021-03-22 18:17 UTC, seesemichaelj commented
Thanks @alexhultman for providing your input on the necessities of exporting the symbols for this PR to be useful; makes sense, and I agree that the symbols would need to be exported to make sense.

Thank you @nornagon for the swift response to looking at this PR! I really appreciate the maintainers here at Electron and the time you take to address outside contributions.

I do think that the conversation is getting heated, but we can still recover and have a productive discourse about this.

For what it's worth, I agree with sentiments in the comment https://github.com/electron/electron/issues/13176#issuecomment-610305707, but I disagree with Electron's desire to diverge away from NodeJS practices. I understand that the group that maintains Electron is not associated with the group that maintains NodeJS, and you're providing an awesome tool for the public to benefit from. So what you end up deciding is the way it goes, and that's totally understandable. However, application developers that use NodeJS expect (maybe they shouldn't, I'm not sure) a mostly fluid transition using Electron from using NodeJS. I think it's important for large-reaching tools like Electron and NodeJS to stay lock-step in terms of how things are delivered unless absolutely necessary (i.e. need to use BoringSSL due to using Chromium), etc.

There's a really high chance I don't understand the full picture, and I apologize for my ignorance, but if Electron maintainers have strong opinions to not exporting symbols, then why are they still exported in NodeJS? This divergence causes industry issues of dependencies and tools that rely on the technology stack of NodeJS or Electron, but then hit a wall when trying to move forward with migrating/adopting the other library. If there was consistency, then we wouldn't be in this position.

Again, y'all are providing a free tool for everyone to thrive on, but being consistent (either by adopting the practices of NodeJS or by getting NodeJS to adopt Electron's practices) to me is the most important takeaway here. The outcome may cause issues (i.e. if NodeJS stops exporting the OpenSSL symbols, then @alexhultman's super valuable, extremely fast websocket server library https://github.com/uNetworking/uWebSockets.js would need potentially major changes [I'm not sure of the impact]).

This PR's hope was to try to close the divide between NodeJS and Electron one step closer. I'm happy to try to amend this PR to export the BoringSSL symbols if it's decided that Electron maintainers would be open to that. However, we (@davidmurdoch and I) from Truffle Suite can understand if you have strong reservations against that and will try to make do with that decision.

Again, I appreciate the time and consideration by the Electron maintainers, and you particularly @nornagon!

2021-03-22 18:39 UTC, seesemichaelj commented
> Do you have any specific 3rd-party native modules in mind that you're trying to build?

Yup! @alexhultman maintains https://github.com/uNetworking/uWebSockets.js which leverages the native library https://github.com/uNetworking/uWebSockets

As far as porting to work with BoringSSL; @alexhultman made it seem like the support would be relatively trivial, but I don't know if we've actually gotten to that point of integration yet.

2021-03-22 18:53 UTC, alexhultman commented
We support BoringSSL I use it all the time.

2022-02-24 23:02 UTC, miniak commented
@seesemichaelj what's the plan with this PR? there are no updates for almost a year

2022-02-24 23:18 UTC, seesemichaelj commented
@miniak As I no longer have a need for https://github.com/uNetworking/uWebSockets.js in Electron, I no longer have an opinion on the state of this PR. I'm going to close it; if others still need this, I welcome them to open their own PR.

2022-02-24 23:18 UTC, closed without merging

2022-02-25 08:05 UTC, alexhultman commented
We ship our own statically linked BoringSSL so this is no longer a problem for us.