fix: window.print() in pdf plugin
electron/electron pull request #28328
Opened 2021-03-22 14:31 UTC by codebytere

#### Description of Change

Fixes an issue where `window.print()` did not work properly when printing a pdf from the pdf plugin. Pulled from Chromium's [corresponding impl](https://source.chromium.org/chromium/chromium/src/+/master:chrome/renderer/printing/chrome_print_render_frame_helper_delegate.cc;l=64-81;drc=ce83ee3f482ef49409bf97c28dd28cd8da8072c7;bpv=1;bpt=1). 

Tested with https://gist.github.com/293b0a64d8564da954fc222b9aba9ce1.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: Fixed an issue where `window.print()` did not work properly when printing a pdf from the pdf plugin.

2021-03-22 14:32 UTC, codebytere commented on lib/browser/api/web-contents.ts
> +  // True, if the document source is modifiable. e.g. HTML and not PDF.
tangential fix - not directly related to the problem at hand.

2021-03-22 17:36 UTC, nornagon requested changes
can we have an automated test? :)

2021-03-22 17:39 UTC, codebytere commented
@nornagon what would you envision there? the issue with printing tests generally is that they create blocking dialogs we then can't get rid of - it's why we don't test `window.print()` in other contexts either

2021-03-22 17:46 UTC, nornagon commented
ah, i didn't realise there was a dialog involved, that's a shame. :okay:

2021-03-22 17:46 UTC, nornagon approved these changes

2021-03-22 19:02 UTC, deepak1556 approved these changes

2021-03-22 21:21 UTC, MarshallOfSound approved these changes

2021-03-23 13:39 UTC, jkleinsc approved these changes

2021-03-23 14:40 UTC, merged