refactor: remove more uses of v8::Isolate::GetCurrent()
electron/electron pull request #28369
Opened 2021-03-24 13:37 UTC by codebytere

#### Description of Change

`v8::Isolate::GetCurrent()` is deprecated, and we should be using our helper method where possible.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: none

2021-03-24 18:15 UTC, nornagon approved these changes

2021-03-25 06:03 UTC, zcbenz requested changes
`JavascriptEnvironment` only lives in the browser process, we can't use it in `shell/common` or `shell/renderer` files. 

There is a similar `blink::MainThreadIsolate()` API available in renderer, but since the code in renderer may run in workers with different isolates, I think the only safe way to replace `v8::Isolate::GetCurrent()` is to pass isolate explicitly.

2021-03-29 08:57 UTC, codebytere commented
@zcbenz i think this should do it - all changes I made here are either invoked in the main process or I now pass in the isolate explicitly

2021-03-29 10:42 UTC, zcbenz approved these changes

2021-03-29 10:44 UTC, codebytere commented
Test failures not germane.

2021-03-29 10:45 UTC, merged