chore: the minimum supported version is now 10.11
electron/electron pull request #28480
Opened 2021-04-01 22:03 UTC by MarshallOfSound

Notes: no-notes

2021-04-01 22:15 UTC, nornagon requested changes
IMO this deserves release notes.

2021-04-01 23:50 UTC, MarshallOfSound commented
@nornagon Maybe it does, but not in this PR.  The change was made in Electron 12 so if anything those notes should be retroactively updated.  Adding notes in this PR is misleading and incorrect as the fundamental OS limitation was modified a while back

2021-04-01 23:51 UTC, nornagon approved these changes

2021-04-01 23:51 UTC, nornagon commented
we should probably backport this to 12 then.

2021-04-02 07:21 UTC, codebytere approved these changes

2021-04-02 07:29 UTC, Aekewu approved these changes

2021-04-05 19:18 UTC, merged