Update native-file-drag-drop.md
electron/electron pull request #28652
Opened 2021-04-14 08:03 UTC by dengjie13520

electronic 12 + needs to set contextisolation to false

#### Description of Change

#### Checklist

- [ ] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [ ] relevant documentation is changed or added
- [ ] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes:

2021-04-15 00:24 UTC, MarshallOfSound requested changes
The example should be updated to work with `contextIsolation: true` rather than suggesting an insecure option be used

2021-04-18 00:08 UTC, miniak commented
@dengjie13520 also FYI it is Electron not "electronic"

2021-04-22 09:38 UTC, codebytere commented
@dengjie13520 would you like to move this PR forward?

2021-04-28 17:47 UTC, GrahamSH-LLK commented on docs/tutorial/native-file-drag-drop.md
> +Note: electronic 12 + needs to set contextisolation to false
You mean Electron, afaik. Also, there should be a period at the end.

2021-04-28 22:06 UTC, codebytere commented
Closing as no response has been given. Happy to consider re-opening though.

2021-04-28 22:06 UTC, closed without merging