fix: ensure the typescript definitions only export correct value types
electron/electron pull request #28712
Opened 2021-04-18 02:27 UTC by MarshallOfSound

In typescript there are two main types of "types" you can export, value types (class, const) and definition types (type, interface).  The typescript compiler will let anything declared via const or class be used as a value.  Unfortunately we were exporting a bunch of things (see the diff) as class/const when they weren't actually exported values. This lead to typescript being happy but the runtime throwing errors (not something we want).

This change passes "exported-in" context through our docs, to the parser and then to the definitions generator to ensure we only mark things as exported in the ts defs that we actually export.

Fixes #22167

This PR is currently targeting `update-ts-parser` as it relies on some of those changes and this shows the actual diff.

Notes: Fixed typescript export definitions such that not-exported values are not declared in the exports interface

2021-04-20 23:19 UTC, nornagon requested changes
I think "Exported in" is more confusing than "Process". Can we keep the previous verbiage?

2021-04-20 23:56 UTC, MarshallOfSound commented
@nornagon We have to distinguish between a module being "available" in a process and a module being "exported" in the `electron` module in that process.  If you have an alternative proposal for the words to use to distinguish that I'm open to suggestions, but we can't use the same verbiage in both cases.

2021-06-14 18:26 UTC, nornagon commented on docs/api/browser-window.md
> +Export in: [Main](../glossary.md#main-process)
Was this left by mistake?

2021-06-14 18:44 UTC, MarshallOfSound commented on docs/api/browser-window.md
> +Export in: [Main](../glossary.md#main-process)
Oh lol, was actually a typo lol

2021-06-15 19:09 UTC, nornagon approved these changes

2021-06-15 20:50 UTC, merged