Update dialog.md
electron/electron pull request #28747
Opened 2021-04-20 18:17 UTC by Tabea4

see #28718

#### Description of Change

#### Checklist

- [ ] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [ ] relevant documentation is changed or added
- [ ] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes:

2021-04-28 23:48 UTC, miniak commented
@Tabea4 instead of "some platforms will not show it" we should say which ones

2021-04-29 08:08 UTC, codebytere requested changes

2021-04-29 08:08 UTC, codebytere commented on docs/api/dialog.md
> +  * `title` String (optional) - Title of the dialog, some platforms will not show it.
This should specify the platforms on which it works. 

See
https://github.com/electron/electron/blob/2865d161b720e209f29ca84858492e095dc3e161/docs/api/dialog.md#L96-L103 for prior art.

2021-04-29 09:06 UTC, Tabea4 commented
@miniak @codebytere 
I think that this is not necessarily only a matter of the platform, but of the desktop environment. I’m on Ubuntu using the Gnome desktop environment. I don’t have the possibility to check this on every desktop environment, that’s why I just wanted to add a note, so that developers know that this might not work on their machine. This is similar to the option `title` of the `showMessageBoxSync` : https://www.electronjs.org/docs/api/dialog#dialogshowmessageboxsyncbrowserwindow-options, where it also only says `some platforms will not show it.`

2021-05-05 07:44 UTC, zcbenz reviewed
I think we could take this if it says "on Linux some desktop environments will not show it".

2021-05-05 15:47 UTC, Tabea4 commented
> I think we could take this if it says "on Linux some desktop environments will not show it".

I changed it accordingly.

2021-05-06 00:49 UTC, zcbenz approved these changes

2021-05-06 08:08 UTC, codebytere commented on docs/api/dialog.md
> +  * `title` String (optional) - Title of the dialog, on _Linux_ some desktop environments will not show it.
Let's clean this phrasing up a bit? 

> `title` String (optional) - The dialog title. Cannot be displayed on some Linux desktop environments.

2021-05-06 08:08 UTC, codebytere commented on docs/api/dialog.md
> +  * `title` String (optional) - Title of the dialog, on _Linux_ some desktop environments will not show it.
Same as above.

2021-05-06 09:03 UTC, Tabea4 commented on docs/api/dialog.md
> +  * `title` String (optional) - Title of the dialog, on _Linux_ some desktop environments will not show it.
Changed it as suggested

2021-05-06 09:04 UTC, Tabea4 commented on docs/api/dialog.md
> +  * `title` String (optional) - Title of the dialog, on _Linux_ some desktop environments will not show it.
Changed it as well

2021-05-19 07:43 UTC, codebytere approved these changes

2021-05-19 07:44 UTC, merged