chore: Browser::SetAppUserModelID is Windows only
electron/electron pull request #28909
Opened 2021-04-28 13:38 UTC by miniak

#### Description of Change
After #28127 this is Windows only https://github.com/electron/electron/blob/56c3103e73ac71bd6845a31a2e37f5ffd0810be7/shell/browser/api/electron_api_app.cc#L1538-L1541

#### Checklist
- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes

#### Release Notes
Notes: no-notes

2021-04-28 17:26 UTC, codebytere approved these changes

2021-04-28 19:52 UTC, MarshallOfSound requested changes
@nornagon you originally landed this https://github.com/electron/electron/commit/640a1451126b404a6a9557c6c080cc83d51805de

It doesn't have a ref but this is a breaking change (previously there was a noop provided on other platforms).  Can we get insight into why the change was made?

2021-04-28 19:55 UTC, nornagon commented
@MarshallOfSound because wstrings are windows only, so it wasn't compiling.

2021-04-28 20:01 UTC, MarshallOfSound commented
Gotcha, we should restore the other platform noop implementations in master and 13-x-y 👍  Probably easiest to do in JS land 😄

2021-04-28 20:01 UTC, MarshallOfSound commented
Closing this out in favor of the above mentioned solution

2021-04-28 23:40 UTC, miniak commented
@MarshallOfSound it still makes sense to merge this to remove dead code in C++

2021-04-29 01:41 UTC, MarshallOfSound approved these changes
Fair

2021-05-03 16:12 UTC, jkleinsc approved these changes

2021-05-03 16:13 UTC, jkleinsc commented
Merging as CI failure is unrelated to PR change.

2021-05-03 16:13 UTC, merged