Preload in worker script
electron/electron pull request #28923
Opened 2021-04-29 02:25 UTC by hamst

#### Description of Change
Add `preloadInWorker` for `webPreferences` in `BrowserWindow` to define a script to be loaded first before any other scripts in worker.

cc @codebytere 

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [x] relevant documentation is changed or added
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: Added preloadInWorker to define a script to be loaded first before any other scripts in worker.

2021-05-05 07:27 UTC, zcbenz requested changes
From the document it is unclear how this option works with `contextIsolation`, can you make it clear and add related tests?

And I think this option should either respect the `contextIsolation` option of the window, or just always run the preload script in isolated context. /cc @electron/wg-api

2021-05-05 07:27 UTC, zcbenz commented on lib/worker/init.ts
> +  // Export node bindings to global.
This file shares lots of code with `lib/renderer/init.ts`, can you move the shared code into a utility function? Like what `windowSetup` and `webViewInit` do.

2021-05-05 22:26 UTC, hamst commented
@zcbenz It seems that contextIsolation is not supported in WebWorkers, so adding preloadInWorker doesn't affect it in any ways. I will add some details in documents, as far as having tests with contextIsolation, will they be useful?

2021-05-06 01:11 UTC, zcbenz commented
The `contextIsolation` controls whether preload scripts should run in the web page's context or in a separate context, currently it is not related to WebWorker because WebWorker does not have preload scripts.

But since this PR is adding `preloadInWorker`, we have to define how `contextIsolation` affects preload scripts in WebWorker. We can either:
1. Make `preloadInWorker` respect the `contextIsolation` option that, `contextIsolation` should be able to control whether preload scripts should run in the worker script's context or in a separate context ;
2. Or ignore the  `contextIsolation` option and always run the preload scripts in separate context in WebWorker.

From current implementation, the preload scripts specified by `preloadInWorker` are running in the same context of the worker script, which is against the "secure by default" principle that we have in Electron's APIs.

2021-05-06 08:01 UTC, MarshallOfSound requested changes
Without solving the ctx isolation issue:

> This script will always have access to node APIs no matter whether node integration in worker is turned on or off.

is fundamentally a massive security vulnerability that we can't / won't land into this project.  Putting a hard block on this pending a proposal for how to deal with ctx isolation

2021-05-06 18:45 UTC, hamst commented
Right now we have an option `nodeIntegrationInWorker` but don't support `contextIsolation` in worker. Being enabled `nodeIntegrationInWorker` allows access to powerful API without any limitation for all web worker scripts loaded in webpage, and there is no way to limit this. Very unlikely that this option without `contextIsolation` support follows "secure by default" principle, and that's what we have today. So `contextIsolation` for worker must be supported no matter if we have `preloadInWorker` or not.
Option `preloadInWorker` makes things way better: you define the script with all access to API, and you can make some API visible for all workers, but it requires additional steps and unlikely could be done unintentionally. By default, nothing will be exposed. That's a big difference from security prospective.
So getting `contextIsolation` support for workers should be a separate task which must be done to be "secure by defaults" regardless `preloadInWorker`. As `contextIsolation` heavily relies on contextBridge module, some work needs to be done to relax the requirement to avoid using electron modules in workers https://www.electronjs.org/docs/tutorial/multithreading#available-apis and make the implementation thread-safe.

2021-05-07 02:29 UTC, zcbenz commented
@hamst Thanks for explaining, I see your point now. I'm good with this API, since it is an improvement over `nodeIntegrationInWorker` on security, before `contextIsolation` is supported in worker.

2021-05-07 17:59 UTC, hamst commented
Would be good to link the issue #28620 to this PR.

2021-05-07 18:31 UTC, closed without merging