update function createWindow()
electron/electron pull request #28924
Opened 2021-04-29 06:59 UTC by SergioBerrio

i have added an attribute which helped me to make the aplication run

#### Description of Change

#### Checklist

- [ ] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [ ] relevant documentation is changed or added
- [ ] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes:

2021-04-29 20:39 UTC, MarshallOfSound requested changes
As with other examples we should update the example to support `contextIsolation: true` rather than disabling an important security feature

2021-05-04 08:42 UTC, codebytere commented
@SergioBerrio please address the above comments if you would like for this PR to move forward!

2021-05-04 09:54 UTC, matthijsgroen commented on docs/tutorial/dark-mode.md
>      }
This was a thing that bothered me in the docs a bit.. why are the examples not using a 'preload' script and promoting the proper behavior? (That would be using `{ contextIsolation: true, nodeIntegration: false }` right?)

I wanted to fix all security related things and the consensus on stack overflow and guides would be: 'security', why bother. While the documentation on contextIsolation was actually really good and a way nicer way from the webapp to communicate with electron, since with the preload script the whole communication with electron is more like pure feature detection.

2021-05-13 02:06 UTC, zcbenz commented
I'm closing this PR since the example should be updated to use preload scripts instead, please let me know if you still plan to work on this PR and I'll reopen it.

2021-05-13 02:06 UTC, closed without merging