docs: Link to `BrowserView` from `webview` page
electron/electron pull request #28942
Opened 2021-04-29 21:52 UTC by hamstu

#### Description of Change
Make it easier to jump to the docs page on BrowserView. ✨ 

#### Checklist

- [ ] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [ ] relevant documentation is changed or added
- [ ] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes:

2021-04-30 07:55 UTC, codebytere requested changes
Thanks! Looks like lint is failing:

```
File Location: /home/builduser/project/src/electron/docs/api/webview-tag.md
	Broken links: browser-view
Parsed through 204 files within docs directory and its 69 subdirectories.
Found 1 broken relative links.
```

2021-05-02 20:51 UTC, hamstu commented
Thanks @codebytere! I think I missed the right link format. Pushed a fix.

2021-05-04 08:41 UTC, codebytere approved these changes
Thanks @hamstu! looks good ✨

2021-05-05 07:12 UTC, zcbenz approved these changes

2021-05-05 07:12 UTC, merged