fix: don't warn about enableRemoteModule when it's undefined
electron/electron pull request #29023
Opened 2021-05-05 18:32 UTC by nornagon

#### Description of Change
Fixes #29020.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [ ] relevant documentation is changed or added
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: Fixed an incorrect warning about enableRemoteModule being issued when the option was undefined (and thus defaulting to false).

2021-05-05 18:33 UTC, codebytere approved these changes

2021-05-05 18:38 UTC, MarshallOfSound approved these changes

2021-05-06 11:26 UTC, zcbenz requested changes
Tests are failing:

```
2 tests failed
  out of 1723
security warnings without sandbox should warn about enabled remote module with remote content
security warnings with sandbox should warn about enabled remote module with remote content
```

2021-05-07 07:17 UTC, codebytere requested changes
@nornagon this should target master unless i'm mistaken?

2021-05-08 04:17 UTC, miniak commented
@codebytere the remote module is gone in master

2021-05-13 02:00 UTC, zcbenz approved these changes

2021-05-13 08:46 UTC, codebytere approved these changes

2021-05-13 08:46 UTC, merged

2021-06-15 13:24 UTC, miniak commented
/trop run backport-to 12-x-y