fix: <webview> focus / blur events don't work with contextIsolation enabled
electron/electron pull request #29026
Opened 2021-05-05 18:37 UTC by miniak

Backport of #29004

See that PR for details.

Notes: Fixed `<webview>` `focus` / `blur` events not working with `contextIsolation` enabled.

2021-05-06 11:24 UTC, zcbenz approved these changes

2021-05-06 11:24 UTC, zcbenz requested changes
Build is failing

```
[tsl] ERROR in /home/builduser/project/src/electron/lib/renderer/web-view/web-view-impl.ts(161,22)
      TS2531: Object is possibly 'null'.
```

2021-05-07 01:11 UTC, miniak commented
@zcbenz it's interesting that PRs targeting other branches didn't hit this issue. Fixed now

2021-05-07 02:15 UTC, zcbenz approved these changes

2021-05-07 02:15 UTC, merged