fix: fix aspect ratio when max width/height is set
electron/electron pull request #29101
Opened 2021-05-11 11:18 UTC by CezaryKulakowski

Add the native frame border size to the minimum and maximum size if
the view reports its size as the client size. It allows to enlarge
window to proper values when aspect ratio and max width/height are
set. It also fixes DCHECK which was triggered when user tried to
enlarge window above dimensions set during creation of the
BrowserWindow.

#### Description of Change

#### Checklist

- [ ] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [ ] relevant documentation is changed or added
- [ ] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: fixed respecting aspect ratio when maximum size is set on BrowserWindow

2021-05-20 06:54 UTC, zcbenz approved these changes
I think the patch itself is good, can you also try to upstream this patch to Chromium?

This PR requires review from @electron/wg-upgrades.

2021-05-20 07:28 UTC, CezaryKulakowski commented
I'll try.

2021-09-01 07:48 UTC, AsmedianV approved these changes

2021-09-01 23:09 UTC, nornagon requested changes
Patch is pretty small and self-contained, but there are no tests. We periodically sweep our patch list and remove patches that don't cause tests to fail when deleted, so this would be liable to be removed without a test.

2021-09-30 09:19 UTC, CezaryKulakowski commented
@nornagon it would be hard (if possible) to create test for it as current testing environment does't allow to perform user initiated window resize (i.e. resize with mouse and window's edge). It would require browser test functionality and generating winapi events WM_SIZING.

2021-11-17 15:29 UTC, CezaryKulakowski commented
I was trying to get a repro on clean chromium to be able to upstream the fix to them. Unfortunately the only use case in chromium which uses this code (at least the only one I was able to find) is html5 video's pip: https://developer.mozilla.org/en-US/docs/Web/API/HTMLVideoElement/requestPictureInPicture. The problem is that this window is frameless so its content size is equal to its window size and check which I added is not needed for such case (it also wouldn't break anything but we won't be able to get a repro).

2021-11-17 16:18 UTC, CezaryKulakowski commented
I've just checked that I should be able to create spec test for it. I'll handle it tomorrow and I'all also rebase the changes to the newest main.

2021-11-18 16:51 UTC, CezaryKulakowski commented
I've pushed branch rebased to the newest main. I've also added a test.

2021-11-19 01:38 UTC, zcbenz commented
Test has been added and I think this PR should be ready to go, we still need approval from @electron/wg-upgrades.

2021-11-19 05:58 UTC, deepak1556 approved these changes
LGTM since it now addresses https://github.com/electron/electron/pull/29101#pullrequestreview-744479827

2021-11-22 09:31 UTC, merged