fix: ensure window transparency work when disabled allowRendererProcessReuse (#28475)
electron/electron pull request #29163
Opened 2021-05-14 02:36 UTC by yaohy0819

#### Description of Change

copy master latest code to fix this issue on 11-x-y

#### Checklist

- [ ] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [ ] relevant documentation is changed or added
- [ ] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes:

2021-05-15 01:35 UTC, MarshallOfSound requested changes
I do not believe simply copying this code will fix the problem, the child window logic in Electron 12 is substantially different to Electron 11 and the fix I landed for E12 relied on all the new logic we also added in E12.

Have you tested this?

2021-05-17 07:51 UTC, yaohy0819 commented
> I do not believe simply copying this code will fix the problem, the child window logic in Electron 12 is substantially different to Electron 11 and the fix I landed for E12 relied on all the new logic we also added in E12.
> 
> Have you tested this?

Thank you for your reply.

Yes, my test have passed.
This bug is because WebContents::RenderViewCreated couldn't get RenderWidgetHostView when disabled allowRendererProcessReuse, that cause electron lost the SetBackgroundColor . So I move SetBackgroundColor to WebContents::RenderFrameCreated ensure we can got RenderWidgetHostView.

PS. when disabled allowRendererProcessReuse,  electron will create the second RenderWidgetHostImpl, and we expect to use the second RenderWidgetHostImpl's RenderWidgetHostView to SetBackgroundColor. but WebContents::RenderViewCreated only could get the first RenderWidgetHostView, 

the second RenderWidgetHostImpl create stacks:
```
electron.exe!content::RenderWidgetHostImpl::RenderWidgetHostImpl(delegate, agent_scheduling_group, routing_id, hidden, frame_token_message_queue) Line 358	C++
electron.exe!std::__1::make_unique<...>(__args, __args, __args, __args, __args) Line 3043	C++
electron.exe!content::RenderWidgetHostFactory::Create(delegate, agent_scheduling_group, routing_id, hidden) Line 25	C++
electron.exe!content::RenderViewHostFactory::Create(instance, delegate, widget_delegate, main_frame_routing_id, swapped_out) Line 39	C++
electron.exe!content::FrameTree::CreateRenderViewHost(site_instance, main_frame_routing_id, swapped_out) Line 392	C++
electron.exe!content::RenderFrameHostManager::CreateRenderFrameHost(create_frame_case, site_instance, frame_routing_id, frame_token, renderer_initiated_creation) Line 2267	C++
electron.exe!content::RenderFrameHostManager::CreateSpeculativeRenderFrame(instance) Line 2354	C++
electron.exe!content::RenderFrameHostManager::CreateSpeculativeRenderFrameHost(old_instance, new_instance) Line 2313	C++
electron.exe!content::RenderFrameHostManager::GetFrameHostForNavigation(request) Line 837	C++
electron.exe!content::RenderFrameHostManager::DidCreateNavigationRequest(request) Line 702	C++
electron.exe!content::FrameTreeNode::CreatedNavigationRequest(navigation_request) Line 510	C++
electron.exe!content::Navigator::Navigate(request, reload_type, restore_type) Line 507	C++
electron.exe!content::NavigationControllerImpl::NavigateWithoutEntry(params) Line 3098	C++
electron.exe!content::NavigationControllerImpl::LoadURLWithParams(params) Line 998	C++
electron.exe!electron::api::WebContents::LoadURL(url, options) Line 1748	C++
[Inline Frame] electron.exe!base::internal::FunctorTraits<...>::Invoke(method, receiver_ptr, args, args) Line 498	C++
```

2021-05-19 01:30 UTC, zcbenz approved these changes
Thanks for explaining, I'm good with backporting this code.

2021-05-24 02:30 UTC, zcbenz commented
@MarshallOfSound Can you take another look at this?

2021-06-07 01:39 UTC, zcbenz commented
I'm closing this PR since 11.x now only receive security fixes.

2021-06-07 01:39 UTC, closed without merging