build: remove individual release build workflows
electron/electron pull request #29344
Opened 2021-05-26 18:07 UTC by MarshallOfSound

Continuing circle simplification, this removes our "single job" publish workflows for linux and macOS and replaces them with the primary publish workflow but ensures that the other jobs have no steps if they aren't the selected arch.  This doesn't impact the normal sudowoodo flow, just ad-hoc release builds triggered by `ci-release-builds.js`

Notes: no-notes

2021-05-27 15:42 UTC, jkleinsc requested changes
I tested kicking off jobs from ci-release-build and got a build error trying to just run one job.

I ran:
`node script/release/ci-release-build.js --ci=CircleCI --job=macos-publish --arch=osx-x64 remove-single-publish`

The result:
https://app.circleci.com/pipelines/github/electron/electron/40206/workflows/6e2acc66-1b1d-431c-96d9-5fe427f9e04f/jobs/888725

2021-05-27 17:52 UTC, MarshallOfSound commented
Huh, I tested this in isolation but I guess my test case had a dummy step "echo 0" just to test the if condition.  I guess you need a job with at least one step 😆

2021-05-27 17:56 UTC, MarshallOfSound commented
@jkleinsc Ran your exact script to start this publish-macos job with the latest fix --> https://app.circleci.com/pipelines/github/electron/electron/40209/workflows/0e219ab5-64d9-4ca6-bb1b-759c45023d71

2021-06-07 14:04 UTC, jkleinsc approved these changes
it is annoying that we need a dummy step but I guess its ok as is.

2021-06-07 14:17 UTC, merged