fix: increase stack size on windows x86
electron/electron pull request #29474
Opened 2021-06-02 06:47 UTC by stephen9357

#### Description of Change
Increase stack size to 1MiB on Windows x86, to fix V8 stack overflow (#28487 ).
@deepak1556 increased stack size on Windows x64 to 8MiB, but only 0.5MiB on Windows x86. It's not enough for V8.

callstack while stack overflow.
```
0:000:x86> kbL
 # ChildEBP RetAddr  Args to Child              
00 000ce034 0223dee3 000ce040 03a05afc 95de35b8 electron!v8::internal::Isolate::StackOverflow
01 000ce050 01f77440 00495bd8 0add5360 03a05afc electron!v8::internal::PendingCompilationErrorHandler::ReportErrors+0x33
02 000ce074 01f74ce5 000ce1a8 000ce150 000ce288 electron!v8::internal::`anonymous namespace'::FailWithPreparedPendingException+0x40
03 (Inline) -------- -------- -------- -------- electron!v8::internal::`anonymous namespace'::FailWithPendingException+0x2a
04 000ce128 01f75dcd 0add5360 00000000 00495bd8 electron!v8::internal::`anonymous namespace'::CompileToplevel+0x375
05 (Inline) -------- -------- -------- -------- electron!v8::internal::`anonymous namespace'::CompileToplevel+0x1a
06 000ce1fc 01f758d6 021e0041 00000003 00000200 electron!v8::internal::`anonymous namespace'::CompileScriptOnMainThread+0xed
07 000ce2f0 020d1707 000ce358 00495bd8 0add5354 electron!v8::internal::Compiler::GetSharedFunctionInfoForScript+0x596
08 000ce36c 020d44aa 00495bd8 0ad71038 0add5354 electron!v8::internal::Genesis::CompileExtension+0x1f7
09 000ce3b0 020d4053 00495bd8 004922b0 000ce3c4 electron!v8::internal::Genesis::InstallExtension+0xda
0a (Inline) -------- -------- -------- -------- electron!v8::internal::Genesis::InstallExtension+0x3b
0b (Inline) -------- -------- -------- -------- electron!v8::internal::Genesis::InstallRequestedExtensions+0x43
0c 000ce3e4 020bd8f7 00495bd8 00495bd8 000ce678 electron!v8::internal::Genesis::InstallExtensions+0x113
0d (Inline) -------- -------- -------- -------- electron!v8::internal::Bootstrapper::InstallExtensions+0x2d
0e 000ce440 01edbc8e 000ce4cc 00000000 00000000 electron!v8::internal::Bootstrapper::CreateEnvironment+0x87
0f (Inline) -------- -------- -------- -------- electron!v8::InvokeBootstrapper<v8::internal::Context>::Invoke+0x1d
10 (Inline) -------- -------- -------- -------- electron!v8::CreateEnvironment+0x5d
11 000ce4e8 01edc82e 000ce554 00495bd8 000ce678 electron!v8::NewContext+0x12e
12 000ce520 05ef7a21 000ce554 00495bd8 00000000 electron!v8::Context::FromSnapshot+0x4e
13 000ce60c 0427bfe3 000ce680 00495bd8 42054da0 electron!blink::V8ContextSnapshotImpl::CreateContext+0x121
14 000ce630 04f789dc 000ce680 00495bd8 42054da0 electron!blink::V8ContextSnapshot::CreateContextFromSnapshot+0x23
15 000ce748 04f783e6 06fb24b8 06fb2498 000002db electron!blink::LocalWindowProxy::CreateContext+0xcc
16 000ce804 043a9268 00000000 000ce838 0426c16a electron!blink::LocalWindowProxy::Initialize+0x86
17 (Inline) -------- -------- -------- -------- electron!blink::WindowProxyManager::GetWindowProxy+0x11
18 000ce810 0426c16a 42054da0 00495bd8 00000000 electron!blink::Frame::GetWindowProxy+0x18
19 (Inline) -------- -------- -------- -------- electron!blink::ToV8ContextEvenIfDetached+0x15
1a (Inline) -------- -------- -------- -------- electron!blink::ToScriptStateImpl+0x15
1b (Inline) -------- -------- -------- -------- electron!blink::ToScriptState+0x27
1c 000ce838 03a26dff 2bf81f00 000ce854 000ce874 electron!blink::ToScriptStateForMainWorld+0x4a
1d 000ce848 0343bf46 000ce854 00000038 00495bd8 electron!blink::WebLocalFrameImpl::MainWorldScriptContext+0xf
1e 000ce874 034201e1 0adb1e68 0adf7598 000ce8e4 electron!extensions::ScriptContextSet::GetMainWorldContextForFrame+0x46
1f (Inline) -------- -------- -------- -------- electron!extensions::`anonymous namespace'::GetExtensionFromFrame+0x6
20 000ce884 03b53dfd 00000001 00000000 00000000 electron!extensions::ExtensionFrameHelper::DidCommitProvisionalLoad+0x11
21 000ce8e4 03b5380d 00000001 00000000 00000000 electron!content::RenderFrameImpl::NotifyObserversOfNavigationCommit+0x14d
22 000cea50 04467d6c 000cea64 00000000 00000001 electron!content::RenderFrameImpl::DidCommitNavigation+0xd0d
23 000cea7c 0448f3a4 55823c18 00000000 00000001 electron!blink::LocalFrameClientImpl::DispatchDidCommitLoad+0x4c
24 000cebc4 04421501 000cebf0 00000005 2bf82060 electron!blink::DocumentLoader::CommitNavigation+0x3e4
25 000cebd8 044235ec 2bf89a18 000cec10 00000000 electron!blink::FrameLoader::CommitDocumentLoader+0x81
26 000cecdc 03a2ba3e 00000000 00000000 00000003 electron!blink::FrameLoader::CommitNavigation+0x3fc
27 000ced04 03b4dbdd 00000000 00000000 000ced00 electron!blink::WebLocalFrameImpl::CommitNavigation+0x4e
28 000ceda4 03b648d1 0ae16820 0ae165a0 00000000 electron!content::RenderFrameImpl::CommitNavigationWithParams+0x3ed
29 000cedfc 03b647e0 03b4d7f0 00000000 0ad713b8 electron!base::internal::FunctorTraits<void (content::RenderFrameImpl::*)(mojo::StructPtr<content::mojom::CommonNavigationParams>, mojo::StructPtr<content::mojom::CommitNavigationParams>, std::__1::unique_ptr<blink::PendingURLLoaderFactoryBundle,std::__1::default_delete<blink::PendingURLLoaderFactoryBundle> >, base::Optional<std::__1::vector<mojo::StructPtr<blink::mojom::TransferrableURLLoader>,std::__1::allocator<mojo::StructPtr<blink::mojom::TransferrableURLLoader> > > >, mojo::StructPtr<blink::mojom::ControllerServiceWorkerInfo>, mojo::StructPtr<blink::mojom::ServiceWorkerContainerInfoForClient>, mojo::PendingRemote<network::mojom::URLLoaderFactory>, std::__1::unique_ptr<content::DocumentState,std::__1::default_delete<content::DocumentState> >, std::__1::unique_ptr<blink::WebNavigationParams,std::__1::default_delete<blink::WebNavigationParams> >) __attribute__((thiscall)),void>::Invoke<void (content::RenderFrameImpl::*)(mojo::StructPtr<content::mojom::CommonNavigationParams>, mojo::StructPtr<content::mojom::CommitNavigationParams>, std::__1::unique_ptr<blink::PendingURLLoaderFactoryBundle,std::__1::default_delete<blink::PendingURLLoaderFactoryBundle> >, base::Optional<std::__1::vector<mojo::StructPtr<blink::mojom::TransferrableURLLoader>,std::__1::allocator<mojo::StructPtr<blink::mojom::TransferrableURLLoader> > > >, mojo::StructPtr<blink::mojom::ControllerServiceWorkerInfo>, mojo::StructPtr<blink::mojom::ServiceWorkerContainerInfoForClient>, mojo::PendingRemote<network::mojom::URLLoaderFactory>, std::__1::unique_ptr<content::DocumentState,std::__1::default_delete<content::DocumentState> >, std::__1::unique_ptr<blink::WebNavigationParams,std::__1::default_delete<blink::WebNavigationParams> >) __attribute__((thiscall)),base::WeakPtr<content::RenderFrameImpl>,mojo::StructPtr<content::mojom::CommonNavigationParams>,mojo::StructPtr<content::mojom::CommitNavigationParams>,std::__1::unique_ptr<blink::PendingURLLoaderFactoryBundle,std::__1::default_delete<blink::PendingURLLoade+0xd1
2a (Inline) -------- -------- -------- -------- electron!base::internal::InvokeHelper<1,void>::MakeItSo+0x87
2b (Inline) -------- -------- -------- -------- electron!base::internal::Invoker<base::internal::BindState<void (content::RenderFrameImpl::*)(mojo::StructPtr<content::mojom::CommonNavigationParams>, mojo::StructPtr<content::mojom::CommitNavigationParams>, std::__1::unique_ptr<blink::PendingURLLoaderFactoryBundle,std::__1::default_delete<blink::PendingURLLoaderFactoryBundle> >, base::Optional<std::__1::vector<mojo::StructPtr<blink::mojom::TransferrableURLLoader>,std::__1::allocator<mojo::StructPtr<blink::mojom::TransferrableURLLoader> > > >, mojo::StructPtr<blink::mojom::ControllerServiceWorkerInfo>, mojo::StructPtr<blink::mojom::ServiceWorkerContainerInfoForClient>, mojo::PendingRemote<network::mojom::URLLoaderFactory>, std::__1::unique_ptr<content::DocumentState,std::__1::default_delete<content::DocumentState> >, std::__1::unique_ptr<blink::WebNavigationParams,std::__1::default_delete<blink::WebNavigationParams> >) __attribute__((thiscall)),base::WeakPtr<content::RenderFrameImpl>,mojo::StructPtr<content::mojom::CommonNavigationParams>,mojo::StructPtr<content::mojom::CommitNavigationParams>,std::__1::unique_ptr<blink::Pendin [...]

2021-06-02 07:30 UTC, deepak1556 commented
@stephen9357 thanks for opening this PR, I would like to align the stack setup similar to chrome. Please refer to https://github.com/electron/electron/issues/29177#issuecomment-848559718.  Basically we need to increase the main thread stack via fibers during runtime.

2021-06-06 10:16 UTC, StaZhu commented
I have tried remove "ldflags += ["/stack:0x80000"]" which introduced in 11.2.1 for x86 arch cpu, and rebuild the electron. then crash on ia32 windows has been completed solved!  just for reference, seems the stack size from 1.5MiB to 0.5MiB causes the issue.

2021-06-08 04:02 UTC, deepak1556 commented
@stephen9357 are you looking to make progress on this PR by adjusting the stack size during runtime or would you like me to take over ? Thanks!

2021-06-10 08:32 UTC, stephen9357 commented
@deepak1556 Sorry for my late reply. 
Yes, Chrome's fiber change works. I have committed the code just like chrome do, please review my change. Thanks.

2021-06-11 15:28 UTC, deepak1556 commented
Change looks good, restarted win-32 ci to confirm flaky tests.

2021-06-15 18:57 UTC, nornagon approved these changes

2021-06-15 20:11 UTC, jkleinsc requested changes
Windows 32 failures don't seem to be flakes:
https://ci.appveyor.com/project/electron-bot/electron-92tg5/builds/39613530

2021-06-28 01:35 UTC, bruceauyeung commented
@stephen9357 before this PR being merged, is there any workround to get things work? such as increasing stack size manually ? how ?

2021-06-29 03:48 UTC, stephen9357 commented
> @stephen9357 before this PR being merged, is there any workround to get things work? such as increasing stack size manually ? how ?

We need to increase main thread's stack size, it's created by OS, according to SizeOfStackReserve in PE optional header, we can not change it manually.
We can only change stack size since second thread, which is created by CreateThread  API and the second parameter is stack size of new thread.

2021-07-05 15:05 UTC, weifeiyue commented
We have the same problem. When will the version be released ?

2021-07-13 11:41 UTC, y489436672 commented
I want to know when it can be repaired? thank you all.

2021-07-15 06:35 UTC, stephen9357 commented
> I want to know when it can be repaired? thank you all.

@y489436672 I'm working on it.
@jkleinsc  `npm run test` failed on my Windows 10 PC, it looks like some symbols are missing, can you help? Thanks.

```
D:\workspace\electron-offical\src\electron>npm run test

> electron@15.0.0-nightly.20210531 test
> node ./script/spec-runner.js

Triggering runners: main, remote, native
OUT_DIR is: Release-x86
yarn install v1.22.10
warning package.json: No license field
warning electron-test@0.1.0: No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
info abstract-socket@2.1.0: The platform "win32" is incompatible with this module.
info "abstract-socket@2.1.0" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
error D:\workspace\electron-offical\src\electron\spec\node_modules\is-valid-window: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: D:\workspace\electron-offical\src\electron\spec\node_modules\is-valid-window
Output:
D:\workspace\electron-offical\src\electron\spec\node_modules\is-valid-window>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\Admin\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@12.18.4 | win32 | x64
gyp info find Python using Python version 2.7.18 found at "C:\Python27\python.exe"
gyp info find VS using VS2019 (16.10.31410.357) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Python27\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\Users\\Admin\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\workspace\\electron-offical\\src\\electron\\spec\\node_modules\\is-valid-window\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Admin\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\workspace\\electron-offical\\src\\out\\Release-x86\\gen\\node_headers\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=D:\\workspace\\electron-offical\\src\\out\\Release-x86\\gen\\node_headers',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\Admin\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=D:\\\\workspace\\\\electron-offical\\\\src\\\\out\\\\Release-x86\\\\gen\\\\node_headers\\\\$(Configuration)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=D:\\workspace\\electron-offical\\src\\electron\\spec\\node_modules\\is-valid-window',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'D:\\workspace\\electron-offical\\src\\electron\\spec\\node_modules\\is-valid-window\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]
�ڴ˽��������һ������һ����Ŀ����Ҫ���ò������ɣ������ӡ�-m�����ء�
  main.cc
D:\workspace\electron-offical\src\out\Release-x86\gen\node_headers\include\node\node_api.h(7,1): warning C4005: ��NAPI_EXTERN��: ���ض��� [D:\workspace\electron-offical\src\electron\spec\node_modules\is-valid-window\build\is_valid_window.vcxproj]
D:\workspace\electron-offical\src\out\Release-x86\gen\node_headers\include\node\js_native_api.h(30): message : �μ���NAPI_EXTERN����ǰһ������ [D:\workspace\electron-offical\src\electron\spec\node_modules\is-valid-window\build\is_valid_window.vcxproj]
  impl_win.cc
  win_delay_load_hook.cc
    ���ڴ����� D:\workspace\electron-offical\src\electron\spec\node_modules\is-valid-window\build\Release\is_valid_window.lib �Ͷ��� D:\workspace\electron-offical\src\electron\spec\node_modules\is-valid-window\build\Release\is_valid_window.exp
main.obj : error LNK2001: �޷��������ⲿ���� napi_get_boolean [D:\workspace\electron-offical\src\electron\spec\node_modules\is-valid-window\build\is_valid_window.vcxproj]
main.obj : error LNK2001: �޷��������ⲿ���� __imp_napi_is_buffer [D:\workspace\electron-offical\src\electron\spec\node_modules\is-valid-window\build\is_valid_window.vcxproj]
main.obj : error LNK2001: �޷��������ⲿ���� napi_throw_error [D:\workspace\electron-offical\src\electron\spec\node_modules\is-valid-window\build\is_valid_window.vcxproj]
main.obj : error LNK2001: �޷��������ⲿ���� __imp_napi_get_buffer_info [D:\workspace\electron-offical\src\electron\spec\node_modules\is-valid-window\build\is_valid_window.vcxproj]
main.obj : error LNK2001: �޷��������ⲿ���� __imp_napi_module_register [D:\workspace\electron-offical\src\electron\spec\node_modules\is-valid-window\build\is_valid_window.vcxproj]
main.obj : error LNK2001: �޷��������ⲿ���� napi_define_properties [D:\workspace\electron-offical\src\electron\spec\node_modules\is-valid-window\build\is_valid_window.vcxproj]
main.obj : error LNK2001: �޷��������ⲿ���� napi_get_cb_info [D:\workspace\electron-offical\src\electron\spec\node_modules\is-valid-window\build\is_valid_window.vcxproj]
D:\workspace\electron-offical\src\electron\spec\node_modules\is-valid-window\build\Release\is_valid_window.node : fatal error LNK1120: 7 ���޷��������ⲿ���� [D:\workspace\electron-offical\src\electron\spec\node_modules\is-valid-window\build\is_valid_window.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Admin\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Windows_NT 10.0.19041
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Admin\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\workspace\electron-offical\src\electron\spec\node_modules\is-valid-window
gyp ERR! node -v v12.18.4
gyp ERR! node-gyp -v v7.1.2
gyp ERR! not ok
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
✗ Failed to yarn install in 'D:\workspace\electron-offical\src\electron\spec'

2021-07-15 06:48 UTC, deepak1556 commented
@stephen9357 please perform the following steps to fix native module compilation,

```
* cd out/Release-x86/gen/node_headers
* mkdir Release
* cp out/Release-x86/electron.lib out/Release-x86/gen/node_headers/Release/node.lib

npm run test // will be able to find symbols to link for the native modules
```

2021-07-16 13:12 UTC, weifeiyue commented
when can it be fixed? This bug has affected the progress of my project 😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭

2021-07-18 15:59 UTC, stephen9357 commented
@deepak1556 Thanks for you help. Only AMD64 can be tested,  these function names exported by the x86 version of node.lib are different.
```
E:\Github\electron\src\out>dumpbin.exe /exports Testing-x64\gen\node_headers\Release\node.lib | findstr "napi_get_boolean"
                  napi_get_boolean

E:\Github\electron\src\out>dumpbin.exe /exports Testing-x86\gen\node_headers\Release\node.lib | findstr "napi_get_boolean"
                  _napi_get_boolean

```
I compiled is-valid-window.node under AMD64, and then ran the x86 test case. The mainline code also failed. Maybe other changes failed the test case?

```
E:\Github\electron\src\electron>npm run test -- -g "quit-on-crashed-event"

> electron@15.0.0-nightly.20210716 test E:\Github\electron\src\electron
> node ./script/spec-runner.js "-g" "quit-on-crashed-event"

Triggering runners: main, remote, native

Running: Main process specs

1..1
not ok 1 crash cases the "quit-on-crashed-event" case should not crash
  Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (E:\Github\electron\src\electron\spec-main\crash-spec.ts)
      at listOnTimeout (node:internal/timers:557:17)
      at processTimers (node:internal/timers:500:7)
not ok 2 crash cases "after each" hook for "the "quit-on-crashed-event" case should not crash"
  AssertionError: all child processes should have exited cleanly: expected [ { _events: { exit: [Function] },

...

[13272:0718/234935.510:ERROR:desktop_native_widget_aura.cc(753)] Not implemented reached in virtual const gfx::ImageSkia *views::DesktopNativeWidgetAura::GetWindowIcon()
[13272:0718/234935.510:ERROR:desktop_native_widget_aura.cc(758)] Not implemented reached in virtual const gfx::ImageSkia *views::DesktopNativeWidgetAura::GetWindowAppIcon()

Unhandled exception in main spec runner: AssertionError: exit signal should be null: expected 'SIGTERM' to equal null
    at ChildProcess.<anonymous> (E:\Github\electron\src\electron\spec-main\crash-spec.ts:25:25)
    at ChildProcess.emit (node:events:394:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12) {
  showDiff: true,
  actual: 'SIGTERM',
  expected: null
}
✗ Electron tests failed with code 0x1.
```

2021-07-19 15:57 UTC, deepak1556 commented
Thanks for testing @stephen9357 , I will take a look at this today.

2021-07-20 07:40 UTC, deepak1556 commented
@stephen9357 I would like to push changes to this PR, can you follow https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork to provide the permission. Thanks!

2021-07-20 09:07 UTC, stephen9357 commented
@deepak1556 Ok, "Allow edits by maintainers" checked.

2021-07-22 02:53 UTC, deepak1556 commented
Okay looks like the null pointer crash implementation for `process.crash` was not actually causing a crash in CI with the fiber switch, maybe because of its undefined behavior https://blog.aaronballman.com/2011/08/crashing-easy-to-do-when-you-dont-want-to-hard-when-you-do/. I cannot repro the issue locally, to unblock this PR I have switched the test case to use a reliable crash code.

2021-07-22 15:21 UTC, jkleinsc approved these changes

2021-07-22 19:49 UTC, deepak1556 commented
Failing tests are unrelated, merging.

2021-07-22 19:49 UTC, merged