test: add spec for --require filtering in NODE_OPTIONS
electron/electron pull request #29505
Opened 2021-06-02 20:44 UTC by miniak

Backport of #29501

Notes: no-notes

2021-06-02 21:36 UTC, MarshallOfSound approved these changes

2021-06-03 05:45 UTC, zcbenz requested changes
Should be merged after rebased on https://github.com/electron/electron/pull/29419.

2021-06-03 14:40 UTC, miniak commented
@zcbenz the backport to 11-x-y should have been merged after the fix. This one for master can be merged.

2021-06-03 15:39 UTC, miniak commented
@zcbenz #29501 is now merged

2021-06-03 23:14 UTC, zcbenz approved these changes

2021-06-03 23:14 UTC, merged