docs: fix image links in `performance.md`
electron/electron pull request #29592
Opened 2021-06-08 15:53 UTC by RaisinTen

#### Description of Change

Fixes https://github.com/electron/electron/issues/29580

Signed-off-by: Darshan Sen <raisinten@gmail.com>

#### Checklist

- [ ] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [x] relevant documentation is changed or added
- [ ] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: none

2021-06-09 04:09 UTC, dsanders11 requested changes
@RaisinTen, nice catch. I've gone ahead and made some suggested changes. The URLs are already at the bottom of the doc as [reference-style links](https://www.markdownguide.org/basic-syntax/#reference-style-links), it was just the usage of the links for the images which had the wrong syntax.

2021-06-09 04:09 UTC, dsanders11 commented on docs/tutorial/performance.md
> +![Performance CPU Profile](../images/performance-cpu-prof.png)
```suggestion
![Performance CPU Profile][performance-cpu-prof]
```

2021-06-09 04:09 UTC, dsanders11 commented on docs/tutorial/performance.md
> +![Performance Heap Memory Profile](../images/performance-heap-prof.png)
```suggestion
![Performance Heap Memory Profile][performance-heap-prof]
```

2021-06-09 06:44 UTC, mariasandra6 approved these changes

2021-06-09 14:21 UTC, RaisinTen commented
@dsanders11 Thanks for the suggestion. Updated, PTAL. :)

2021-06-10 01:39 UTC, dsanders11 approved these changes

2021-06-10 12:28 UTC, codebytere approved these changes

2021-06-10 17:44 UTC, merged