fix: ensure cursor styles are correct in top 22px of the frameless window on macOS
electron/electron pull request #29622
Opened 2021-06-10 06:10 UTC by MarshallOfSound

I swear I try the same thing every 6 months or so expecting it to magically work.  This time, it did??? I think this works now as a result of @zcbenz 's refactor of how hidden and hiddenInset styles work.

Gonna give this a wider sweep of manual testing tomorrow 🤷 

Notes: Fixed cursor style issues in top 22 pixels of frameless windows on macOS

2021-06-10 08:24 UTC, codebytere approved these changes

2021-06-10 08:33 UTC, zcbenz reviewed
`NSBorderlessWindowMask` has some unfortunate side effects, for example window does not have rounded corners, no window shadow. And this style has already been deprecated in macOS so we should not use it.

Can you give more details about the problem you want to solve? There might be another solution to it.

2021-06-10 20:23 UTC, MarshallOfSound commented
@zcbenz https://github.com/electron/electron/issues/5723 specifically

2021-06-14 01:38 UTC, zcbenz commented
It can be fixed by applying `NSWindowStyleMaskFullSizeContentView` to the window, which however has a side effect of removing the rounded corners of the window, you can try with the `roundedCorners: false` option.

I'll see if it is possible to keep the rounded corners with `NSWindowStyleMaskFullSizeContentView`.

2021-06-14 07:37 UTC, zcbenz requested changes
After a few more investigation on the original issue, I found that the key to solve it, is to remove the `NSWindowStyleMaskTitled` style, which removes the titlebar completely. Neither `NSBorderlessWindowMask` nor `NSWindowStyleMaskFullSizeContentView` style is really related.

However removing the `NSWindowStyleMaskTitled` style has a a few severe side effects:
1. the window's corners are not rounded;
2. the window can not be closed in normal ways;
3. the window can not enter fullscreen.

While the 1) and 2) can somehow be workarounded, I can't find any way to solve the last one.

So anyway using `NSBorderlessWindowMask` style is not good way to solve the problem..

2021-06-16 17:29 UTC, closed without merging