chore: set python interpreter to python3 in script/spec-runner.js
electron/electron pull request #29740
Opened 2021-06-16 20:20 UTC by 1bitphoenix

The new installs of python module, python-dbusmock, is broken for python2. The tests still run fine on linux machine in Electron's pipeline setup on CircleCI, because the docker image used has the non-broken version of python-dbusmock for python2 installed. But running electron tests on any other linux machine would fail if they don't have this non-broken version of python-dbusmock for python2 installed, already, which is the case for most of the machines.
Moreover, Python2 is deprecated now. So it would be better if we change the python interpreter in script/spec-runner.js file to python3, for which all the python modules are updated and working.

Notes: none

2021-06-16 23:26 UTC, nornagon approved these changes
seems reasonable!

2021-06-17 06:49 UTC, MarshallOfSound requested changes
CI is failing with spec-runner related python dependency issues.  You may have to update our build-images we use on CI:

https://github.com/electron/build-images

2021-06-17 12:37 UTC, 1bitphoenix commented
@MarshallOfSound Can you point me to the repo/project/procedure through which I can update the build-mage?

2021-06-17 16:13 UTC, ckerr commented
If this can get to green, it would solve a recurring annoyance when working with Electron on Linux -- currently building & most work with depot-tools needs to be python2, but tests need to use python3 for python-dbusmock, just as @1bitphoenix says. :+1: on this approach

2021-06-22 11:12 UTC, 1bitphoenix commented
@MarshallOfSound 
Raised PR to update electron image - [link](https://github.com/electron/build-images/pull/9)

2021-06-29 05:51 UTC, 1bitphoenix commented
I have updated the PR. All the linux tests have passed. 2 of the macOS builds failed due to build timeout.
Pushing amended commit to restart builds.

2021-06-29 21:57 UTC, nornagon approved these changes

2021-06-29 22:37 UTC, MarshallOfSound approved these changes

2021-06-29 22:46 UTC, merged