fix: properly order out child windows
electron/electron pull request #29821
Opened 2021-06-21 14:30 UTC by codebytere

#### Description of Change

Closes https://github.com/electron/electron/issues/29820. Properly orders out child windows when `window.hide()` is called on a parent window. This should not change any end user behavior, but Chromium specifically DCHECKs for it so we should handle it properly.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: none.

2021-06-21 17:00 UTC, nornagon approved these changes

2021-06-21 18:29 UTC, MarshallOfSound requested changes
Hm if I'm reading this right this is an annoying behavior change, where you can't open a child window and have it remain visible while hiding the parent.  (E.g. Think about a certain app that has a calls window it opens as a child and then hides the parent).

Not sure what the correct solution is here but this will definitely affect existing apps

2021-06-21 20:27 UTC, codebytere commented
@MarshallOfSound I thought so too, but this behavior is the same for end users at present - if you add for example

```
const child = new BrowserWindow({
    width: 200,
    height: 200,
    webPreferences: {
      preload: path.join(__dirname, 'preload.js')
    },
    parent: mainWindow
  })

  child.show()
  setTimeout(() => {
    mainWindow.hide()
  }, 5000)
  ```
  
to the default fiddle and run with e.g. `12.0.10` you'll see that when the `setTimeout` callback executes, both windows are hidden.

2021-06-22 06:20 UTC, zcbenz approved these changes
I'm 👍  with this since it is fixing a DCHECK in Chromium.

2021-06-24 16:18 UTC, MarshallOfSound approved these changes

2021-06-24 18:43 UTC, codebytere commented
Crash report failure is not relevant.

2021-06-24 18:43 UTC, merged