fix: type internal APIs that can return null properly
electron/electron pull request #29852
Opened 2021-06-22 20:53 UTC by miniak

#### Description of Change
The following APIs can return `null`:
https://github.com/electron/electron/blob/b8261f15916eb94428d5672716f85c56720b1501/shell/browser/api/electron_api_web_contents.cc#L3043-L3065

#### Checklist
- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes

#### Release Notes
Notes: none

2021-06-22 21:57 UTC, nornagon requested changes
This isn't very useful if we always access these with `!`, should we be null-checking in these cases instead?

2021-07-26 18:10 UTC, MarshallOfSound commented
> This isn't very useful if we always access these with !, should we be null-checking in these cases instead?

I think it's still useful for _new_ code, and this existing code is valid because we do know better than the compiler in most of these code paths that these values are definitely non-null 🤷

2021-07-26 21:59 UTC, nornagon approved these changes

2021-07-27 00:24 UTC, zcbenz approved these changes

2021-07-27 05:48 UTC, merged