fix: BrowserViews not painting their WebContents
electron/electron pull request #29919
Opened 2021-06-28 17:08 UTC by codebytere

#### Description of Change

Closes https://github.com/electron/electron/issues/29859.

Fixes an issue where `BrowserView`s would appear not to load their `webContents`. Further investigation showed that it was in fact not that the `webContents` weren't being loaded, but that they weren't being _painted_ properly. If I tried to open `devTools` on the webContents or called `setBounds` _after_ the initial URL load it would work - this tracked back to `Layout` in `inspectable_web_contents_view_views.h` and to a hierarchy change in https://chromium-review.googlesource.com/c/chromium/src/+/2780032. Essentially, the change meant that `Layout` was no longer called by Chromium in some of the places it was before.

To fix this, I added call to `DidFinishNavigation` and called into `Layout()` so that paints would happen properly again when they were supposed to.

To verify:

```js
const { BrowserView, BrowserWindow, app } = require('electron')

app.whenReady().then(async () => {
  let win = new BrowserWindow({ width: 800, height: 600 })
  win.on('closed', () => {
    win = null
  })
  const view = new BrowserView({
    webPreferences: {
      nodeIntegration: false
    }
  })
  win.setBrowserView(view)
  view.setBounds({ x: 0, y: 0, width: 800, height: 600 })
  await view.webContents.loadURL('https://electronjs.org')
})
```

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: Fixed an issue where `BrowserView` webContents would appear not to load in some circumstances.

2021-06-28 17:11 UTC, nornagon requested changes
I'm skeptical that `DidFinishNavigation` is the right place to hook into to call `Layout()` from. What lead you to that conclusion?

Should we be calling this instead when the view is added to the hierarchy?

2021-06-28 19:41 UTC, codebytere commented
@nornagon i was seeking something I could guarantee would be after the `webContents` finished loading - i also tried `RenderFrameCreated` to no success. What were you envisioning? Happy to try something else!

2021-07-28 12:29 UTC, zcbenz commented
https://github.com/electron/electron/issues/29607 also looks similar.

Can you check if the `contents_web_view_` in `InspectableWebContentsViewViews` has a proper size? My first instinct is that `contents_web_view_` somehow did not get sized after before loading URL.

2021-07-29 10:07 UTC, codebytere commented
@zcbenz looks like the bounds are correct in both cases, unfortunately.

2021-07-29 12:13 UTC, zcbenz commented
It seems that changing the size of `views::WebView` no longer changes the size of WebContents if RenderWidget is not ready, this behavior makes sense to me but I don't know why resizing used to work.

Calling `Layout()` in `DidFirstVisuallyNonEmptyPaint` or `RenderViewReady` should be able to work around the problem.

BrowserWindow has this code so it is probably why it does not suffer from this problem:
https://github.com/electron/electron/blob/385d0f590fe39f6e8ec87dafb2c8b22ae005901f/shell/browser/api/electron_api_browser_window.cc#L156-L165

Also note that the above code came from https://github.com/electron/electron/pull/6026, and since the implementation of `ready-to-show` event has changed we should probably remove it, or update its comments if it is still needed.

2021-07-29 17:47 UTC, codebytere commented
@zcbenz i thought so too, but calling it in `DidFirstVisuallyNonEmptyPaint` also does not work sadly

2021-07-29 17:54 UTC, codebytere commented
Using `RenderViewReady` works! Updated.

2021-07-29 18:36 UTC, nornagon commented on shell/browser/native_browser_view_views.cc
> +  auto* iwc_view = GetInspectableWebContentsView();
nit: say the type. It wasn't totally obvious to me that this returns an `InspectableWebContentsView*`, so I think this helps readability ein Bißchen

```suggestion
  InspectableWebContentsView* iwc_view = GetInspectableWebContentsView();
```

2021-07-29 20:35 UTC, MarshallOfSound approved these changes

2021-07-29 23:24 UTC, zcbenz approved these changes

2021-07-29 23:59 UTC, merged

2021-09-21 14:10 UTC, codebytere commented
/trop run backport-to 13-x-y

2022-06-23 07:25 UTC, TianbinTobin commented
```
win.setBrowserView(view)
await view.webContents.loadURL('https://electronjs.org')
view.setBounds({ x: 0, y: 0, width: 800, height: 600 })
```
I tried it better this way