chore: remove unused getWebPreferences method
electron/electron pull request #30160
Opened 2021-07-15 22:28 UTC by nornagon

#### Description of Change
The method is undocumented & unused.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)

#### Release Notes

Notes: none

2021-07-16 15:48 UTC, miniak approved these changes

2021-07-19 16:29 UTC, MarshallOfSound approved these changes

2021-07-19 16:29 UTC, merged

2021-07-19 16:30 UTC, MarshallOfSound requested changes
Is there an expected replacement for this API for those that are using it un-documented?  I know for instance we use `getLastWebPreferences()`

2021-07-19 16:32 UTC, nornagon commented
no, we don't support our undocumented APIs 🙃 

getLastWebPreferences exists but tbh i'd prefer it didn't.