feat: support vibrancy on Windows
electron/electron pull request #30298
Opened 2021-07-27 23:11 UTC by codebytere

#### Description of Change

Closes https://github.com/electron/electron/issues/16391.
Closes https://github.com/electron/electron/issues/29937.

Adds vibrancy support for BrowserWindows on Windows.

Screenshot:

<img width="823" alt="Screen Shot 2021-07-28 at 1 11 12 AM" src="https://user-images.githubusercontent.com/2036040/127239079-b51e45a2-223b-4837-92e8-8884e65e924c.png">

#### Checklist

- [x] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [x] relevant documentation is changed or added
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: Adds vibrancy support for BrowserWindows on Windows.

2021-07-28 17:32 UTC, riverar commented
I wrote those Acrylic hacks originally; they are not supported by Microsoft and introduce a number of problems. DO NOT merge this. This is a very bad idea.

2021-07-28 17:34 UTC, codebytere commented
@riverar is there a better supported API surface I should instead look towards?

2021-07-28 17:37 UTC, riverar commented
There is no documented (or undocumented) path to get Acrylic into a desktop app without introducing problems, sadly. (The undocumented path here _is_ (finally) fixed in Windows 11 builds but that's not helpful downstream and Microsoft refuses to service this.)

I think your best option is to adopt Mica (when those APIs come out) and we all just keep pressuring Microsoft for an official Acrylic path.

2021-07-28 18:27 UTC, chingucoding commented
@codebytere How does this PR address #29937? Mica and Acrylic are different things and work differently so adding acrylic does not cover Mica. Or does this close the feature request as in "there is an alternative"?

2021-07-28 19:22 UTC, MarshallOfSound commented
In agreement with @riverar we should avoid using undocumented / unsupported windows APIs here

2021-07-29 01:27 UTC, miniak commented on shell/browser/native_window_views.cc
> +        (pSetWindowCompositionAttribute)GetProcAddress(
use this pattern instead https://github.com/electron/electron/blob/c5ad7ed0cd05fe46aefedd0c3dbed580d6a5ce20/shell/browser/notifications/win/win32_desktop_notifications/common.h#L39-L42

2021-07-29 16:38 UTC, nornagon requested changes
marking request-changes to reflect conversation

2021-08-10 23:13 UTC, miniak commented
Is this going to be supported using public API on Windows 11 using [`DWMWA_USE_HOSTBACKDROPBRUSH`](https://docs.microsoft.com/en-us/windows/win32/api/dwmapi/ne-dwmapi-dwmwindowattribute)?

2021-10-02 14:49 UTC, sylveon commented
In Windows 11, there are documented 0aths for both Mica and Acrylic in Win32. I heavily suggest using those and not supporting Windows 10 for vibrancy, as SetWindowCompositionAttribute is fill of pitfalls, bugs, and weird issues.

Also "vibrancy" is a macOS term, Windows doesn't use it to describe its transparency effects. Suggest using another name, maybe something like backgroundBrush, or hostBackdropBrush (also that would allow devs to so something like pass both vibrancy and backgroundBrush in the window create options, and the right one for the current OS is picked).

2021-10-02 17:25 UTC, riverar commented
> In Windows 11, there are documented paths for both Mica and Acrylic in Win32.

I'm not aware of any official guidance/documentation for these paths. Got a link? (Availability in the preview SDKs is not documentation and Islands is of no use here.)

2021-10-02 18:27 UTC, sylveon commented
https://docs.microsoft.com/en-us/windows/win32/api/dwmapi/ne-dwmapi-dwmwindowattribute
> `DWMWA_USE_HOSTBACKDROPBRUSH`
> 
> Use with DwmSetWindowAttribute. Enables a non-UWP window to use host backdrop brushes. If this flag is set, then a Win32 app that calls Windows::UI::Composition APIs can build transparency effects using the host backdrop brush (see Compositor.CreateHostBackdropBrush). The retrieved value is of type BOOL. TRUE to enable host backdrop brushes for the window; otherwise, FALSE.

For Mica, I believe you can just directly use the Windows::UI::Composition APIs, and this window attribute isn't required.

2021-10-02 18:59 UTC, riverar commented
I had a chat with @sylveon offline as well and while this is a preview API in a preview SDK, we agree this will be the way forward (for Windows 11 only). 👍

So @codebytere could perhaps swap out their method for this one, add Win11 guard rails, and complete this PR.

2021-10-03 11:42 UTC, codebytere commented
@riverar awesome, thanks! i'll get on that this week 🙇🏻‍♀️

2021-10-03 11:57 UTC, alfodei22 commented
id='sp-postQuickEdit' var='post'

2021-12-01 23:25 UTC, XFaonAE commented
Why isnt anyone reviewing the pr

2021-12-08 08:06 UTC, zcbenz commented
> Why isnt anyone reviewing the pr

According to the discussion above, the best way to implement the feature is to use a new API in Windows 11, instead of the unreliable private API used in current approach.

2021-12-08 08:06 UTC, aleversn commented
Thank you for your email. I've received your message. If your message requires a reply, I will sooner get in touch with you. Best RegardsPeichao LaiFuzhou University

2021-12-13 23:41 UTC, XFaonAE commented
> > Why isnt anyone reviewing the pr
> 
> According to the discussion above, the best way to implement the feature is to use a new API in Windows 11, instead of the unreliable private API used in current approach.

So are we waiting on the OP?

2021-12-28 18:14 UTC, XFaonAE commented
Hey! Someone has found a better Api for both acrylic and mica!
> New DWMWA_SYSTEMBACKDROP_TYPE in 22523 SDK, public Win32 API for Mica.
Also for Acrylic.
@codebytere

2021-12-28 18:17 UTC, sylveon commented
It's not available in a stable release of Windows yet, and won't be backported to the existing ones.

2022-03-03 18:22 UTC, ckerr commented on docs/api/browser-window.md
> +* `dark`
_(nit)_ should annotate these three as deprecated here

2022-03-03 18:22 UTC, ckerr commented on docs/api/browser-window.md
> +* `ultra-dark`
should annotate these two as deprecated here

2022-03-03 18:32 UTC, nornagon commented on docs/api/browser-window.md
> +#### `win.setVibrancy(type)` _macOS_ _Windows_
Let's put this under a separate name for Windows

2022-03-03 18:36 UTC, ckerr commented on shell/browser/native_window_views.cc
> +void NativeWindowViews::SetVibrancy(const std::string& type) {
```suggestion
void NativeWindowViews::SetVibrancy(base::StringPiece type) {
```

The API code we call below allows a StringPiece, so we should use that more flexible type here too

2022-03-03 18:36 UTC, ckerr commented on shell/browser/native_window_views.cc
> +      if (!base::HexStringToBytes(color_string, &bytes))
```suggestion
      type.remove_prefix(1);
      if (!base::HexStringToBytes(type, &bytes))
```

2022-05-17 18:12 UTC, aleversn commented
Thank you for your email. I've received your message. If your message requires a reply, I will sooner get in touch with you. Best RegardsPeichao LaiFuzhou University

2022-05-18 12:41 UTC, XFaonAE commented
> @XFaonAE had a comment [here](https://github.com/electron/electron/pull/30298#issuecomment-1002225999) that points to a newer API that might be officially supported upstream? If so, that sounds worth looking into?
> 
> Marking as request-changes

Just to be safe, I did test it out again on the latest dev build, and it still seem to be functioning as expected.
One thing to note is that mica was **not** meant to be used with system native titlebars, which is why some weird behaviour may occure, instead I recommend setting the window style to WS_CAPTION and then moving the client area as needed to hide the titlebar, then design your own titlebar. Its quite the hassle which is why i stopped usin g NodeJS entirly xD Instead I do java now

2022-06-02 10:51 UTC, Levminer commented
Offical docs: https://docs.microsoft.com/en-us/windows/win32/api/dwmapi/ne-dwmapi-dwm_systembackdrop_type?WT.mc_id=WD-MVP-5002756

2022-06-02 14:52 UTC, XFaonAE commented
> Offical docs: https://docs.microsoft.com/en-us/windows/win32/api/dwmapi/ne-dwmapi-dwm_systembackdrop_type?WT.mc_id=WD-MVP-5002756

Great work! But unfortunatly these docs are old, and dont say anything about Mica, 
These documentation references MAY or MAY NOT be helpfull, but they are relavant to Mica and backdrop brushes. UWP components can infact be used with Win32 which is well... that electron is based on

https://docs.microsoft.com/en-us/uwp/api/windows.ui.composition.compositor.createhostbackdropbrush?view=winrt-22621
https://github.com/microsoft/Windows.UI.Composition-Win32-Samples

2022-06-02 14:57 UTC, sylveon commented
What do you mean old? These where published just a few days ago.

They don't refer to Mica by name but it's what you get when using DWMSBT_MAINWINDOW. You get acrylic with DWMSBT_TRANSIENTWINDOW.

2023-05-03 10:49 UTC, codebytere commented
Closed in favor of https://github.com/electron/electron/pull/38163

2023-05-03 10:49 UTC, closed without merging