chore: more crash-keys for gin::Wrappable debugging
electron/electron pull request #30404
Opened 2021-08-04 22:59 UTC by nornagon

#### Description of Change
Adds more detection to the gin::Wrappable crash keys.

cc @vertedinde

#### Release Notes

Notes: none

2021-08-04 23:09 UTC, MarshallOfSound approved these changes

2021-08-04 23:15 UTC, miniak approved these changes

2021-08-04 23:31 UTC, VerteDinde approved these changes

2021-08-04 23:33 UTC, VerteDinde requested changes

2021-08-04 23:33 UTC, VerteDinde commented on shell/common/crash_keys.cc
> +    crash_location = "AutoUpdater";
Sorry, just noticed there's two AutoUpdater checks here, could we remove one?

2021-08-05 18:38 UTC, VerteDinde approved these changes

2021-08-05 18:39 UTC, merged