feat: add width option to dialog.showMessageBox()
electron/electron pull request #30474
Opened 2021-08-10 18:21 UTC by miniak

#### Description of Change
This allows working around the overly narrow NSAlert dialogs on macOS Big Sur
<img width="271" alt="Screen Shot 2021-08-10 at 8 02 22 PM" src="https://user-images.githubusercontent.com/1281234/128914044-d54e5cf6-c230-4423-8acb-09563fbcacc9.png">

#### Checklist
- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [x] relevant documentation is changed or added
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes
Notes: Added `width` option to `dialog.showMessageBox()` / `dialog.showMessageBoxSync()`.

2021-08-11 08:02 UTC, codebytere reviewed
I agree this is a problem worth addressing, but my mild concern here is that this solution is a bit narrow and might prevent us from addressing other similar issues in a more robust way in the future.

For example - with this users can specify a custom width, but would they ever experience issues with height? Would it perhaps make more sense to specify `x, y, width, height` as a `gfx::Rect` here?

2021-08-11 12:40 UTC, miniak commented
> I agree this is a problem worth addressing, but my mild concern here is that this solution is a bit narrow and might prevent us from addressing other similar issues in a more robust way in the future.
> 
> For example - with this users can specify a custom width, but would they ever experience issues with height? Would it perhaps make more sense to specify `x, y, width, height` as a `gfx::Rect` here?

It's only possible to specify width. I am using a dummy https://developer.apple.com/documentation/appkit/nsalert/1530575-accessoryview?language=objc, which has specified width and zero height. There does not seem to be any other good way to make the dialog wider.

2021-08-13 00:45 UTC, zcbenz requested changes
The API looks good to me.

2021-08-13 00:45 UTC, zcbenz commented on shell/browser/ui/message_box_mac.mm
> +    [alert setAccessoryView:[[NSView alloc] initWithFrame:rect]];
The passed view should be autoreleased.

2021-08-18 20:58 UTC, miniak commented on shell/browser/ui/message_box_mac.mm
> +    [alert setAccessoryView:[[NSView alloc] initWithFrame:rect]];
done

2021-08-18 23:40 UTC, zcbenz approved these changes

2021-08-23 08:07 UTC, codebytere approved these changes

2021-09-23 10:56 UTC, merged