feat: enable windows control overlay on Windows
electron/electron pull request #30887
Opened 2021-09-08 21:09 UTC by mlaurencin

Backport of #29600.

See that PR for details.

Notes: Added support for Windows Control Overlay on Windows.

2021-09-08 23:46 UTC, MarshallOfSound reviewed
Approved by @electron/wg-releases, but I want to review the actual patch files before approve-approving

2021-09-21 05:43 UTC, zcbenz approved these changes

2021-09-21 10:43 UTC, zcbenz requested changes

2021-09-21 10:43 UTC, zcbenz commented on shell/browser/native_window_mac.mm
> +  options.Get(options::kResizable, &resizable);
This code has no effect as it is reading the option into a temporary variable.

2021-09-23 10:52 UTC, zcbenz approved these changes

2021-09-23 10:52 UTC, zcbenz commented
This PR requires review from @electron/wg-upgrades.

2021-09-23 11:25 UTC, deepak1556 approved these changes
@mlaurencin are the chromium patches direct backports or did you have to make any modifications ?

2021-09-23 18:20 UTC, mlaurencin commented
> @mlaurencin are the chromium patches direct backports or did you have to make any modifications ?

The chromium patches were just directly backported with no modifications.

2021-09-23 20:04 UTC, merged