docs: update context isolation doc
electron/electron pull request #30898
Opened 2021-09-09 19:50 UTC by erickzhao

#### Description of Change

Updates the Context Isolation tutorial.

Changes:
* Removes language around context isolation being enabled in the future
* Adds a bit more detail to the Migration section
* Adds a section about augmenting the global `window` object with TypeScript

I usually don't add release notes, but I figure the TypeScript stuff is worth pointing out.

cc @MarshallOfSound @malept

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] relevant documentation is changed or added
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: adds documentation on using TypeScript with the `contextBridge` API

2021-09-10 01:04 UTC, malept requested changes

2021-09-10 01:04 UTC, malept commented on docs/tutorial/context-isolation.md
> +You should read the `contextBridge` documentation linked above to fully understand its limitations. For instance, you can't send custom prototypes or symbols over the bridge.
```suggestion
Please read the `contextBridge` documentation linked above to fully understand its limitations. For instance, you can't send custom prototypes or symbols over the bridge.
```

2021-09-10 01:04 UTC, malept commented on docs/tutorial/context-isolation.md
> +export interface ElectronAPI {
Per the declaration below:

```suggestion
export interface IElectronAPI {
```

2021-09-15 00:46 UTC, zcbenz approved these changes

2021-09-15 01:50 UTC, merged