fix: fix crash on win7 casued by "GetHostNameW" function
electron/electron pull request #31011
Opened 2021-09-17 13:49 UTC by TomaszMa

uv lib dosen't support windows 7 anymore. Current version of uv lib
(1.42.0) is using "GetHostNameW" function which is not present in
windows 7 Ws2_32/64.dll. Revert "uv_os_gethostname" function to 1.41.0
version, which works fine on windows 7 and higher.

#### Description of Change

#### Checklist

- [x] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [ ] relevant documentation is changed or added
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: Resolves problem with crash on windows 7 caused by uv lib which is using "GetHostNameW" function.

2021-09-17 16:35 UTC, nornagon requested changes
Please propose these changes upstream to libuv.

2021-09-20 09:44 UTC, TomaszMa commented
> Please propose these changes upstream to libuv.

That was the plan, but I saw earlier that they rejected similar fix in UVlib with comment that they do not support win7 anymore (https://github.com/libuv/libuv/issues/3305 and https://github.com/libuv/libuv/issues/3260).
Now I see that there is one PR in review in UVlib: https://github.com/libuv/libuv/pull/3285
I dont know when if and whether at all it will land in UVlib.
So till situation in UVlib is not clear I decided to make PR to Electron using patch mechanism. In other case Electron will not support win7 till UVlib will fix it, or not.

2021-09-21 01:34 UTC, zcbenz reviewed
It seems that libuv/libuv#3285 has a high chance to get merged, I prefer to wait for it first.

2021-11-11 15:32 UTC, miniak commented
I think we should fix the crash first and then worry about upstreaming the fix. We broken releases, which don't work on Windows 7. #31795

2021-11-12 08:02 UTC, zcbenz commented
I'm good backporting the libuv patch before it is merged to upstream, since it has already been approved in review, and we should not suddenly drop Windows 7 support.

I'll start a PR to backport https://github.com/libuv/libuv/pull/3285 instead.

2021-11-12 08:35 UTC, zcbenz commented
Close in favor of https://github.com/electron/electron/pull/31804.

2021-11-12 08:35 UTC, closed without merging