fix: sanitize params for 'context-menu' event sent over IPC for webview
electron/electron pull request #31259
Opened 2021-10-03 01:03 UTC by miniak

#### Description of Change
Fixes #31249

#### Checklist
- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/main/docs/development/testing.md)
- [ ] relevant documentation is changed or added
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes
Notes:

2021-10-03 03:42 UTC, MarshallOfSound requested changes
Can we instead make `frame` a non enumerable getter

2021-10-04 15:52 UTC, MarshallOfSound approved these changes

2021-10-04 16:50 UTC, codebytere approved these changes

2021-10-04 17:42 UTC, samuelmaddock approved these changes

2021-10-04 18:00 UTC, merged