chore: update nmv to 103 for Electron 18
electron/electron pull request #31778
Opened 2021-11-09 22:07 UTC by VerteDinde

#### Description of Change
This PR updates our NMV to 103

Please do not merge until this PR has been closed: https://github.com/nodejs/node/pull/40768

#### Checklist

- [ ] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/main/docs/development/testing.md)
- [ ] relevant documentation is changed or added
- [ ] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes:

2021-11-10 01:42 UTC, miniak approved these changes

2021-11-10 01:44 UTC, miniak commented
@VerteDinde I believe this should technically be `semver/major` as it is a breaking change. I did that same for the previous bump #31282.

2021-11-10 08:50 UTC, zcbenz approved these changes

2021-11-10 18:56 UTC, jkleinsc approved these changes

2021-11-10 19:45 UTC, ckerr approved these changes

2021-11-11 15:13 UTC, jkleinsc requested changes
Marking as changes requested so this doesn't accidentally get merged early.

2021-11-17 19:35 UTC, merged