fix: navigator.keyboard.lock() not working
electron/electron pull request #31846
Opened 2021-11-15 15:54 UTC by codebytere

Backport of #31572

See that PR for details.

Notes: Enables support for `navigator.keyboard.lock()`.

2021-11-22 07:42 UTC, zcbenz commented
Build is failing.

2022-01-13 09:46 UTC, zcbenz approved these changes

2022-01-18 20:54 UTC, jkleinsc requested changes
- I tested this with @clavin's gist from here: https://gist.github.com/clavin/3d5a69768c914d56ccf732bbca8d488e (as commented in #31420 and it doesn't seem to fix the issue (at least on macOS) as I can command - tab when the lock is on.

2022-03-30 01:54 UTC, miniak commented
@codebytere Electron 15 should only be getting security fixes now, does it make sense to keep this PR?

2022-03-30 07:41 UTC, closed without merging