feat: add app.isHidden API for macOS
electron/electron pull request #32155
Opened 2021-12-11 20:04 UTC by mitchchn

#### Description of Change

Added an API to check if the app is hidden on macOS. This is a distinct state from the app _windows_ being hidden, and can be used to implement unique behaviour on activation. It is also useful in conjunction with `NSWindow.canHIde`, which I will introduce in a follow-up MR if there are no objections.

#### Checklist

- [ ] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/main/docs/development/testing.md)
- [ ] relevant documentation is changed or added
- [ ] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes:

2022-01-05 18:28 UTC, jkleinsc commented
API LGTM

2022-01-10 17:10 UTC, mitchchn commented
It looks like CI timed out but I'm unable to re-run it. There shouldn't be any test failures.

2022-01-10 21:37 UTC, nornagon commented
Should perhaps also be exposed as `.hidden` given https://github.com/electron/governance/blob/main/wg-api/best-practices.md#use-getters-and-setters-as-well-as-properties ?

2022-01-11 16:08 UTC, mitchchn commented
@nornagon the reason I didn't add a getter is because there is no setter (unless `app.hidden = true` hides the app, which feels wrong to me?) and also out of analogy with `BrowserWindow.isVisible()` which does not have a getter. I can add one if you still think it should be there.

2022-01-19 19:02 UTC, nornagon commented
@mitchchn I don't feel strongly enough about it to block this, so API LGTM.

2022-03-02 19:56 UTC, samuelmaddock reviewed
API LGTM

2022-03-02 19:56 UTC, samuelmaddock commented on docs/api/app.md
> +Whether the application is hidden (e.g. with Command-H).
Mentioning windows for clarity.
```suggestion
Whether the application—including all of its windows—is hidden (e.g. with `Command-H`).
```

2022-03-03 00:14 UTC, mitchchn commented
> Looks like newly added tests are failing

@jkleinsc hiding and unhiding is async. To reliably wait on these events in the test suite I would need to expose "hide" and "unhide" events on `app` for macOS (https://developer.apple.com/documentation/appkit/nsapplication/1428562-didhidenotification). How would we feel about that?

2022-03-03 00:37 UTC, jkleinsc commented
@mitchchn you can use the `waitUntil` spec helper:
```
      await expect(
        waitUntil(() => app.isHidden() === true)
      ).to.eventually.be.fulfilled();
```

2022-03-03 19:06 UTC, jkleinsc reviewed
API LGTM

2022-03-03 21:50 UTC, codebytere approved these changes
API LGTM

2022-03-08 21:00 UTC, jkleinsc requested changes
The documentation for this feature needs to specify that the return value is a boolean so that the typescript generator can properly label this function's return value.

2022-03-08 21:00 UTC, jkleinsc commented on docs/api/app.md
> +Whether the application—including all of its windows—is hidden (e.g. with `Command-H`).
```suggestion
Returns `boolean` - `true` if the application—including all of its windows—is hidden (e.g. with `Command-H`), `false` otherwise.
```

2022-03-09 21:35 UTC, jkleinsc requested changes
The new test should use the `ifdescribe` helper

2022-03-09 21:35 UTC, jkleinsc commented on spec-main/api-app-spec.ts
> +  showHideDescribe('app hide and show API', () => {
```suggestion
  ifdescribe(process.platform === 'darwin')('app hide and show API', () => {
```

2022-03-09 22:33 UTC, jkleinsc approved these changes

2022-03-14 14:50 UTC, mitchchn commented
@jkleinsc: thanks for your review feedback. Is there anything left for me to do here? It looks like CI is timing out, not failing on my test, but if that's not the case I can investigate.

2022-03-30 01:34 UTC, merged