fix: Don't create console window when creating process
electron/electron pull request #32340
Opened 2022-01-05 00:42 UTC by rzhao271

#### Description of Change

Since the `windowsHide` parameters still default to `false`, we need to keep the patch that disables console windows from showing up, otherwise for `execSync` calls, or `spawnSync` calls with `shell: true`, console windows still show up for Windows users.

This issue has been occurring since Electron 16.

Downstream issue: https://github.com/microsoft/vscode/issues/138792

CC @deepak1556 

#### Checklist

- [x] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/main/docs/development/testing.md)
- [x] relevant documentation is changed or added
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: Fix regression where console windows would open for execSync and some spawnSync calls for Windows users.

2022-01-05 01:14 UTC, deepak1556 requested changes
This patch was removed to adopt the embedder flag provided in https://github.com/nodejs/node/pull/39712

It looks like the spawn_sync path was missed in the upstream PR. This should be addressed there.

/cc @zcbenz

2022-01-05 01:59 UTC, deepak1556 commented on patches/node/fix_don_t_create_console_window_when_creating_process.patch
> ++    uv_process_options_.flags |= UV_PROCESS_WINDOWS_HIDE_CONSOLE;
Can you try upstreaming this patch. Thanks!

2022-01-06 15:06 UTC, rzhao271 commented
The upstream node patch is being tracked at https://github.com/nodejs/node/pull/41412 and seems nearly ready to merge.

2022-01-06 15:13 UTC, deepak1556 commented on patches/node/fix_don_t_create_console_window_when_creating_process.patch
> +The patch can be removed when the windowsHide parameter
```suggestion
The patch has been upstreamed with https://github.com/nodejs/node/pull/41412
```

2022-01-06 21:42 UTC, deepak1556 approved these changes

2022-01-07 08:38 UTC, zcbenz approved these changes

2022-01-07 08:38 UTC, merged