chore: cherry-pick c5571653d932 from chromium
electron/electron pull request #32353
Opened 2022-01-05 19:43 UTC by nornagon

Quota: Use Threadsafe Pressure Callback.

Fixes UAF by removing use of raw ptr to StorageNotificationService.
Instead, the service's interface exposes a method to create a
thread-safe callback to pass to the quota manager instead.

This change also changes the parameter type for the call chain from
url::Origin to blink::StorageKey to match the type Quota is keyed on.

Bug:1275020

(cherry picked from commit e304c0373f9cc4a65d39d7094e4897627e83390e)

Change-Id: Icc696d22fa41324e7a6c056599db635bb5de6291
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3347939
Reviewed-by: Joshua Bell <jsbell@chromium.org>
Reviewed-by: Nasko Oskov <nasko@chromium.org>
Commit-Queue: Jarryd Goodman <jarrydg@chromium.org>
Cr-Original-Commit-Position: refs/heads/main@{#953375}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3360203
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Owners-Override: Krishna Govind <govind@chromium.org>
Commit-Queue: Krishna Govind <govind@chromium.org>
Cr-Commit-Position: refs/branch-heads/4664@{#1352}
Cr-Branched-From: 24dc4ee75e01a29d390d43c9c264372a169273a7-refs/heads/main@{#929512}

Notes:

2022-01-13 01:50 UTC, zcbenz requested changes
Build is failing 

```
../../content/browser/storage_partition_impl.cc:1215:15: error: 'CreateThreadSafePressureNotificationCallback' is a private member of 'content::StorageNotificationService'
            ->CreateThreadSafePressureNotificationCallback());
              ^
../../content/public/browser/storage_notification_service.h:42:3: note: declared private here
  CreateThreadSafePressureNotificationCallback() = 0;
  ^
1 error generated.
```

2022-01-24 11:03 UTC, zcbenz approved these changes

2022-01-24 17:27 UTC, ckerr approved these changes

2022-01-24 18:16 UTC, jkleinsc approved these changes

2022-01-24 18:16 UTC, merged