docs: separate the dependency list for ubuntu
electron/electron pull request #32607
Opened 2022-01-25 09:56 UTC by bavulapati

#### Description of Change
Closes #27704 

[Chromium script](https://chromium.googlesource.com/chromium/src/+/main/build/install-build-deps.sh#527) to install build dependencies seems to suggest that `libgnome-keyring-dev` isn't needed on Ubuntu 20.
And the tests run fine with `python3-dbusmock`

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] relevant documentation is changed or added

#### Release Notes

Notes: Separates dependency list for ubuntu < 20.04 and ubuntu >= 20.04

2022-01-25 21:10 UTC, jkleinsc approved these changes

2022-01-25 21:42 UTC, nornagon approved these changes

2022-01-26 01:02 UTC, erickzhao requested changes
Dev documentation should be `Notes: none` for release notes

2022-01-26 02:08 UTC, bavulapati commented
@erickzhao Changed the same. PTAL. Thanks.

2022-01-26 15:29 UTC, merged