fix: make `process.exit()` synchronous even after the app is ready
electron/electron pull request #32831
Opened 2022-02-09 12:34 UTC by RaisinTen

#### Description of Change

The `process.exit()` function should be synchronous both before and after
the `ready` event gets emitted.

Fixes: https://github.com/electron/electron/issues/32060
Signed-off-by: Darshan Sen <raisinten@gmail.com>

cc @zcbenz because `Browser::Exit()` was introduced in https://github.com/electron/electron/pull/3356

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] tests are [changed or added](https://github.com/electron/electron/blob/main/docs/development/testing.md)
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: Makes `process.exit()` synchronous even after the app is ready.

2022-02-11 11:19 UTC, codebytere approved these changes
This looks good to me but i'll defer to @zcbenz for final sign-off!

2022-02-11 13:12 UTC, zcbenz requested changes
Killing the process immediately will leave all native resources unreleased, which leads to problems like cookies and localStorage not saved to disk.

Our document made a wrong statement about `app.exit`, this method actually means to behave like `app.quit` that gracefully exits the app but set an exit code instead, and I believe most users of this API are already relying on this behavior (for example [vscode](https://github.com/microsoft/vscode/blob/bf1c9e93913714c85b0db6f2e2690b0bddbab7e4/src/vs/platform/lifecycle/electron-main/lifecycleMainService.ts#L636)), so we simply can not change this behavior as it would be a breaking change.

I'm fine making `process.exit` kill the process immediately, though this might still be a breaking change. /cc @electron/wg-api

2022-02-16 15:59 UTC, RaisinTen commented
@zcbenz

> Killing the process immediately will leave all native resources unreleased, which leads to problems like cookies and localStorage not saved to disk.

I thought that the code above my exit() call already handled those synchronously. I believe we should add a regression test to make sure that `app.exit()/quit()` takes care of releasing the resources then, in case that's not already added / disabled.

> that gracefully exits the app

I'm not sure I fully understand that. Does that mean we expect `app.exit()/quit()` to:
* release all sorts of resources and exit OR
* only take care of closing open windows, register an exit call to run at an unknown time in the future and then return back to JS where the user can run code to release the resources manually for an unknown amount of time till the actual exit() call is fired

I say "an unknown amount of time" because code like:
```js
setTimeout(() => console.log('lol'), 0);
require('electron').app.quit();
```
prints lol but:
```js
setTimeout(() => console.log('lol'), 1000); // 0 -> 1000
require('electron').app.quit();
```
doesn't.

> I'm fine making process.exit kill the process immediately

Cool :)

2022-02-16 21:47 UTC, nornagon commented
If we want to have a "graceful but immediate" exit event, we will need to refactor our shutdown logic, because at present the shutdown process can in some cases trigger JS events: https://github.com/electron/electron/blob/cc0eb7b908344403bb14e9ebdd1422f38701c57f/shell/browser/javascript_environment.cc#L368-L374

2022-02-17 00:24 UTC, zcbenz commented
The shutdown procedure of Chromium is designed to be asynchronous that, there is no possibility to have an `app.exit` that can quit the process immediately while cleaning resources gracefully.

Shutting down Chromium works in following steps:

1. We request all renderer processes to close;
2. Return control to task scheduler and wait for each renderer process to quit;
3. When each renderer process is cleaned up, we destroy its WebContents;
4. After all renderer processes are finished, we tell Chromium to quit and return control to task scheduler;
5. Chromium runs shutdown tasks, some of them are asynchronous, such as writing localStorage to disk;
6. After all shutdown tasks are done, Chromium will exit the process.

If we simply force the main process to exit in any of those steps, there will be high possibility of loss of data, and there might also be crashes on exit (https://github.com/electron/electron/issues/3350).

I'm fine making `process.exit` quit the process immediately because most Node.js code expect so and could run into unknown bugs if we do not do so. But on the other hand in an Electron app most users would surely not want to lose data on exit, so we might need more discussions on the behavior of `process.exit`.

2022-02-17 14:26 UTC, RaisinTen commented
> If we want to have a "graceful but immediate" exit method, we will need to refactor our shutdown logic, because at present the shutdown process can in some cases trigger JS events

Yep, I agree. There are some other deviations in this aspect, like - currently the process 'exit' handler doesn't get run unless we are on the repl.

> The shutdown procedure of Chromium is designed to be asynchronous that, there is no possibility to have an app.exit that can quit the process immediately while cleaning resources gracefully.

But is there anything preventing us from reliably terminating only JS execution - the rest of the code, coming after the `app.exit()` call? Because it seems to be UB to run any code after the exit call from the POV of a user because there doesn't seem to be a way to know when exactly the program will exit.

2022-02-17 21:28 UTC, nornagon commented
@RaisinTen it's not really so straightforward, e.g. all our `WebContents` etc. objects are JavaScript objects, so we can't easily shut down V8 without also deleting all our tracking objects.

2022-04-08 06:52 UTC, RaisinTen commented
I have updated the code to remove the monkey patch on process.exit(), so that should work the same way as in Node.js. I think we can change how `app.quit()` and `app.exit()` works in a different PR. PTAL.

2022-04-10 10:32 UTC, zcbenz reviewed
Can you document this in `docs/breaking-changes.md`?

2022-04-10 10:32 UTC, zcbenz commented on spec/fixtures/api/process-exit-after-ready/package.json
> +  "name": "process-exit-after-ready",
```suggestion
  "name": "electron-test-process-exit-after-ready",
```

2022-04-10 10:32 UTC, zcbenz commented on spec/fixtures/api/process-exit-before-ready/package.json
> +  "name": "process-exit-before-ready",
```suggestion
  "name": "electron-test-process-exit-before-ready",
```

2022-04-10 10:49 UTC, MarshallOfSound requested changes
I don't understand the need for this breaking change, it will be a PITA to locate for apps impacted and afaics it serves no real benefit to the majority of apps.

-1 on this change due to the breaking and incredibly subtle nature, folks have used `app.exit` and `process.exit` interchangably for years.  A loose search of `process.exit electron` (not exact at all but at least an indicator) yields 30K results on public github alone.

Without incredibly strong reasoning we should not be landing breaking changes like this.  Is there an upstream change that is forcing us to make this change? Will our current shutdown lifecycle become unmaintainable? Is the current status quo negatively impacting apps? Etc.

2022-04-10 11:03 UTC, RaisinTen commented
@MarshallOfSound 

> I don't understand the need for this breaking change

Currently, there's no way to exit the app instantly with a specified error code after the ready event gets emitted and `process.exit()` is meant to be there just for that purpose.

> Without incredibly strong reasoning we should not be landing breaking changes like this.

There is absolutely no reason for the app to execute JS code that comes after the `process.exit()` call. There's no way to tell when Chromium will shutdown, so essentially that's undefined behavior. We should get rid of such a foot gun from users.

> Is the current status quo negatively impacting apps?

In our test suite at Postman, we were using a tear down logic like https://gist.github.com/RaisinTen/ced9932fd0d76dd30ec72758bc18bc51 and I found it very confusing why the errors got printed but the tests exited with a 0 error code.

2022-04-11 06:54 UTC, RaisinTen commented
> Can you document this in `docs/breaking-changes.md`?

@zcbenz done, PTAL.

2022-04-13 08:28 UTC, zcbenz requested changes
I'm marking this PR as request changes as the test is hanging in CI.

2023-03-28 17:50 UTC, ckerr commented
Dusting off this older PR since Zoilist was asking about it in wg-api.

Looks like this has been targeted for 21, 22, 23, and 24 over the last year :laughing: 

Is this PR still needed @RaisinTen, @zcbenz? That is, should we followup to try and to get it , or should this PR be closed?

2023-03-29 05:32 UTC, RaisinTen commented
Thanks for the ping. I wasn't able to spend enough time to come up with the right fix, so I'll close it.

2023-03-29 05:32 UTC, closed without merging