test: fix crash on image.crop
electron/electron pull request #33148
Opened 2022-03-03 23:51 UTC by dsanders11

#### Description of Change

Ran into this causing a test crash on an M1 MBP. The root crash is in a converter, but this works around the test crash now.

@codebytere 

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes

#### Release Notes

Notes: none

2022-03-03 23:54 UTC, codebytere approved these changes

2022-03-03 23:59 UTC, ckerr approved these changes

2022-03-08 19:22 UTC, jkleinsc requested changes
@dsanders11 can you rebase this to the latest from main?  That should resolve the failing CI.

2022-03-09 22:09 UTC, samuelmaddock approved these changes

2022-03-22 00:37 UTC, jkleinsc approved these changes

2022-03-23 00:14 UTC, merged