fix: prevent UAF crash in setCertificateVerifyProc
electron/electron pull request #33204
Opened 2022-03-09 00:27 UTC by nornagon

#### Description of Change
This fixes a bug with the RemoteCertVerifier patch that drives the
`ses.setCertificateVerifyProc` API. When an in-flight request was cancelled
after the procedure was invoked but before the result was received, a
use-after-free could occur.

Fixes #31675.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/main/docs/development/testing.md)
- [ ] relevant documentation is changed or added
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: Fixed a network service crash that could occur when using setCertificateVerifyProc.

2022-03-09 03:06 UTC, deepak1556 approved these changes

2022-03-09 03:06 UTC, deepak1556 commented on patches/chromium/network_service_allow_remote_certificate_verification_logic.patch
> ++    *out_req = std::make_unique<Request>(); // TODO: also pass this to OnRequestFinished
Is the TODO comment still relevant ?

2022-03-09 17:39 UTC, nornagon commented on patches/chromium/network_service_allow_remote_certificate_verification_logic.patch
> ++    *out_req = std::make_unique<Request>(); // TODO: also pass this to OnRequestFinished
nope, thanks for catching.

2022-03-09 21:40 UTC, jkleinsc requested changes
Looks like tests are legitimately failing.

2022-03-10 11:03 UTC, deepak1556 approved these changes

2022-03-11 19:35 UTC, merged

2022-03-22 15:15 UTC, lauw70 commented
@nornagon do you have any idea when we could expect this fix to land in a 17+.x.y stable release?