fix: queue bounds changes when moving BrowserWindows
electron/electron pull request #33288
Opened 2022-03-16 09:56 UTC by codebytere

#### Description of Change

Closes https://github.com/electron/electron/issues/33279.
Refs https://bugs.chromium.org/p/chromium/issues/detail?id=251813

It's the case at present that `widget()->SetBounds(bounds)` does not take effect if the window is currently being moved or resized. This is an open issue on Chromium since 2013, with no real solution implemented upstream but several options suggested, including:

> Drag completes ignoring the bounds update but the bounds update is queued and then executed after drag completes.

In a Chromium context, this might not be ideal, but in an Electron context I believe this is the most expected behavior from a development standpoint. As a result of this PR, the bounds update correctly once the user completes the resize or the drag movements to reflect the new bounds set programmatically.

Tested with https://gist.github.com/6b6ea5cdaa1883656a8bd0bf89195283. This is unfortunately not directly testable via spec, given that it's dependent on user-initiated movement.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: Fixed an issue where new bounds set via `setBounds` was not correctly applied if the user was moving or resizing the window concurrently.

2022-03-16 20:09 UTC, dsanders11 commented
A couple of questions and comments. First, it looks like this is only implemented for Windows? If that's intentional, can it be mentioned in the description and release notes?

- If Windows only, can we `#ifdef` the changes? It looks to me like with the current code the queue will be filled on Linux and `SetBounds` while moving/resizing ignored and the queue will never be read
- This is implemented as a queue, but only one item is popped when the move/resize ends. What happens if you change the repro gist to use `setinterval` instead of `settimeout`, and keep dragging during that time? Won't multiple bounds changes be queued up, but only one read? Seems that would affect future moves/resizes - it'll start playing back the full queue, but only each time you move/resize the window.

2022-03-16 22:52 UTC, codebytere commented
@dsanders11 you're right, i ifdef'd the queue itself and whiffed on the queue fill part. I've also corrected the queue pop logic.

2022-03-16 23:05 UTC, pushkin- commented
Is there a reason we even need a queue, or should we just remember whatever the latest setBounds call was and just apply that? Why do we need to move the window 20 or whatever times in a row?

2022-03-17 08:40 UTC, codebytere commented
@pushkin- i also thought about that. i'd be fine with either.

2022-03-21 17:37 UTC, jkleinsc requested changes
It looks like true queuing wasn't implemented.  Not sure if it was intentional or not.

2022-03-21 17:37 UTC, jkleinsc commented on shell/browser/native_window_views.h
> +#include <queue>
It doesn't look like this is used?

2022-03-21 17:45 UTC, jkleinsc approved these changes

2022-03-22 06:06 UTC, zcbenz approved these changes

2022-03-22 06:07 UTC, merged