fix: libuv patches to address child_process.spawn slowness
electron/electron pull request #33337
Opened 2022-03-18 18:40 UTC by nornagon

#### Description of Change
Closes #26143.

This backports six PRs from libuv 1.44.1 to fix slow child_process spawning
behavior on macOS Big Sur and later.

libuv references:
- libuv/libuv#3257
- libuv/libuv#3537
- libuv/libuv#3251
- libuv/libuv#3512
- libuv/libuv#3441
- libuv/libuv#3451

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/main/docs/development/testing.md)
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: Fixed slowness when using child_process.spawn and related methods on macOS Big Sur and newer.

2022-03-21 00:49 UTC, zcbenz approved these changes

2022-03-21 05:03 UTC, deepak1556 commented
@nornagon the following PRs are also relevant to this backport

https://github.com/libuv/libuv/pull/3524
https://github.com/libuv/libuv/pull/3521

2022-03-23 00:34 UTC, deepak1556 requested changes
Marking to avoid accidental merge.

2022-03-23 06:59 UTC, deepak1556 approved these changes

2022-03-23 13:30 UTC, deepak1556 commented
Failing tests are unrelated, merging.

2022-03-23 13:30 UTC, merged