test: scope internal test fixtures under `@electron`
electron/electron pull request #33822
Opened 2022-04-18 20:37 UTC by JamieMagee

#### Description of Change

This PR scopes the internal test fixtures `echo` and `uv-dlopen` under the `@electron` scope.

I understand that these packages are not published and are only fixtures for the test suite. However, it is always a good practice to use scopes that you own to avoid substitution attacks[^1]. This attack was already attempted with `uv-dlopen` and npmjs.com has a security hold on that package name as a result[^2].

I wish to do the same change for other `package.json` files under `spec/fixtures` as well, but thought I'd start small first.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [x] tests are [changed or added](https://github.com/electron/electron/blob/main/docs/development/testing.md)
- [x] relevant documentation is changed or added
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: none

[^1]: https://github.blog/2021-02-12-avoiding-npm-substitution-attacks/
[^2]: https://www.npmjs.com/package/uv-dlopen

2022-04-22 14:44 UTC, miniak approved these changes

2022-04-25 07:42 UTC, deepak1556 approved these changes

2022-04-25 07:53 UTC, MarshallOfSound requested changes
To avoid confusion with the `@electron` scope that actually contains real dependencies and some people have permission to publish to can we instead use `@electron-ci` which I just reserved on NPM and no-one has publish rights too.

2022-04-25 07:53 UTC, MarshallOfSound commented
Also to make CI run can you please sign in to Circle CI 👍

2022-04-25 07:53 UTC, mraulim commented
Krásny deň,
ďakujeme za email a potvrdzujeme, že sme ho zaevidovali. Už teraz sa postupne začína posúvať v našom poradovníku na spracovanie, a ak všetko pôjde podľa plánu, tak vám počas pracovných dní odpovieme už do 24 hodín. Ruku na to. 📷
Ak je vaša požiadavka naozaj urgentná, tak neváhajte a napíšte nám v čete na stránke.
Spríjemnite si čakanie zaujímavosťami na našom magazíne alebo si pozrite, aké nové zážitky pre vás máme prvýkrát.
Tím Zľavomat

On 4/25/2022 Samuel Attard ***@***.***) wrote:
> @MarshallOfSound requested changes on this pull request.
> 
> To avoid confusion with the ***@***.***` scope that actually contains real dependencies and some people have permission to publish to can we instead use ***@***.***` which I just reserved on NPM and no-one has publish rights too.
> 
> 
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/electron/electron/pull/33822#pullrequestreview-951472847
> You are receiving this because you are subscribed to this thread.
> 
> Message ID: ***@***.***>

2022-04-26 15:46 UTC, miniak commented
@JamieMagee there are some test failures

2022-04-29 18:02 UTC, JamieMagee commented
@miniak Thanks! I missed a couple of references to the old package names. Updated them to have `@electron-ci`.

2022-04-29 20:40 UTC, miniak commented
@MarshallOfSound can you please unblock?

2022-04-29 22:21 UTC, MarshallOfSound approved these changes

2022-05-02 09:44 UTC, alexeykuzmin commented
@MarshallOfSound 👋 , can you (or someone else with superpowers) please restart that one failed build or forcibly merge the PR?

2022-05-02 17:09 UTC, jkleinsc commented
- Merging as CI failure is known flake documented in #34020

2022-05-02 17:09 UTC, merged

2022-05-02 18:50 UTC, miniak commented
/top run backport-to 15-x-y

2022-05-02 18:50 UTC, miniak commented
/trop run backport-to 15-x-y