build: use smaller resource_class because goma
electron/electron pull request #33905
Opened 2022-04-23 11:36 UTC by MarshallOfSound

As noted in #33904 with Goma and other CI improvements we really don't need to be burning a 20 core machine.  Some super basic testing shows that dropping from the 20 core machine to an 8 core machine _increases_ CI time by ~30-90 seconds, I don't think that is going to be the end of the world for anyone especially when the above mentioned PR speeds CI up by over double that 🤷 

This should drop our linux credit usage by almost ~50% ✨ 🥳 

Changes:
* Testing builds now use 8 core instead of 20 core
* Unused release jobs deleted
* Publish builds now use 16 core instead of 20 core

Notes: no-notes

2022-04-25 14:03 UTC, jkleinsc requested changes
looks good to me other than an unnecessary use of default size

2022-04-25 15:27 UTC, MarshallOfSound commented on .circleci/config/base.yml
> +      size: 2xlarge
This change just showed how weird it was that we depended on the default value all over the place.  Felt it was better to be explicit, maybe we should just remove the default value and force explicit sizing

2022-04-27 06:38 UTC, MarshallOfSound commented on .circleci/config/base.yml
> +      size: 2xlarge
I've done this, we had a couple of defaults that didn't make things clear.  So I've removed some defaults and made things more explicit.

2022-04-27 18:27 UTC, jkleinsc requested changes
We can't remove the xcode: "13.3.0" because that is what build tools uses to determine xcode version

2022-04-27 18:27 UTC, jkleinsc commented on .circleci/config/base.yml
> -      xcode: "13.3.0"
Removing this will break build tools as it looks for xcode: ... to determine which version of xcode to use

2022-04-27 18:50 UTC, jkleinsc approved these changes
I'm fine with this as long as https://github.com/electron/build-tools/pull/370 gets merged in.

2022-04-28 10:17 UTC, merged

2022-05-03 08:22 UTC, MarshallOfSound commented
/trop run backport-to 19-x-y, 18-x-y, 17-x-y