fix: Handle an electron.d.ts file in a custom build
electron/electron pull request #33979
Opened 2022-04-29 15:29 UTC by felixrieseberg

#### Description of Change
Right now, if you use a custom build or a mirror during the installation of Electron, you will always get the `electron.d.ts` file that was part of the npm package - and not the one that's part of your custom build or mirror.

With this change, during installation, we check if the downloaded zip file contained an `electron.d.ts` file. If so, we move it one level up. 

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/main/docs/development/testing.md)
- [x] relevant documentation is changed or added
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: Fixed: If a custom Electron build contains an electron.d.ts file, it is now being used.

2022-04-29 23:14 UTC, felixrieseberg commented
The broken Windows build seems to be a fluke!

2022-05-02 07:13 UTC, MarshallOfSound commented
@felixrieseberg Can you re-auth with Circle to kick off the CI builds, you may have to push an empty commit too

2022-05-04 08:18 UTC, codebytere approved these changes
Approved w/ small typo fix!

2022-05-04 08:18 UTC, codebytere commented on npm/install.js
> +      const hasTypeDefenitions = fs.existsSync(srcTypeDefPath)
nit: `s/hasTypeDefenitions/hasTypeDefinitions`

2022-05-06 15:04 UTC, felixrieseberg commented on npm/install.js
> +      const hasTypeDefenitions = fs.existsSync(srcTypeDefPath)
```suggestion
      const hasTypeDefinitions = fs.existsSync(srcTypeDefPath)
```

2022-05-09 15:22 UTC, jkleinsc commented
@felixrieseberg can you re-authenticate with CircleCI and then push an empty commit to trigger CircleCI testing?

2022-06-14 16:29 UTC, jkleinsc requested changes
Lint failures need to be addressed.

2022-09-16 01:45 UTC, ckerr commented
@jkleinsc are you good with these lint changes?

2022-09-26 18:27 UTC, jkleinsc approved these changes

2022-09-26 18:39 UTC, merged

2022-10-19 20:30 UTC, hassanmahdi58 commented
electron.d.ts