docs: add macOS height option info
electron/electron pull request #34451
Opened 2022-06-06 19:08 UTC by mlaurencin

#### Description of Change

This PR modifies the documentation for the WCO height option added by https://github.com/electron/electron/pull/34278 to include macOS functionality.

#### Checklist

- [ ] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/main/docs/development/testing.md)
- [ ] relevant documentation is changed or added
- [ ] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: None

2022-06-06 20:10 UTC, clavin approved these changes

2022-06-06 21:08 UTC, jkleinsc requested changes
LGTM, but https://github.com/electron/electron/blob/main/docs/api/browser-window.md should also be changed

2022-06-09 19:14 UTC, jkleinsc commented
@mlaurencin https://github.com/electron/electron/blob/main/docs/api/browser-window.md#winsettitlebaroverlayoptions-windows needs to be updated.

2022-06-09 19:16 UTC, jkleinsc approved these changes

2022-06-09 19:17 UTC, jkleinsc commented
@mlaurencin I was thinking https://github.com/electron/electron/blob/main/docs/api/browser-window.md#winsettitlebaroverlayoptions-windows needed to be updated but I see that is Windows only functionality.

2022-06-09 19:17 UTC, merged