chore: remove deprecated 'new-window' event
electron/electron pull request #34526
Opened 2022-06-13 17:29 UTC by miniak

#### Description of Change
It has been deprecated since Electron 13.

#### Checklist
- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] tests are [changed or added](https://github.com/electron/electron/blob/main/docs/development/testing.md)
- [x] relevant documentation is changed or added
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes
Notes: The deprecated 'new-window' event has been removed.

2022-06-13 17:32 UTC, nornagon requested changes
i'm worried about removing this without any machinery to explode when people try to do things the old way. we used to recommend `new-window` listeners for security reasons, and i bet a lot of apps still use it. removing it without an error/warning seems dangerous.

i suggest a 2-version deprecate/delete cycle:
1. in version `X`, add a warning when an app registers a `new-window` listener.
2. in version `X+1`, remove the event and throw an error when the app registers a `new-window` listener.

2022-06-13 17:35 UTC, miniak commented
@zcbenz can you please help addressing this?
https://github.com/electron/electron/blob/16cd22ff6a4dcccc3b8cc3f959b83b0d3f1ac68f/lib/browser/api/web-contents.ts#L690-L694
https://github.com/electron/electron/blob/16cd22ff6a4dcccc3b8cc3f959b83b0d3f1ac68f/lib/browser/guest-window-manager.ts#L219-L222

2022-06-13 17:38 UTC, miniak commented
@nornagon can we still add the warning in Electron 20 to be able to land the removal in Electron 21?

2022-06-13 17:40 UTC, nornagon commented
@miniak I'm not necessarily against that, but it's been deprecated for over a year now so I'm not sure waiting one more version to delete it is that bad? Is there any rush?

2022-06-13 19:08 UTC, samuelmaddock commented
Adding a deprecation log and waiting seems like the correct approach. We may not be considering a certain use case and users can voice their concern prior to removal if they notice the deprecation.

If we can afford it, maybe waiting 2 versions would be worthwhile since not everyone upgrades to the latest version.

2022-06-13 19:33 UTC, miniak commented
@samuelmaddock the question was mainly whether to do warning in E21 and then remove in E22, or already warn in E20 and remote in E21. We can also warn in E20 and remove in E22.

2022-06-14 15:15 UTC, samuelmaddock commented
> We can also warn in E20 and remove in E22.

This sounds best to me to give folks upgrading ample time.

2022-08-08 14:00 UTC, jkleinsc approved these changes
API LGTM

2022-08-08 16:09 UTC, nornagon approved these changes

2022-08-08 16:09 UTC, nornagon commented
API LGTM

2022-08-09 00:09 UTC, zcbenz approved these changes
API LGTM

2022-08-09 21:57 UTC, merged

2022-09-26 22:23 UTC, stefansundin commented on docs/breaking-changes.md
> +## Planned Breaking API Changes (22.0)
This should say `21.0` and not `22.0` right?