docs: add separate linkable browser-window-options.md and web-preferences.md
electron/electron pull request #34633
Opened 2022-06-19 23:04 UTC by miniak

#### Description of Change
`BrowserWindowOptions` and `WebPreferences` are used in multiple places.

#### Checklist
- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] relevant documentation is changed or added

#### Release Notes
Notes: none

2022-06-21 03:31 UTC, dsanders11 submitted a review, later dismissed
I'm also mostly 👍 on this as I've considered the same change before when in the docs, so that's several of us now that have been inclined to make this change.

But I do understand the concerns about the docs being a bit more cumbersome as a result. 🤔 For context, I believe [these are the past comments](https://github.com/electron/electron/pull/23054#discussion_r406388437) that @zcbenz is referencing.

I think that's less of a concern on the current docs website (which wasn't the case when those comments were originally made) since now when you hover over a linked structure, it shows you the details. Although that won't alleviate the concern about `WebPreferences` being not immediately visible on the `BrowserWindow` page since I don't think you can hover in the hove. I think the current docs implementation also gives us more freedom to potentially inline the structure as well if we wanted, so I think there are options.

I'm throwing a "request changes" on this just because there are a handful of broken reference-style links as a result of the changes. Unfortunately the docs linker doesn't catch that they're broken.

2022-06-21 03:31 UTC, dsanders11 commented on docs/api/window-open.md
> +A subset of [WebPreferences](structures/web-preferences.md) can be set directly,
```suggestion
A subset of [`WebPreferences`](structures/web-preferences.md) can be set directly,
```

nit: I think this should keep the backticks.

2022-06-21 03:31 UTC, dsanders11 commented on docs/api/window-open.md
> +the browser. Electron will parse [BrowserWindowConstructorOptions](structures/browser-window-options.md) out of this
```suggestion
the browser. Electron will parse [`BrowserWindowConstructorOptions`](structures/browser-window-options.md) out of this
```

nit: I think this should keep the backticks.

2022-06-21 03:31 UTC, dsanders11 commented on docs/api/window-open.md
> +* When opening `about:blank`, the child window's [WebPreferences](structures/web-preferences.md) will be copied
```suggestion
* When opening `about:blank`, the child window's [`WebPreferences`](structures/web-preferences.md) will be copied
```

nit: I think this should keep the backticks.

2022-06-21 03:31 UTC, dsanders11 commented on docs/api/window-open.md
> +the window and setting the [BrowserWindowConstructorOptions](structures/browser-window-options.md) to be used when
```suggestion
the window and setting the [`BrowserWindowConstructorOptions`](structures/browser-window-options.md) to be used when
```

nit: I think this should keep the backticks.

2022-06-21 03:31 UTC, dsanders11 commented on docs/api/app.md
> +Enables full sandbox mode on the app. This means that all renderers will be launched sandboxed, regardless of the value of the `sandbox` flag in [WebPreferences](structures/web-preferences.md).
```suggestion
Enables full sandbox mode on the app. This means that all renderers will be launched sandboxed, regardless of the value of the `sandbox` flag in [`WebPreferences`](structures/web-preferences.md).
```

nit: Let's add backticks here while we're at it.

2022-06-21 03:31 UTC, dsanders11 commented on docs/api/structures/browser-window-options.md
> +* `titleBarOverlay` Object | Boolean (optional) -  When using a frameless window in conjunction with `win.setWindowButtonVisibility(true)` on macOS or using a `titleBarStyle` so that the standard win
There are some broken links in here, like `[JavaScript APIs][overlay-javascript-apis]`.

2023-02-24 22:45 UTC, miniak commented
@dsanders11 should I rebase this one? Does it have a chance being merged?

2023-02-24 23:00 UTC, erickzhao commented
I think we want to make some docs-related changes to make this ultimately more readable on the website cc @nornagon

2023-02-24 23:02 UTC, dsanders11 commented
> Does it have a chance being merged?

But, to expand on @erickzhao's comment, I think the answer to this is yes. Consensus seemed to be reached on we're happy to merge this if we can tweak the website to better handle the UX in the published docs.

2023-02-24 23:04 UTC, miniak commented
rebased and linting issues fixed

2023-02-28 11:17 UTC, codebytere approved these changes

2023-02-28 14:18 UTC, dsanders11 requested changes
Putting a change on this to prevent merge only because we want to make a change to how it's displayed on the website for UX:

* Ability to inline the structure, for example in `docs/api/browser-window.md` so that users don't have to click through
* Ability to disable the hover card on a structure on the website, so that a very large structure like this one doesn't cause problems

Current plan is to extend the website code to handle special URL queries for this behavior, e.g. `?inline=true` or `?hover=false`,  and I'll try to get a PR up on `electron/website` for that by EOW, or I'll clear this request changes.

Thanks for the patience on this one @miniak.

2023-04-18 23:25 UTC, dsanders11 reviewed
Website changes have landed, we should be good to go now. @miniak, could you grab the changes in 5522d5e124afa1ffe402fe8cc8b2f59ff497209c and add them to this PR so that inlining will happen for the website? Once that's done we're good to merge. 👍

2023-04-20 12:04 UTC, miniak commented
@dsanders11 done

2023-04-20 12:44 UTC, dsanders11 approved these changes

2023-04-25 13:16 UTC, merged