Avoid stringifying the error
electron/electron pull request #35183
Opened 2022-08-02 15:17 UTC by raphaelbadia

Stringifying the error makes it impossible to return a proper error when the handler fails.
So in the UI we can only say "it worked" or "it didn't work", unless we parse the error.

It would be more useful to get the error fully to display understandable error messages in the UI.

#### Description of Change

#### Checklist

- [ ] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/main/docs/development/testing.md)
- [ ] relevant documentation is changed or added
- [ ] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes:

2022-08-02 18:58 UTC, MarshallOfSound commented on lib/renderer/ipc-renderer-internal.ts
> +    throw error;
```suggestion
    throw new AggregateError([new Error(`Error invoking remote method '${channel}'`), error]);
```

JS has built-in primitives for this kind of thing, we should retain the "channel" context

2022-08-02 22:02 UTC, miniak commented
@nornagon please check, I think you added this code

2022-08-02 22:09 UTC, nornagon requested changes
the `error` returned from `ipc.invoke` is a string, from here: https://github.com/electron/electron/blob/3fe00d75e9499ed9f55754548358e10385ab169e/lib/browser/api/web-contents.ts#L576

so no information is being lost.

2022-08-03 13:47 UTC, raphaelbadia commented
@nornagon how could I access this error from the renderer then ? Currently in my renderer I do something like this : 

```
window.auth
    .login(values.email, values.password)
    .catch((error) => {
        const realErrorString = error.substring(errorMessage.indexOf(':') + 2); // to drop the `Error invoking remote method '${channel}': 
.........
```

2022-08-25 07:19 UTC, zcbenz commented
I'm closing this PR since stringifying the error does not fix the issue as mentioned above.

2022-08-25 07:19 UTC, closed without merging