fix: undefined details.requestingUrl from session.setPermissionCheckHandler
electron/electron pull request #35281
Opened 2022-08-09 11:44 UTC by deepak1556

#### Description of Change

With https://github.com/electron/electron/commit/7e59d784a0b5c922564cbc8c55f95f0e7daf6997, https://chromium-review.googlesource.com/c/chromium/src/+/3495142 deprecates `GetPermissionStatusForFrame` in favor of `GetPermissionStatusForCurrentDocument` and the latter always called into `GetPermissionStatus` which does not have a frame context leading to empty `RenderFrameHost` causing the above issue. 

The CL also changes the backend for `WebFrameMain::ExecuteJavaScript` to use the version that allows resolving promises before returning the result. Not sure why the previous version which does not support promises https://source.chromium.org/chromium/chromium/src/+/main:content/browser/renderer_host/render_frame_host_impl.cc;l=2667-2670 was adopted in https://github.com/electron/electron/commit/704d69a8f96d904afc725f121432d23b7f44bd33

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] tests are [changed or added](https://github.com/electron/electron/blob/main/docs/development/testing.md)
- [ ] relevant documentation is changed or added
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: fix undefined details.requestingUrl from session.setPermissionCheckHandler

2022-08-09 23:53 UTC, miniak requested changes
I think the `WebFrameMain::ExecuteJavaScript` change should be a separate PR

2022-08-10 14:10 UTC, miniak approved these changes

2022-08-22 10:49 UTC, codebytere approved these changes

2022-08-23 01:25 UTC, zcbenz approved these changes

2022-08-23 01:25 UTC, merged