Use absolute URL in faq.md image link
electron/electron pull request #35413
Opened 2022-08-23 02:35 UTC by apetresc

#### Description of Change

The relative link is rendered relative to the host domain, which works fine when viewing it on Github, but since you also use the same generated HTML in your doc site, the link is broken. See here: https://www.electronjs.org/docs/latest/faq#the-font-looks-blurry-what-is-this-and-what-can-i-do

Using an absolute URL here should fix the issue on the main site.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] tests are [changed or added](https://github.com/electron/electron/blob/main/docs/development/testing.md)
- [x] relevant documentation is changed or added
- [ ] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes:

2022-08-25 08:32 UTC, codebytere approved these changes

2022-08-25 08:32 UTC, codebytere commented
@apetresc could you please push an empty commit to trigger the lint check?

2022-08-25 13:58 UTC, apetresc commented
Done! (The Appveyor build failures seem totally unrelated to the change 🤔)

2022-08-25 20:21 UTC, erickzhao approved these changes

2022-08-29 08:01 UTC, zcbenz commented
@apetresc Can you rebase this PR on latest `main`? It should be able to fix the CI failure.

2022-08-30 10:41 UTC, zcbenz approved these changes

2022-08-31 11:15 UTC, apetresc commented
Thanks for doing the rebase for me - I'm travelling at the moment without my laptop until tomorrow.

2022-09-05 02:19 UTC, dsanders11 requested changes
I don't think this is the right approach to fixing this broken image link. All image links in the docs are relative links, they're transformed by Docusaurus (I believe, @erickzhao correct me if I'm wrong) to point to the correct asset paths (which include hashes). Changing this to an absolute link sidesteps that process.

My guess would be Docusaurus isn't transforming the image path correctly due to this case using a reference-style link, or because it's using the simplified syntax style (`![]` rather than `![][]`) - there might be a bug in Docusaurus, or [our own code which fixes up links](https://github.com/electron/electronjs.org-new/blob/5a71030852111e1bd7f31a445d56382b7966baf8/scripts/tasks/md-fixers.js#L143).

I think changing this to an inline link would fix the issue and ensure the image goes through the same asset processing as the other images in the docs.

2022-09-05 14:07 UTC, apetresc commented
That makes sense, thanks @dsanders11. I'm not sure what the underlying Docusaurus problem is that causes the reference-style link to fail to be transformed properly, but if switching to an inline link works, that's good (and it seems like that's the likely culprit since other relative inline image links in other tutorial pages render fine in the HTML site).

So, I've updated this patch to do just that 🙂

2022-09-06 06:52 UTC, dsanders11 approved these changes

2022-09-06 13:21 UTC, apetresc commented
Should I try rebasing again to resolve the appveyor build failures?

2022-09-10 23:37 UTC, dsanders11 commented
> Should I try rebasing again to resolve the appveyor build failures?

@apetresc, you can rebase or push an empty commit.

2022-09-11 23:43 UTC, apetresc commented
@dsanders11 Looks like appveyor finally passed now but the Semver job is hanging because the PR somehow ended up with multiple semver labels. Is that something you have permission to fix?

2022-09-12 22:51 UTC, apetresc commented
Yaaay it finally passed all the checks :confetti_ball:  :partying_face: :confetti_ball:

2022-09-12 23:09 UTC, merged