chore: add warnings for deprecated BrowserWindow methods
electron/electron pull request #35519
Opened 2022-08-31 09:23 UTC by miniak

#### Description of Change
Prepare for the removal of unnecessary forwarders.

#### Checklist
- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/main/docs/development/testing.md)
- [x] relevant documentation is changed or added
- [ ] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes
Notes: none

2022-08-31 22:07 UTC, nornagon requested changes
I don't think removing these APIs is worth the trouble.

2022-08-31 23:42 UTC, miniak commented
@nornagon does it make sense to keep the refactoring, which forwards all the listed methods in the for loop instead of writing the code manually?

2022-08-31 23:45 UTC, miniak commented
@nornagon also what about only deprecating the methods, which are not documented?

2022-08-31 23:57 UTC, nornagon commented
I'm fine with removing undocumented methods. We can do that without warning, generally speaking. As for auto-forwarding vs. listing the method names in an array, I think it's fine to keep them as straightforward functions without an array / automatic forwarding once the number is much smaller (4-5 or so).

2022-09-01 21:13 UTC, nornagon commented on docs/breaking-changes.md
> +* `browserWindow.capturePage`
Actually having thought about it, I'm ok with these three being deprecated and removed. loadURL/loadFile should stay though.

2022-09-05 08:09 UTC, codebytere reviewed
Was there some form of discussion about removing these methods in a future version? While i'm ok with removing the undocumented ones, these were largely here for convenience, which they provided. I don't think that having this type of duplication is inherently a negative unless there's an active negative consequence to their being there, which is not the case here that I am aware.

2023-06-06 18:50 UTC, closed without merging