fix: virtual keyboard overlaps input in webview
electron/electron pull request #35527
Opened 2022-08-31 17:28 UTC by kyrylo-hrechykhin

#### Description of Change

Patch in this PR fixes issue described in the issue #35470

The problem is happening only with <webview> tags. The issue is happening due to lack of communication between VirtualKeyboardControllerWin (content/browser/renderer_host/virtual_keyboard_controller_win.h/cc) and RenderWidgetHostViewChildFrame (content/browser/renderer_host/render_widget_host_view_child_frame.h/cc). 

VirtualKeyboardControllerWin is responsible for showing/hiding virtual keyboard and for notifying about virtual keyboard showed/hidden. It is stored in RenderWidgetHostViewAura.
RenderWidgetHostViewChildFrame is responsible for controlling webview's view. It does not have access to VirtualKeyboardControllerWin instance. Notification from it does not affect RenderWidgetHostViewChildFrame.

This patch adds new one singleton instance VirtualKeyboardNotifier to indirectly connect VirtualKeyboardControllerWin instance and all RenderWidgetHostViewChildFrame instances. This notifier will notify when virtual keyboard show/hide.

CC: @miniak @deepak1556 
Please feel free to mention anyone who can review this.

#### Checklist
- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes. Well, the same number of tests passed as in main branch.

2022-08-31 17:36 UTC, nornagon requested changes
This is quite a significant patch. Per our [patch policy](https://github.com/electron/electron/blob/main/docs/development/patches.md#patch-justification), we should try to either upstream this or substantially reduce the size of the patch.

2022-08-31 18:27 UTC, miniak commented
moving the `VirtualKeyboardNotifier` files to src/electron would decrease the patch size :)

2022-09-01 12:20 UTC, kyrylo-hrechykhin commented
@nornagon , @miniak , please take a look again.
I made the patch smaller by moving VirtualKeyboardNotifier out of it.

2022-09-01 17:17 UTC, deepak1556 commented
Given the guest webcontents `RenderWidgetHostView` is `RenderWidgetHostViewChildFrame` and `VirtualKeyboardControllerWin` is managed by `RenderWidgetHostViewAura`, which class is responsible for triggering the virtual keyboard in the `<webview>` scenario ? Specifically this call https://source.chromium.org/chromium/chromium/src/+/main:content/browser/renderer_host/virtual_keyboard_controller_win.cc;l=94-140

Is it the `RenderWidgetHostViewAura` of the embedding frame ? If that is the case, would this patch now adjust `<webview>` insets even when the keyboard is triggered from embedding frame's input box ?

2022-09-02 10:29 UTC, zcbenz reviewed
It seems that every RenderWidgetHostViewChildFrame is subscribed to the notifier, does this code work with multiple webview/iframes?

2022-09-02 12:04 UTC, kyrylo-hrechykhin commented
> Given the guest webcontents `RenderWidgetHostView` is `RenderWidgetHostViewChildFrame` and `VirtualKeyboardControllerWin` is managed by `RenderWidgetHostViewAura`, which class is responsible for triggering the virtual keyboard in the `<webview>` scenario ? Specifically this call https://source.chromium.org/chromium/chromium/src/+/main:content/browser/renderer_host/virtual_keyboard_controller_win.cc;l=94-140
> 
> Is it the `RenderWidgetHostViewAura` of the embedding frame ? If that is the case, would this patch now adjust `<webview>` insets even when the keyboard is triggered from embedding frame's input box ?

Virtual keyboard is triggered by `RenderWidgetHostViewAura` in the `<webview>` scenario. `RenderWidgetHostViewChildFrame` is not connected to `VirtualKeyboardControllerWin` at all except this notifier.

2022-09-02 12:07 UTC, kyrylo-hrechykhin commented
I tested the fix with more than one webviews and I got quite unexpected results. Please see the video.

It looks like SetInsets for webview depends on currently focused component. Each webview component has its own focused component, that is why we can see how it lifts up or stays still depending on focused input.

https://user-images.githubusercontent.com/71867931/188139189-047aa9b3-e2df-4528-a792-b175a1344fd6.mp4

2022-09-06 06:42 UTC, zcbenz commented
@kyrylo-hrechykhin The webview is essentially a special iframe which connects to a remote WebContents, if a thing works in iframe but not in webview, it is usually because there is a mistake in Chromium that a message is only handled for local WebContents but not for remote WebContents. (For example this patch https://github.com/electron/electron/blob/main/patches/chromium/webview_fullscreen.patch)

So for this issue, can you check if both webview and iframe are using `RenderWidgetHostViewChildFrame` for their view? And whether `VirtualKeyboardControllerWin` has been created for both webview and iframe? If webview and iframe have the same classes attached then I think the root problem is not in these classes.

2022-09-22 15:54 UTC, kyrylo-hrechykhin commented
@zcbenz , thanks for the comment.
Well, callstack for webview and iframe is absolutely the same in terms of lifting up the view on OSK show. This is the description of callstacks:

![image](https://user-images.githubusercontent.com/71867931/191791635-bcdd097f-bb2f-4447-aab6-f9d7a068b76d.png)

The only thing that is different here is output on this line: https://chromium.googlesource.com/chromium/src/+/656b12e738db869fd07b9f8edc78bd2f57a014cc/third_party/blink/renderer/core/exported/web_view_impl.cc#2167

For webview VisualContentRect is not smaller on size of OSK. It looks like insets of RenderWidgetHostViews are taken into account in here.

VirtualKeyboardControllerWin is not connected to RenderWidgetHostViewChildFrame at all. I also did not get proves that RenderWidgetHostViewChildFrame is used in case of <iframe> at all.

I also would like to suggest prioritizing this issue (#35470) and involve more people to it. All users of touch devices are affected by it. UX is ruined as long as application uses <webview> and user has touch device.

2025-06-30 10:21 UTC, codebytere commented
Closing due to inactivity - we can re-open if there is more or this is still needed.

2025-06-30 10:21 UTC, closed without merging