fix: add ignore method to IncomingMessage
electron/electron pull request #35767
Opened 2022-09-22 10:24 UTC by kyrylo-hrechykhin

#### Description of Change

That method makes possible to indicate that response is ignored, and all data chunks should be dropped. Otherwise, response data should be read. If response data is not read and is not ignored, memory leak will happen per each net.request call in browser process.

CC: @VerteDinde 

#### Checklist
- [x] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [x] relevant documentation is changed or added
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: Method ignore() is added to IncomingMessage in order to prevent memory leaks in browser process when data is not read.

2022-09-22 16:45 UTC, VerteDinde commented
@kyrylo-hrechykhin Thanks for the PR! Since this is a new method, would it be possible to add a test or two for it, just to make sure we can catch it in the future if it regresses?

2022-09-26 08:28 UTC, codebytere requested changes
if my understanding is correct, the changes in https://github.com/electron/electron/pull/25531 made it such that memory leaks now happen more easily/by default unless the user utilizes the API added in this PR?

If that's the case, I'd really like to try to see if there's an alternate solution that allows for us to fix this problem without creating a new, potentially unintuitive API which users must use to _prevent_ the leaks. It's not that i'm against the API design per se, but rather I think that adding new API to address what is arguably a bug is probably not the most effective solution.

2022-09-26 08:28 UTC, codebytere commented on docs/api/incoming-message.md
> +Otherwise it will lead to memory leaks in browser process ([#34158](https://github.com/electron/electron/issues/34158)).
We don't want to link to bugs in our documentation I wouldn't say.

2022-09-26 08:52 UTC, kyrylo-hrechykhin commented
> if my understanding is correct, the changes in #25531 made it such that memory leaks now happen more easily/by default unless the user utilizes the API added in this PR?
> 
> If that's the case, I'd really like to try to see if there's an alternate solution that allows for us to fix this problem without creating a new, potentially unintuitive API which users must use to _prevent_ the leaks. It's not that i'm against the API design per se, but rather I think that adding new API to address what is arguably a bug is probably not the most effective solution.

Thanks for the comment. Absolutely agree that it is better to fix it properly rather than modify API in order to avoid memory leaks. I did not find solution that will be better in this case when I created this PR. I will check if it is possible to pin body chunk getter on first resume callback call. It will indicate that response is being read.

2022-09-26 23:08 UTC, nornagon commented
Could we use a [FinalizationRegistry](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/FinalizationRegistry) to watch for GC? Or hook the destructor on the C++ side?

2024-02-06 10:02 UTC, codebytere commented
@kyrylo-hrechykhin would you still like to see this move forward?

2024-11-04 17:58 UTC, samuelmaddock commented
I'm closing this PR due to staleness. Please feel free to reopen if there's renewed interest in continuing this work! 🙇

2024-11-04 17:58 UTC, closed without merging