docs: update breaking changes for v21
electron/electron pull request #35820
Opened 2022-09-26 17:23 UTC by clavin

#### Description of Change

Updates the breaking changes doc to properly attribute two changes to the correct release.

Previously, two changes were listed as breaking in Electron 20 but were not part of that release. Instead, they're landing in Electron 21. This documentation change clears this up.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] relevant documentation is changed or added
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: none

2022-09-26 17:41 UTC, VerteDinde approved these changes

2022-09-26 19:21 UTC, jkleinsc approved these changes

2022-09-26 21:34 UTC, MarshallOfSound approved these changes

2022-09-26 22:27 UTC, miniak requested changes
common.gypi in Electron 20 already contains
`V8_COMPRESS_POINTERS_IN_SHARED_CAGE` and `V8_SANDBOXED_POINTERS`

2022-09-27 15:58 UTC, jkleinsc commented
@miniak the flags are there, but we explicitly set 
`v8_enable_sandboxed_pointers = false` in our args for 20-x-y: https://github.com/electron/electron/blob/20-x-y/build/args/all.gn#L49

2022-09-28 00:32 UTC, miniak approved these changes

2022-09-28 00:36 UTC, miniak commented
@jkleinsc how did that happen however. The https://www.electronjs.org/blog/v8-memory-cage post said this change was done in Electron 20 at the time this version was released

2022-09-28 16:47 UTC, merged