build: set Electron Framework dylib version
electron/electron pull request #35862
Opened 2022-09-29 15:01 UTC by zowers

#### Description of Change
set current_version dylib version so it's available in crash dumps instead of zeros.

Current version is stored in LC_ID_DYLIB load command, can be checked with:
otool -l Electron\ Framework.framework/Electron\ Framework | grep -A5 LC_ID_DYLIB

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: macOS: Set Electron Framework dylib version so it's available in crash dumps instead of zeros.

2022-09-30 20:04 UTC, MarshallOfSound requested changes
Hm, this leaves out prerelease information.  I wonder if there's a nice way to encode that information into these numbers instead of just dropping it

2022-10-03 10:24 UTC, zowers commented
> How to show negative nature of prerelease component also not apparent, probably by substracting from 256, e.g.

or better be sortable and use positive numbers and differentiate non-prerelase builds by some high number, e.g.
> ```js
> Z = prerelease == 0 ? 100 : prerelease;
> ```

2022-10-09 15:28 UTC, zowers commented
@MarshallOfSound what do you think about my suggestions regarding how to resolve your comment? are they good or not?

2022-10-18 14:29 UTC, zowers commented
@MarshallOfSound did you have time to look at it?

2022-11-08 11:30 UTC, zowers commented
will return to it in near future

2022-11-08 15:20 UTC, codebytere commented
@zowers do you mind if i convert it to a draft?

2023-10-30 11:24 UTC, codebytere commented
Closing as this has had no activity for over a year. Happy to re-open if there's renewed interest!

2023-10-30 11:24 UTC, closed without merging