test: add tests for valid electron module names
electron/electron pull request #35931
Opened 2022-10-06 12:21 UTC by RaisinTen

#### Description of Change

https://github.com/electron/electron/pull/35915 landed without any tests, so this change adds some. This also documents why these variations exist. I admit, it isn't the best place for documenting such a thing because it's not very accessible but I don't know what the best place is either, so suggestions welcome!

Signed-off-by: Darshan Sen <raisinten@gmail.com>

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] tests are [changed or added](https://github.com/electron/electron/blob/main/docs/development/testing.md)
- [x] relevant documentation is changed or added

#### Release Notes

Notes: none 

cc @MarshallOfSound

2022-10-06 12:48 UTC, codebytere approved these changes

2022-10-06 13:12 UTC, RaisinTen commented on lib/common/reset-search-paths.ts
> +// work everywhere, they're superficial for TypeScript only.
@codebytere this is basically a copy-paste of Samuel's comment regarding what `electron/main`, `electron/common` and `electron/renderer` are for - https://github.com/electron/electron/pull/35915#issuecomment-1269893433

2022-10-06 13:31 UTC, RaisinTen commented on lib/common/reset-search-paths.ts
> +// work everywhere, they're superficial for TypeScript only.
@codebytere I have rephrased the comment, does it look better now?

2022-10-06 14:23 UTC, jkleinsc approved these changes

2022-10-06 16:05 UTC, codebytere commented on lib/common/reset-search-paths.ts
> +// work everywhere, they're superficial for TypeScript only.
looks great - thanks!

2022-10-10 10:11 UTC, miniak requested changes
I think we should do this fist https://github.com/electron/electron/pull/35959

2022-10-10 19:56 UTC, miniak approved these changes

2022-10-11 06:59 UTC, merged