fix: ensure autofill popup view is > 1x1 in size
electron/electron pull request #36121
Opened 2022-10-24 21:26 UTC by nornagon

#### Description of Change
Fixes #26667

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes

#### Release Notes

Notes: none

2022-10-25 06:13 UTC, codebytere submitted a review, later dismissed

2022-10-25 10:49 UTC, zcbenz approved these changes

2022-10-25 10:57 UTC, zcbenz requested changes

2022-10-25 10:57 UTC, zcbenz commented on shell/browser/ui/views/autofill_popup_view.cc
> +      gfx::Rect(popup_->popup_bounds_.origin(), gfx::Size(1, 1))));
If `popup_->popup_bounds_` could be empty, then so would be `popup_->popup_bounds_in_view()`, which is used in some other places.

2022-10-25 10:58 UTC, zcbenz commented
It was also mentioned in https://github.com/electron/electron/issues/26667 that passing zero size to `BrowserWindow` could cause the same problem.

2023-01-25 15:25 UTC, codebytere commented on shell/browser/ui/views/autofill_popup_view.cc
> +      gfx::Rect(popup_->popup_bounds_.origin(), gfx::Size(1, 1))));
```suggestion
  // Clamp popup_bounds_ to ensure it's never zero-width.
  popup_->popup_bounds_.Union(
      gfx::Rect(popup_->popup_bounds_.origin(), gfx::Size(1, 1)));
  GetWidget()->SetBounds(popup_->popup_bounds_);
```

2023-01-26 23:54 UTC, zcbenz approved these changes

2023-01-27 09:50 UTC, merged