build: determine electron version from tags not files
electron/electron pull request #36136
Opened 2022-10-26 03:59 UTC by VerteDinde

Manual backport of https://github.com/electron/electron/pull/36106

See that PR for details.

Notes: no-notes

2022-10-26 14:41 UTC, jkleinsc requested changes
Requesting changes until we get the main branch/nightly releases sorted out.

2022-10-26 14:41 UTC, VerteDinde commented
Moving this to draft until after nightly is fixed/stable releases are kicked off

2022-10-27 03:24 UTC, VerteDinde commented
Updated with latest working changes

2022-10-28 19:12 UTC, MarshallOfSound approved these changes

2022-10-30 22:37 UTC, merged