fix: fixed crash when BrowserView with destroyed webcontents is reused
electron/electron pull request #36414
Opened 2022-11-20 15:58 UTC by CezaryKulakowski

Fixed #36371.

#### Description of Change

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: fixed crash when BrowserView with destroyed webcontents is reused

2022-11-21 11:45 UTC, codebytere requested changes
Please add a regression test to this! Additionally - this does prevent a full crash but what also seems to be happening is that the `BrowserView` webContents is being destroyed when maybe it shouldn't be. This is happening as a result of https://github.com/electron/electron/pull/35509 - specifically [this change](https://github.com/electron/electron/pull/35509/files#diff-261075c0abf5bfd33be70313bcd3699da9b1222b6f27df0e8294fc63789f160bR1213) cc @nornagon

2022-11-21 12:27 UTC, CezaryKulakowski commented
I've pushed fixup with test. It crashes without this fix.

2022-11-21 22:32 UTC, nornagon commented
Thanks for the new test, pulled the test into https://github.com/electron/electron/pull/35658, which threw a JS exception in this case, which is now fixed.

This PR will be obsoleted if #35658 lands.

2023-08-15 08:46 UTC, codebytere commented
Handled in https://github.com/electron/electron/pull/37420 - apologies for not getting to this sooner before i realized it.

2023-08-15 08:46 UTC, closed without merging