todo : replace GetNativeHandle() with GetAcceleratedWidget()
electron/electron pull request #36697
Opened 2022-12-18 10:42 UTC by Aman1919

#### Description of Change

Replaced GetNativeHandle() with GetAcceleratedWidget()

#### Checklist

- [ ] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/main/docs/development/testing.md)
- [ ] relevant documentation, tutorials, templates and examples are changed or added
- [ ] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes:

2022-12-19 18:37 UTC, nornagon requested changes
I'm not sure this is correct?

https://github.com/electron/electron/blob/5fd7a43970c2bdfa1017a4b23098aec3dafbf513/shell/browser/native_window_mac.mm#L1207-L1208

this would make `GetNativeWindowHandle` return the window number instead of the `contentView`, which would break anything using the native window handle.

2022-12-20 11:34 UTC, Aman1919 commented
so  instead of returning [window _windowNumber ] . [window _contentView ] should be returned ?

2022-12-20 18:07 UTC, nornagon commented
@Aman1919 that will almost certainly break other things.

Can you help me understand why you want to make this change?

2022-12-21 12:36 UTC, Aman1919 commented
to restore the older implementation 
https://github.com/electron/electron/pull/15521#issuecomment-436279372

2022-12-21 13:52 UTC, RaisinTen commented
Hey @nornagon, @Aman1919 reached out to me and he wanted to contribute to Electron, so we built Electron from source on his device and thought it would be pretty cool if we could solve this TODO as his first contribution.

As @Aman1919 pointed out, this change was originally added in https://github.com/electron/electron/pull/15521 and so we thought that reverting the GetNativeWindowHandle() change to use GetAcceleratedWidget() would be the right approach.

2022-12-21 21:35 UTC, nornagon commented
Looks like https://github.com/electron/electron/pull/15521#issuecomment-436279372 suggests you'll need to extract the window from the ID before passing it back to JS.

Just to be completely clear: _this refactor must not break apps currently using [win.getNativeWindowHandle()](https://www.electronjs.org/docs/latest/api/browser-window#wingetnativewindowhandle)_. As long as that function behaves identically to how it currently does, I'm OK with the refactor. Note that we do have one test for this function, and it is failing on macOS as expected: https://app.circleci.com/pipelines/github/electron/electron/61324/workflows/f521edcb-7a59-479d-81fa-3f852b50f1d7/jobs/1378097

2023-01-31 02:22 UTC, miniak requested changes

2023-01-31 02:22 UTC, miniak commented on shell/browser/native_window_mac.mm
> +
revert this

2023-01-31 02:22 UTC, miniak commented on shell/browser/native_window_views.h
> -
revert this

2023-02-06 04:59 UTC, RaisinTen commented
This test is failing and it means that the handle this is returning right now is invalid: https://app.circleci.com/pipelines/github/electron/electron/62665/workflows/8d5c3b65-45bd-4744-b330-09a72891cb02/jobs/1402677?invite=true#step-114-701
```
not ok 490 BrowserWindow module window.getNativeWindowHandle() returns valid handle
  AssertionError: is valid window: expected false to be true
      at Context.<anonymous> (electron/spec/api-browser-window-spec.ts:5184:66)
      at processImmediate (node:internal/timers:471:21)
```
@MarshallOfSound @deepak1556 could you also take a look because y'all have more context on https://github.com/electron/electron/pull/15521?

2023-04-15 11:50 UTC, closed without merging