feat: emit `devtools-open-in-new-tab` event for DevTools link selection
electron/electron pull request #36774
Opened 2023-01-02 14:31 UTC by codebytere

#### Description of Change

Closes https://github.com/electron/electron/issues/36715.

This PR adds a new event `devtools-open-in-new-tab` corresponding to a link in DevTools being either clicked or selected for opening in a new tab via context menu. There is precedent for event emission corresponding to `DevToolsEmbedderMessageDispatcher::Delegate` methods - this was previously a no-op and so the primary change here is adding an implementation to surface the action to developers.

Alternatively, we could potentially have implemented the new window behavior ourselves, but this is (imo) a large security hole and as such i would rather give developers more fine-grained control over handling and optionally opening new links there.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] relevant documentation, tutorials, templates and examples are changed or added
- [x] [PR release notes](https://github.com/electron/clerk/blob/main/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/main/README.md#examples).

#### Release Notes

Notes: Added a new `devtools-open-in-new-tab` event to `webContents` to allow developers to open new windows with them.

2023-01-03 20:46 UTC, nornagon requested changes
Chrome directs this through `Browser::OpenURL`: https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/devtools/devtools_ui_bindings.cc;l=196-201;drc=fd7b4c1844e6431a5ba4475eb515257a3a238a31

We have an `open-url` event on `app` already, but it seems to be only used on macOS, for when a user opens an app-registered URL. Oh well.

Let's call this `devtools-open-url` instead of `devtools-open-in-new-tab`.

2023-01-04 04:24 UTC, deepak1556 commented
Can we not just open the platform specific application to handle the URL https://github.com/electron/electron/blob/20cff642821cf9dc57b55fef4414fa0b010d329f/shell/common/platform_util.h#L33-L37 ? Is it necessary for applications to handle this event ?

2023-01-04 10:45 UTC, codebytere commented
@deepak1556 i considered that, but i think that allowing developers to decide for themselves is comparatively little effort and allows them to make a wider range of choices.

2023-01-17 20:22 UTC, jkleinsc approved these changes
API LGTM

2023-01-25 19:55 UTC, nornagon approved these changes
API LGTM

2023-01-25 22:34 UTC, ckerr approved these changes
API LGTM

2023-01-26 07:20 UTC, zcbenz approved these changes
API LGTM

2023-01-26 08:54 UTC, merged