build: remove older branch migration helpers
electron/electron pull request #36888
Opened 2023-01-11 15:15 UTC by codebytere

#### Description of Change

The main migration has been complete for some time, and so there are no longer any branches which might release off of master. Address TODOs and simplify code accordingly. There also aren't any branches that should take the `1-x-y` format any longer, so simplify that as well.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [x] [PR release notes](https://github.com/electron/clerk/blob/main/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/main/README.md#examples).

#### Release Notes

Notes: none

2023-01-11 21:13 UTC, dsanders11 commented
> There also aren't any branches that should take the 1-x-y format any longer, so simplify that as well.

I might be confused, but this seems inverted? Isn't the current release branch `23-x-y`? Versus an old branch like `6-1-x`.

2023-01-11 23:03 UTC, jkleinsc requested changes
As @dsanders11 mentioned this seems backwards.  Newer branches follow d-x-y not d-d-x.

2023-01-12 10:37 UTC, codebytere commented
yep - accident, fixed.

2023-01-12 15:27 UTC, jkleinsc approved these changes

2023-01-12 17:05 UTC, merged