fix: cookies filter secure and session invalid
electron/electron pull request #37203
Opened 2023-02-09 09:14 UTC by BlackHole1

#### Description of Change

Make the following code work:

```js
session.defaultSession.cookies.get({
  secure: true,
  session: true,
})
```

#### Checklist

- [ ] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/main/docs/development/testing.md)
- [ ] relevant documentation, tutorials, templates and examples are changed or added
- [ ] [PR release notes](https://github.com/electron/clerk/blob/main/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/main/README.md#examples).

#### Release Notes

Notes: none

2023-02-09 09:31 UTC, codebytere requested changes
Can you please describe the issue in more detail as well as properly fill out the PR template? Additionally, we should have some tests for this.

2023-02-09 09:55 UTC, BlackHole1 commented
> Can you please describe the issue in more detail as well as properly fill out the PR template? Additionally, we should have some tests for this.

@codebytere Updated. The whole file does not have any unit tests at the moment. And the change in this PR is very simple, it is just if logic is written wrong.

2023-02-09 16:42 UTC, BlackHole1 commented
@codebytere Description updated and already add tests.

2023-02-09 17:59 UTC, deepak1556 approved these changes

2023-02-09 17:59 UTC, deepak1556 commented on shell/browser/api/electron_api_cookies.cc
>    if (session_filter && *session_filter != !cookie.IsPersistent())
Maybe also switch this for simplicity

```suggestion
  if (session_filter && *session_filter == cookie.IsPersistent())
```

2023-02-09 18:00 UTC, deepak1556 commented
@BlackHole1 can you update the `Notes:` section with user facing release note since this is a bug fix.

2023-02-09 23:49 UTC, BlackHole1 commented
@deepak1556 Done. I updated the `notes` description.

2023-02-13 07:35 UTC, zcbenz approved these changes

2023-02-13 09:04 UTC, codebytere approved these changes

2023-02-13 14:02 UTC, merged