chore: correct extra qualification causing build error with GCC
electron/electron pull request #37548
Opened 2023-03-10 20:06 UTC by brjsp

#### Description of Change

[See it on godbolt](https://godbolt.org/z/WvYooTnff)

#### Release Notes

none

2023-03-13 15:17 UTC, jkleinsc requested changes
@brjsp thanks for the PR.  We should leave the namespace declaration in but remove the namespace qualifier from 
`struct base::ScopedObservationTraits<...`

2023-03-13 15:17 UTC, jkleinsc commented on shell/browser/hid/electron_hid_delegate.h
>  struct base::ScopedObservationTraits<
```suggestion
struct ScopedObservationTraits<
```

2023-03-13 15:17 UTC, jkleinsc commented on shell/browser/serial/electron_serial_delegate.h
>  struct base::ScopedObservationTraits<
```suggestion
struct ScopedObservationTraits<
```

2023-04-19 09:41 UTC, codebytere approved these changes

2023-04-24 14:12 UTC, jkleinsc approved these changes

2023-04-26 14:40 UTC, merged