feat: add powerMonitor.isSystemAutomaticallyResumed API
electron/electron pull request #37759
Opened 2023-03-29 22:15 UTC by MarshallOfSound

Direct expose of win32 API

Notes: Added new `powerMonitor.isSystemAutomaticallyResumed` API to check if the system was woken by user input

2023-03-30 17:15 UTC, nornagon requested changes
I feel like this is kind of an awkward API, it should rather be a parameter of the 'resume' event or something.

2023-03-30 17:15 UTC, nornagon commented on docs/api/power-monitor.md
> +Returns `boolean` - Whether the system was resumed automatically or due to user input.  This maps directly to the `IsSystemResumeAutomatic` win32 API.
Let's have an example about how this is supposed to be used.

2023-03-30 17:15 UTC, nornagon commented on docs/api/power-monitor.md
> +https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-issystemresumeautomatic
Give this link a title, please!

2023-04-04 08:29 UTC, zcbenz reviewed
I'm not sure if we should add rarely used win32 APIs to Electron's builtin APIs, writing a napi module or using node-ffi for this api is simple, but if we add it as a public Electron API, it could end up that only one app would be using it.

2023-06-13 20:30 UTC, closed without merging