docs: replace the example app using electron
electron/electron pull request #37805
Opened 2023-04-03 17:09 UTC by iamaliyousefi

#### Description of Change
[Atom editor](https://github.com/atom/atom) was used as an example of apps using Electron. Since [Atom editor has been archived](https://github.blog/2022-06-08-sunsetting-atom/) and is not maintained anymore, I replaced it with vscode as a more famous and live example of an app which uses Electron. 

#### Checklist

- [x ] PR description included and stakeholders cc'd

#### Release Notes

Notes: none

2023-04-04 00:07 UTC, MarshallOfSound submitted a review, later dismissed
Atom was here originally because Electron was made specifically out of Atom.

We should probably just remove it from this list and not replace it, the links to `/apps` is enough

cc @electron/wg-ecosystem

2023-04-04 13:14 UTC, aysabzevar commented
@MarshallOfSound  Thanks for your comment. I believe having a very well-known example of an app which used Electron is still beneficial.

2023-08-31 00:48 UTC, zcbenz commented
This PR needs some opinions from @electron/wg-ecosystem .

2023-08-31 04:47 UTC, erickzhao approved these changes
docs: LGTM

2023-09-27 15:04 UTC, jkleinsc requested changes
Needs a small change to pass lint (no trailing spaces allowed).

2023-10-05 14:35 UTC, iamaliyousefi reviewed
Remove the trailing space.

2023-10-05 14:35 UTC, iamaliyousefi commented on README.md
> +[Chromium](https://www.chromium.org) and is used by the [Visual Studio
Just removed the trailing space. Thanks again @jkleinsc  for the heads up.

2023-10-18 14:55 UTC, jkleinsc approved these changes

2023-10-18 14:56 UTC, merged