chore: fix clang-tidy warnings
electron/electron pull request #38079
Opened 2023-04-21 20:57 UTC by dsanders11

#### Description of Change

Fixes the current warnings from `clang-tidy`, other than `modernize-use-nullptr` which I'm disabling for now as there's too much noise.  There's a couple false positives I had to silence with `// NOLINT`.

The goal is to add a `clang-tidy` CI job, but that will be done in a future PR.

For completeness, here is the `clang-tidy` output without the fixes:

<details><summary>Warnings</summary>

```
../../electron/shell/common/gin_helper/trackable_object.cc:24:3: warning: 'operator int' must be marked explicit to avoid unintentional implicit conversions [google-explicit-constructor]
  operator int32_t() const { return id_; }
  ^
  explicit 

../../electron/shell/browser/api/electron_api_desktop_capturer.cc:246:35: warning: unnecessary temporary object created while calling emplace_back [modernize-use-emplace]
      window_sources.emplace_back(DesktopCapturer::Source{
                                  ^~~~~~~~~~~~~~~~~~~~~~~~
../../electron/shell/browser/api/electron_api_desktop_capturer.cc:260:11: warning: unnecessary temporary object created while calling emplace_back [modernize-use-emplace]
          DesktopCapturer::Source{list->GetSource(i), std::string()});
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

../../electron/shell/browser/ui/webui/accessibility_ui.cc:155:23: warning: use emplace_back instead of push_back [modernize-use-emplace]
    property_filters->push_back(ui::AXPropertyFilter(attribute, type));
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~               ~
                      emplace_back(
../../electron/shell/browser/usb/usb_chooser_context_factory.cc:18:27: warning: use '= default' to define a trivial destructor [modernize-use-equals-default]
UsbChooserContextFactory::~UsbChooserContextFactory() {}
                          ^                           ~~
                                                      = default;
../../electron/shell/browser/usb/usb_chooser_controller.cc:57:15: warning: argument name 'device' in comment does not match parameter name 'device_info' [bugprone-argument-comment]
  RunCallback(/*device=*/nullptr);
              ^
../../electron/shell/browser/usb/usb_chooser_controller.h:61:52: note: 'device_info' declared here
  void RunCallback(device::mojom::UsbDeviceInfoPtr device_info);
                                                   ^
../../electron/shell/browser/usb/usb_chooser_controller.cc:88:17: warning: argument name 'device' in comment does not match parameter name 'device_info' [bugprone-argument-comment]
    RunCallback(/*device=*/nullptr);
                ^
../../electron/shell/browser/usb/usb_chooser_controller.h:61:52: note: 'device_info' declared here
  void RunCallback(device::mojom::UsbDeviceInfoPtr device_info);
                                                   ^
../../electron/shell/browser/usb/usb_chooser_controller.cc:98:19: warning: argument name 'device' in comment does not match parameter name 'device_info' [bugprone-argument-comment]
      RunCallback(/*device=*/nullptr);
                  ^
../../electron/shell/browser/usb/usb_chooser_controller.h:61:52: note: 'device_info' declared here
  void RunCallback(device::mojom::UsbDeviceInfoPtr device_info);
                                                   ^
../../electron/shell/browser/usb/usb_chooser_controller.cc:134:17: warning: argument name 'port' in comment does not match parameter name 'device_info' [bugprone-argument-comment]
    RunCallback(/*port=*/nullptr);
                ^
../../electron/shell/browser/usb/usb_chooser_controller.h:61:52: note: 'device_info' declared here
  void RunCallback(device::mojom::UsbDeviceInfoPtr device_info);
                                                   ^

../../electron/shell/browser/api/electron_api_utility_process.cc:282:12: warning: converting integer literal to bool, use bool literal instead [modernize-use-bool-literals]
    return 0;
           ^
           false

../../electron/shell/browser/api/electron_api_system_preferences_mac.mm:465:45: warning: 'p' used after it was moved [bugprone-use-after-move]
                                  std::move(p), std::move(err_msg)));
                                            ^
../../electron/shell/browser/api/electron_api_system_preferences_mac.mm:469:31: note: move occurred here
                              base::BindOnce(
                              ^
../../electron/shell/browser/api/electron_api_system_preferences_mac.mm:465:45: note: the use and move are unsequenced, i.e. there is no guarantee about the order in which they are evaluated
                                  std::move(p), std::move(err_msg)));
                                            ^
../../electron/shell/browser/api/electron_api_system_preferences_mac.mm:471:45: warning: 'p' used after it was moved [bugprone-use-after-move]
                                  std::move(p)));
                                            ^
../../electron/shell/browser/api/electron_api_system_preferences_mac.mm:463:31: note: move occurred here
                              base::BindOnce(
                              ^
../../electron/shell/browser/api/electron_api_system_preferences_mac.mm:471:45: note: the use and move are unsequenced, i.e. there is no guarantee about the order in which they are evaluated
                                  std::move(p)));
                                            ^
../../electron/shell/browser/ui/file_dialog_mac.mm:286:14: warning: use emplace_back instead of push_back [modernize-use-emplace]
      paths->push_back(base::FilePath(base::SysNSStringToUTF8([url path])));
             ^~~~~~~~~~~~~~~~~~~~~~~~~                                   ~
             emplace_back(
../../electron/shell/renderer/electron_autofill_agent.cc:49:15: warning: use emplace_back instead of push_back [modernize-use-emplace]
      labels->push_back(std::u16string());
              ^~~~~~~~~~~~~~~~~~~~~~~~~~
              emplace_back(

../../electron/shell/browser/api/gpu_info_enumerator.cc:11:42: warning: initializer for member 'value_stack_' is redundant [readability-redundant-member-init]
GPUInfoEnumerator::GPUInfoEnumerator() : value_stack_(), current_{} {}
                                         ^~~~~~~~~~~~~~
../../electron/shell/browser/api/gpu_info_enumerator.cc:11:58: warning: initializer for member 'current_' is redundant [readability-redundant-member-init]
GPUInfoEnumerator::GPUInfoEnumerator() : value_stack_(), current_{} {}
                                                         ^~~~~~~~~~~
../../electron/shell/browser/bluetooth/electron_bluetooth_delegate.cc:87:10: warning: constructing string from nullptr is undefined behaviour [bugprone-string-constructor]
  return nullptr;
         ^
../../electron/shell/browser/electron_permission_manager.cc:211:5: warning: 'details' used after it was moved [bugprone-use-after-move]
    details.Set("requestingUrl",
    ^
../../electron/shell/browser/electron_permission_manager.cc:215:26: note: move occurred here
                         base::Value(std::move(details)));
                         ^
../../electron/shell/browser/electron_permission_manager.cc:211:5: note: the use happens in a later loop iteration than the move
    details.Set("requestingUrl",
    ^
../../electron/shell/browser/file_select_helper.cc:74:7: warning: initializer for member 'select_file_dialog_' is redundant [readability-redundant-member-init]
      select_file_dialog_(),
      ^~~~~~~~~~~~~~~~~~~~~
../../electron/shell/browser/file_select_helper.cc:75:7: warning: initializer for member 'select_file_types_' is redundant [readability-redundant-member-init]
      select_file_types_(),
      ^~~~~~~~~~~~~~~~~~~~
../../electron/shell/browser/font_defaults.cc:111:3: warning: use range-based for loop instead [modernize-loop-convert]
  for (size_t i = 0; i < kFontDefaultsLength; ++i) {
  ^   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      (auto pref : kFontDefaults)
../../electron/shell/browser/net/asar [...]

2023-04-23 11:14 UTC, miniak approved these changes

2023-04-24 08:22 UTC, codebytere approved these changes

2023-04-24 14:29 UTC, jkleinsc requested changes
Lint needs to be fixed

2023-04-25 09:18 UTC, codebytere commented
@dsanders11 looks like it's confused by `modernize-use-equals-default` 🤔

2023-04-26 06:45 UTC, dsanders11 commented
Lint fixed. `cpplint` apparently doesn't play nice with others and expects to find only its own categories specified for the `NOLINT`/`NOLINTNEXTLINE` comment, but `clang-tidy` also uses that comment syntax. Which is unfortunate.

Refactored the problematic code to remove the comment all together.

https://github.com/electron/electron/blob/225336e4ea6e87a47ed4aa145ddb0ace412a2db2/shell/browser/api/electron_api_system_preferences.cc#L20-L34

2023-04-26 14:09 UTC, jkleinsc approved these changes

2023-04-26 14:09 UTC, merged