docs: Documentation changes
electron/electron pull request #38666
Opened 2023-06-08 04:16 UTC by varunsood2003

- [x] relevant documentation, tutorials, templates and examples are changed or added
Fix : #34499
Made changes in docs regarding the type property of the BrowserWindow that lacked explanation:

2023-06-13 21:44 UTC, dsanders11 requested changes
Hi @varunsood2003! Thanks for the PR. This PR description needs to follow our [pull request template](https://raw.githubusercontent.com/electron/electron/main/.github/PULL_REQUEST_TEMPLATE.md) so that our automation around release notes works, so please revise the description to follow that. This PR also needs a more descriptive title.

For consistency, could the descriptions be changed to be more similar to the ones below them in the macOS section, namely in the style "The `<foo>` type ..." rather than "<foo>: This ..."?

2023-06-21 08:47 UTC, codebytere commented
@varunsood2003 do you plan to pursue this PR?

2023-06-22 08:11 UTC, varunsood2003 commented
@dsanders11 I have made the required changes for this PR.

2023-06-27 15:52 UTC, dsanders11 reviewed
@varunsood2003, thanks! One requested change in the content, and the description on this PR still needs to be updated to fully follow the template as previously mentioned.

2023-06-27 15:52 UTC, dsanders11 commented on docs/api/structures/browser-window-options.md
> +  * The `Toolbar` type creates a window with a toolbar appearance.
```suggestion
  * The `toolbar` type creates a window with a toolbar appearance.
```

2023-07-03 12:37 UTC, varunsood2003 commented
Hey @dsanders11 Hopefully, I have made all the changes according to the requirements. If their are any other changes required please let me know.

2023-07-03 15:40 UTC, dsanders11 approved these changes

2023-07-03 15:42 UTC, dsanders11 commented
Thanks @varunsood2003! I've tweaked the PR description (release notes are not needed for documentation changes) and overall things LGTM now. 👍

cc @electron/docs

2023-07-05 20:26 UTC, jkleinsc approved these changes

2023-07-05 20:26 UTC, merged