docs: The return type of the stop function corrected to as boolean type
electron/electron pull request #39080
Opened 2023-07-13 04:40 UTC by VIRAT9358

#### The return type of the stop function corrected to as boolean type

#### Checklist

Expected Behavior Now
The return type of the stop function should be correctly typed as boolean
 
- changes added at https://github.com/VIRAT9358/electron/blob/my-branch/docs/api/power-save-blocker.md

#### Release Notes
none
Notes:

2023-07-13 08:18 UTC, codebytere requested changes
This example code is not Typescript and should not have types. Can you please explain further what you were trying to do?

2023-07-19 17:07 UTC, codebytere reviewed
@VIRAT9358 we'd be happy to help this move forward if possible - what you need to do to correct this is change https://github.com/electron/electron/pull/39080/files#diff-2fad1de29e653bd23d81332c4a19bd7a28094897557c7e02221b277fff684d02R55-R60 to:

```md
### `powerSaveBlocker.stop(id)`

* `id` Integer - The power save blocker id returned by `powerSaveBlocker.start`.

Returns `boolean` - Whether the specified `powerSaveBlocker` has been stopped.
```

2023-07-20 01:47 UTC, VIRAT9358 commented
Ok I will try to it today.Sorry I misinterpreted the issue

2023-07-20 02:03 UTC, VIRAT9358 commented
const { powerSaveBlocker } = require('electron')

/**
 * Starts a power save blocker with the given type.
 * @param {string} type - The type of power save blocker to start.
 * @returns {number} - The power save blocker id.
 */
const startPowerSaveBlocker = (type) => {
  return powerSaveBlocker.start(type);
};

/**
 * Stops the specified power save blocker.
 * @param {number} id - The power save blocker id returned by `powerSaveBlocker.start`.
 * @returns {boolean} - Whether the specified `powerSaveBlocker` has been stopped.
 */
const stopPowerSaveBlocker = (id) => {
  const isStopped = powerSaveBlocker.stop(id);
  return isStopped;
};

const id = startPowerSaveBlocker('prevent-display-sleep');
console.log(stopPowerSaveBlocker(id));
Can u validate this

2023-07-20 02:03 UTC, VIRAT9358 commented
`const { powerSaveBlocker } = require('electron')

/**
 * Starts a power save blocker with the given type.
 * @param {string} type - The type of power save blocker to start.
 * @returns {number} - The power save blocker id.
 */
const startPowerSaveBlocker = (type) => {
  return powerSaveBlocker.start(type);
};

/**
 * Stops the specified power save blocker.
 * @param {number} id - The power save blocker id returned by `powerSaveBlocker.start`.
 * @returns {boolean} - Whether the specified `powerSaveBlocker` has been stopped.
 */
const stopPowerSaveBlocker = (id) => {
  const isStopped = powerSaveBlocker.stop(id);
  return isStopped;
};

const id = startPowerSaveBlocker('prevent-display-sleep');
console.log(stopPowerSaveBlocker(id));`

2023-07-20 02:04 UTC, VIRAT9358 commented
In the modified code, I've created two separate functions, startPowerSaveBlocker and stopPowerSaveBlocker, which handle the starting and stopping of power save blockers, respectively. The startPowerSaveBlocker function returns the power save blocker id as before, and the stopPowerSaveBlocker function returns a boolean value indicating whether the specified power save blocker has been stopped or not.

2023-07-20 02:08 UTC, VIRAT9358 commented
```javascript
const { powerSaveBlocker } = require('electron')

/**
 * Starts a power save blocker with the given type.
 * @param {string} type - The type of power save blocker to start.
 * @returns {number} - The power save blocker id.
 */
const startPowerSaveBlocker = (type) => {
  return powerSaveBlocker.start(type);
};

/**
 * Stops the specified power save blocker.
 * @param {number} id - The power save blocker id returned by `powerSaveBlocker.start`.
 * @returns {boolean} - Whether the specified `powerSaveBlocker` has been stopped.
 */
const stopPowerSaveBlocker = (id) => {
  const isStopped = powerSaveBlocker.stop(id);
  return isStopped;
};

const id = startPowerSaveBlocker('prevent-display-sleep');
console.log(stopPowerSaveBlocker(id));


```

2023-07-20 02:10 UTC, VIRAT9358 commented
> ```js
> const { powerSaveBlocker } = require('electron')
> 
> /**
>  * Starts a power save blocker with the given type.
>  * @param {string} type - The type of power save blocker to start.
>  * @returns {number} - The power save blocker id.
>  */
> const startPowerSaveBlocker = (type) => {
>   return powerSaveBlocker.start(type);
> };
> 
> /**
>  * Stops the specified power save blocker.
>  * @param {number} id - The power save blocker id returned by `powerSaveBlocker.start`.
>  * @returns {boolean} - Whether the specified `powerSaveBlocker` has been stopped.
>  */
> const stopPowerSaveBlocker = (id) => {
>   const isStopped = powerSaveBlocker.stop(id);
>   return isStopped;
> };
> 
> const id = startPowerSaveBlocker('prevent-display-sleep');
> console.log(stopPowerSaveBlocker(id));
> ```

In the modified code, I've created two separate functions, startPowerSaveBlocker and stopPowerSaveBlocker, which handle the starting and stopping of power save blockers, respectively. The startPowerSaveBlocker function returns the power save blocker id as before, and the stopPowerSaveBlocker function returns a boolean value indicating whether the specified power save blocker has been stopped or not.

2023-07-20 09:13 UTC, codebytere commented
@VIRAT9358 to clarify, we are _not_ changing the example. We are _only_ changing the documentation itself, as i noted above.

2023-07-20 09:14 UTC, codebytere commented on docs/api/power-save-blocker.md
> +console.log(stopped);
none of this should be changed

2023-08-01 12:31 UTC, closed without merging