fix: promise resolved to early when browser intendent in-page navigation
electron/electron pull request #39260
Opened 2023-07-27 14:24 UTC by TomaszMa

#### Description of Change

After this fix [https://github.com/electron/electron/pull/36129](https://github.com/electron/electron/pull/36129) promise returned by `loadURL` function can be resolved before page finish loading. While page is loading it can trigger browser intendent in page navigation (e.g.: `window.history.replaceState` ). This PR fixes this problem.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] tests are [changed or added](https://github.com/electron/electron/blob/main/docs/development/testing.md)
- [ ] relevant documentation, tutorials, templates and examples are changed or added
- [x] [PR release notes](https://github.com/electron/clerk/blob/main/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/main/README.md#examples).

#### Release Notes

Notes: Fix problem with promise resolved to early when browser intendent in-page navigation

2023-07-27 14:30 UTC, TomaszMa commented
@nornagon can you review this fix/change ? Thanks.

2023-07-31 07:03 UTC, zcbenz requested changes
Can you fix the lint warnings?


```
/home/builduser/project/src/electron/lib/browser/api/web-contents.ts
  450:9   error  Identifier 'browser_intendent_in_page_navigation' is not in camel case  camelcase
  465:9   error  Identifier 'browser_intendent_in_page_navigation' is not in camel case  camelcase
  481:12  error  Identifier 'browser_intendent_in_page_navigation' is not in camel case  camelcase

/home/builduser/project/src/electron/spec/api-web-contents-spec.ts
  380:51  error  Missing space before function parentheses      space-before-function-paren
  381:1   error  Expected indentation of 8 spaces but found 10  indent
```

The code looks good to me.

2023-07-31 13:49 UTC, TomaszMa commented
> Can you fix the lint warnings?
> 
> ```
> /home/builduser/project/src/electron/lib/browser/api/web-contents.ts
>   450:9   error  Identifier 'browser_intendent_in_page_navigation' is not in camel case  camelcase
>   465:9   error  Identifier 'browser_intendent_in_page_navigation' is not in camel case  camelcase
>   481:12  error  Identifier 'browser_intendent_in_page_navigation' is not in camel case  camelcase
> 
> /home/builduser/project/src/electron/spec/api-web-contents-spec.ts
>   380:51  error  Missing space before function parentheses      space-before-function-paren
>   381:1   error  Expected indentation of 8 spaces but found 10  indent
> ```
> 
> The code looks good to me.

Warnings fixed.

2023-08-01 06:05 UTC, zcbenz approved these changes

2023-08-08 08:10 UTC, TomaszMa commented
> @TomaszMa can you clarify what is meant by "browser intendent navigation"? I'm not sure I understand what that term refers to and haven't seen it before.

browser intendent navigation - navigation triggered by browser, e.g.: loading resources like images . Navigation indirectly caused by user. Some of the browser intendent navigation can trigger 'did-navigate-in-page' event, e.g.: `window.history.replaceState` . `google.com` page calls `window.history.replaceState` which triggers 'did-navigate-in-page'.

user intendent navigation - navigation triggered by user, e.g.: `BrowserWindow.loadURL`, `BrowserWindow.loadFile`, or user clicking on hyper link. Every navigation directly caused by user.

2023-08-08 08:22 UTC, codebytere requested changes
@TomaszMa ok thanks. I was asking mostly because "intendent" isn't really a term that's used. We should something that more clearly conveys what's going on - `browserInitiated` and `userInitiated` are clearer. Let's instead say `browserInitiatedInPageNavigation` and `finishListenerWhenUserIntendentNavigation`.

2023-08-08 09:02 UTC, TomaszMa commented
@codebytere changed :)

2023-08-08 11:11 UTC, codebytere approved these changes
thanks :D

2023-08-09 14:06 UTC, merged

2023-08-12 13:13 UTC, codebytere commented
I think we should revert this - it's causing consistent failures in many PRs to main cc @zcbenz 

Example: https://app.circleci.com/pipelines/github/electron/electron/73291/workflows/c87fabd1-c799-4c0b-afb3-9c4830707e4f/jobs/1582308/tests

2023-08-14 13:55 UTC, TomaszMa commented
> I think we should revert this - it's causing consistent failures on Linux cc @zcbenz
> 
> Example: https://app.circleci.com/pipelines/github/electron/electron/73291/workflows/c87fabd1-c799-4c0b-afb3-9c4830707e4f/jobs/1582308/tests

Test during integration passed, so or added test on linux is unstable, or something else break the test.
@codebytere I can look on this.