feat: allow more Node.js cli flags in main process
electron/electron pull request #39344
Opened 2023-08-03 09:45 UTC by codebytere

#### Description of Change

Closes https://github.com/electron/electron/issues/39322.

This PR allows a few more cli flags to be set in the main process. Specifically, we currently allow these to be set indirectly via the [`process` object](https://github.com/electron/electron/blob/67a6fbf2656c5aa18c59721b56b081c156e79fad/docs/api/process.md#L93-L110),  which causes Node.js itself to add them to cli flags. This aligns the flags so that users can set them in either place. Before this, Node.js would log the process warning in a way that ultimately created more confusion for users. They would be told to set the flag to see warnings, but if they did, it would be silently dropped and seem to have no effect.

<details><summary>Before</summary>
<p>

```
electron-trace-warnings-issue on git:main ❯ npm start            11:40AM

> electron-quick-start@1.0.0 start
> e start --trace-warnings .

Running "/Users/codebytere/Developer/electron-gn/src/out/Testing/Electron.app/Contents/MacOS/Electron --trace-warnings ."
(node:48122) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 window-all-closed listeners added to [App]. Use emitter.setMaxListeners() to increase limit
(Use `Electron --trace-warnings ...` to show where the warning was created)
```

</p>
</details> 

<details><summary>After</summary>
<p>

```
electron-trace-warnings-issue on git:main ❯ npm start            11:30AM

> electron-quick-start@1.0.0 start
> e start --trace-warnings .

Running "/Users/codebytere/Developer/electron-gn/src/out/Testing/Electron.app/Contents/MacOS/Electron --trace-warnings ."
(node:47282) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 window-all-closed listeners added to [App]. Use emitter.setMaxListeners() to increase limit
    at _addListener (node:events:587:17)
    at App.addListener (node:events:605:10)
    at Object.<anonymous> (/Users/codebytere/Developer/repros/electron-trace-warnings-isssue/main.js:41:7)
    at Module._compile (node:internal/modules/cjs/loader:1271:14)
    at Object..js (node:internal/modules/cjs/loader:1326:10)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at node:internal/modules/cjs/loader:967:12
    at Function._load (node:electron/js2c/asar_bundle:756:32)
    at loadApplicationPackage (/Users/codebytere/Developer/electron-gn/src/out/Testing/Electron.app/Contents/Resources/default_app.asar/main.js:121:16)
```

</p>
</details> 

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] [PR release notes](https://github.com/electron/clerk/blob/main/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/main/README.md#examples).

#### Release Notes

Notes: Added support for several more Node.js cli flags in the main process.

2023-08-03 09:48 UTC, deepak1556 approved these changes

2023-08-03 09:48 UTC, miniak approved these changes

2023-08-03 15:05 UTC, itsananderson approved these changes
API LGTM

2023-08-03 15:05 UTC, itsananderson commented on shell/common/node_bindings.cc
>      // Only allow in no-op (--) option or DebugOptions
Does this comment need an update?

2023-08-03 17:43 UTC, erickzhao requested changes

2023-08-03 18:29 UTC, erickzhao approved these changes
docs: lgtm

2023-08-03 18:30 UTC, erickzhao approved these changes
API LGTM :shipit:

2023-08-03 23:42 UTC, zcbenz approved these changes

2023-08-04 10:59 UTC, deepak1556 commented
Failing test are unrelated, merging.

2023-08-04 10:59 UTC, merged