fix: deadlock in Clipboard.readImage function.
electron/electron pull request #39446
Opened 2023-08-09 19:23 UTC by TomaszMa

#### Description of Change

There is deadlock in `Clipboard.readImage` on Windows when data in clipboard is bitmap or unsupported format (or no image data in clipboard).
Only solution for this problem is to convert `Clipboard.readImage` function to async function returning `Promise`.

Why we hit deadlock:
When data in clipboard is not PNG image or there is no image data in clipboard then `ClipboardWin::ReadPng` fallback to asynchronously decoding bitmap. In order to get results from async function `Clipboard.readImage` is blocked on main thread. Unfortunately results of decoding bitmap are send to main thread which is still blocked, and we have deadlock.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] tests are [changed or added](https://github.com/electron/electron/blob/main/docs/development/testing.md)
- [x] relevant documentation, tutorials, templates and examples are changed or added
- [x] [PR release notes](https://github.com/electron/clerk/blob/main/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/main/README.md#examples).

#### Release Notes

Notes: Resolves deadlock in Clipboard.readImage.

2023-08-09 19:40 UTC, codebytere requested changes
Thanks for working on this! Making this API asynchronous, however, isn't something we classify as a fix - it's a semver-major breaking change. I agree that we should address the deadlock, but we should look towards doing it while retaining the same API signature for users.

@zcbenz any thoughts on a potential workaround?

2023-08-09 20:21 UTC, TomaszMa commented
Deadlock is result of bad design. Electron is trying to force async function to act like sync on main thread. Is bad design and deadlock are to little issues to make decision on changing api ?

I did investigation on this problem and converting `readImage` to async function is only reasonable solution. Below arguments and findings:
- Bad design. Forcing async function to act like sync.
- Deadlock
- `ClipboardWin::ReadPng` can only be called on main or IO thread. So we cant block main thread and delegate reading from clipboard to helper thread.
- Any other solution than changing the api will require patch to chromium or resignation from decoding bitmap from clipboard.

2023-08-09 23:25 UTC, zcbenz commented
The usual way to handle the change of return type is to:

1. Add a new `readImageAsync` API.
2. Throw an exception or print warning in the old `readImage` API.

In this way developers can immediately know that they should rewrite their code to fix the error.

If we don't do so and just change the return type, this will usually be how developers find out the change:

1. Developer find app's feature broken after upgrading Electron.
2. Spent from 10 minutes to a few hours debugging.
3. Find out there is an API change.
4. Go to our GitHub page to submit an issue on why we should not change the return type of an API and only to find out there is already such issue full of angry comments in it.

2023-08-09 23:28 UTC, zcbenz commented
On the deadlock bug itself, I think it is solvable and I can look into it next week.

2023-08-10 07:51 UTC, codebytere commented
This change in particular isn't one we want to make right now because we plan to refactor it in a much larger way upcoming: https://github.com/electron/governance/pull/454.

2023-08-10 13:05 UTC, TomaszMa commented
> On the deadlock bug itself, I think it is solvable and I can look into it next week.

Tried to resolve this problem but:
1: Chrome clipboard api can be called only on main thread.
2: Js function handling is done on main thread.
3: Electron block main thread to simulate sync call.

So:
1. We cant call chrome clipboard api on other thread to avoid deadlock. To do that we will need huge patch reimplementing chrome clipboard api.
2. We cant move handling js functions to other thread, it will require lot of work.

I came with one workaround but it has one disadvantage. `readImage` on Windows will work only with PNG image format. Bitmap and no image data in clipboard will result in empty image. This workaround need to be tested on mac, because I dont know have it will behave on mac.
Workaround: https://github.com/TomaszMa/electron/commit/972a80afd65f208fc19a7246af2c1a99021eb44e

2023-08-10 13:09 UTC, TomaszMa commented
> This change in particular isn't one we want to make right now because we plan to refactor it in a much larger way upcoming: [electron/governance#454](https://github.com/electron/governance/pull/454).

I understand. Is there any plans when it will happen ?

2023-08-11 11:33 UTC, TomaszMa commented
I didn't know that chromium allows recursive task processing (https://github.com/electron/electron/pull/39466) . Question is if it safe.
I am closing this PR due to workaround (https://github.com/electron/electron/pull/39466) and plans for refactoring api (https://github.com/electron/governance/pull/454) .

2023-08-11 11:33 UTC, closed without merging