feat: expose app accessibility transparency settings api
electron/electron pull request #39631
Opened 2023-08-23 23:35 UTC by georgexu99

#### Description of Change

Exposes an api that reads the System Preferences to determine whether the app avoids using semitransparent backgrounds. If the property is  TRUE, don't use use semitransparent backgrounds in the UI.

This setting can be changed by choosing System Preferences > Accessibility > Display and selecting "Reduce transparency".

#### Checklist

- [ ] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/main/docs/development/testing.md)
- [ ] relevant documentation, tutorials, templates and examples are changed or added
- [ ] [PR release notes](https://github.com/electron/clerk/blob/main/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/main/README.md#examples).

#### Release Notes

Notes: Exposed an API to allow apps to determine whether to avoid using semitransparent backgrounds.

2023-08-24 05:07 UTC, dsanders11 commented on docs/api/system-preferences.md
> +### `systemPreferences.accessabilityDisplayShouldReduceTransparency()` _macOS_
```suggestion
### `systemPreferences.accessibilityDisplayShouldReduceTransparency()` _macOS_
```

2023-08-24 17:48 UTC, georgexu99 commented on docs/api/system-preferences.md
> +### `systemPreferences.accessabilityDisplayShouldReduceTransparency()` _macOS_
haha oops

2023-08-25 20:26 UTC, samuelmaddock approved these changes
API LGTM

2023-08-26 14:36 UTC, MarshallOfSound requested changes

2023-08-26 14:36 UTC, MarshallOfSound commented on shell/browser/api/electron_api_system_preferences.cc
> +          "accessibilityDisplayShouldReduceTransparency",
If this is a method it should be `getFoo()` not just `foo()`

But I think this should be a property, not a method

2023-08-30 21:19 UTC, VerteDinde approved these changes

2023-08-30 22:57 UTC, georgexu99 commented
failing tests seem to be flakes

2023-09-05 18:35 UTC, MarshallOfSound approved these changes

2023-09-05 18:35 UTC, MarshallOfSound commented
API LGTM

2023-09-20 19:48 UTC, merged

2023-10-02 21:32 UTC, georgexu99 commented
/trop backport 27-x-y