test: Add comment and test for app.setAppPath()
electron/electron pull request #39706
Opened 2023-08-31 17:53 UTC by felixrieseberg

#### Description of Change

Over in `@electron/universal`, we're making use of the private and undocumented API `app.setAppPath()`. Here's what's happening: 

1. We load an app with an `app.asar`
2. Inside that `app.asar`, we call `require(`app-${platform}.asar)`
3. From this point of forward, Electron's APIs might point at the wrong application root - calls like `browserWindow.loadFile(path)` will try to find `path` inside `app.asar`, even though it's in the platform-specific one.

This PR doesn't change any code in Electron, it simply adds tests and leaves behind a code comment so that we don't accidentally remove that API even though it's used in `@electron/universal`.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] tests are [changed or added](https://github.com/electron/electron/blob/main/docs/development/testing.md)
- [x] relevant documentation, tutorials, templates and examples are changed or added
- [x] [PR release notes](https://github.com/electron/clerk/blob/main/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/main/README.md#examples).

#### Release Notes

notes: no-notes

2023-08-31 21:40 UTC, felixrieseberg commented
Heads-up: The failing tests are flakes or caused by the fact that I'm working in a fork!

2023-09-04 10:35 UTC, codebytere approved these changes

2023-09-04 10:35 UTC, codebytere commented
@felixrieseberg if you rebase this, main was failing and should be resolved now!

2023-09-05 16:12 UTC, felixrieseberg commented
Rebased, thank you!

2023-09-27 09:33 UTC, codebytere commented
<img width="924" alt="Screenshot 2023-09-27 at 11 33 19 AM" src="https://github.com/electron/electron/assets/2036040/7e90796c-d4ba-4250-a798-68f1c3792c05">
@felixrieseberg this looks to be actually failing as of latest CI runs

2023-09-27 14:21 UTC, jkleinsc requested changes
Newly added test fails

2024-02-08 01:57 UTC, zcbenz commented
Add `wip` label as the CI failures need to be solved.

2025-04-27 15:56 UTC, felixrieseberg commented
I'll close this, if I tried this again I'd probably just do it on a brand new PR

2025-04-27 15:56 UTC, closed without merging