refactor: use replaceAll() instead of replace() when appropriate
electron/electron pull request #39721
Opened 2023-09-01 22:27 UTC by miniak

Identified by https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-string-replace-all.md

Notes: none

2023-09-06 18:48 UTC, jkleinsc requested changes
PR needs to be rebased to resolve build errors.

2023-09-06 23:17 UTC, miniak commented
@jkleinsc rebased

2023-09-07 00:59 UTC, jkleinsc approved these changes

2023-09-07 06:49 UTC, zcbenz approved these changes

2023-09-07 06:50 UTC, merged