fix: correctly track receiver for methods called via ctx bridge
electron/electron pull request #39978
Opened 2023-09-26 10:55 UTC by MarshallOfSound

TODO: Write a test that proves this fixes the `nativeImage` issue

Notes: Functions called over the `contextBridge` are now called with the expected receiver (`this`)

2023-10-12 19:05 UTC, jkleinsc requested changes
Can we add a test that verifies the issue in #39891?

2023-10-12 19:07 UTC, jkleinsc commented
@codebytere specifically calling `image.getSize()` from the renderer, not the main process.

2023-10-16 10:44 UTC, codebytere commented
@jkleinsc done!

2023-10-18 14:21 UTC, jkleinsc approved these changes

2023-10-18 14:21 UTC, merged