chore: formally deprecate `crashed` and `render-process-gone` events
electron/electron pull request #40089
Opened 2023-10-04 09:54 UTC by miniak

#### Description of Change

#### Checklist

- [ ] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/main/docs/development/testing.md)
- [ ] relevant documentation, tutorials, templates and examples are changed or added
- [ ] [PR release notes](https://github.com/electron/clerk/blob/main/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/main/README.md#examples).

#### Release Notes

Notes:

2023-10-06 04:41 UTC, dsanders11 requested changes
The `crashed` and `render-process-gone` events are on `WebContents`, not `BrowserWindow`.

2023-10-06 04:49 UTC, dsanders11 commented
Title of this PR should refer to `renderer-process-crashed`, not `renderer-process-gone`. If it's not too much effort, let's add tests which expect the deprecation messages (see the deprecation checklist from cation).

2023-10-06 08:47 UTC, miniak commented
> The `crashed` and `render-process-gone` events are on `WebContents`, not `BrowserWindow`.

@dsanders11 oops, I don't know how I missed that. Fixed now.

2023-10-06 08:58 UTC, miniak commented
> #40090

@dsanders11 I should have added the tests in #40090. We only have test for `renderer-process-crashed` on `app`. I need to add tests for `crashed` / `render-process-gone` on `WebContents` and `<webview>`. Title fixed.

2023-10-06 09:52 UTC, miniak commented
@dsanders11 We need to do this #40124

2023-10-09 00:58 UTC, miniak commented
@dsanders11 the warnings are in main now

2023-10-09 03:56 UTC, dsanders11 commented
@miniak, I'm not sure if #40124 was necessary here. I added [`spec/lib/deprecate-helpers.ts`](https://github.com/electron/electron/blob/main/spec/lib/deprecate-helpers.ts) in #39405 and used that for expecting deprecation warnings in previous PRs. The implementation there works around the internal module issue by listening to `console.warn` and the `warning` event on process and expecting the output there, instead of relying on the details of the deprecation module.

2023-10-09 23:31 UTC, dsanders11 approved these changes

2023-10-10 09:04 UTC, codebytere approved these changes

2023-10-10 23:47 UTC, jkleinsc approved these changes

2023-10-10 23:49 UTC, merged