chore: Show FIDO devices in the chooser if allowed
electron/electron pull request #40216
Opened 2023-10-16 09:11 UTC by codebytere

#### Description of Change

Refs CL:3309164

> This CL allows devices containing a top-level collection with a usage
from the FIDO usage page to appear in the WebHID device chooser if
the requesting origin is allowed to access FIDO.

Refs CL:3595839

> This CL makes sure users can see why a HID device does not show up in the browser picker to help debugging. See https://stackoverflow.com/a/71922823/422957 for context

#### Checklist

- [x] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [x] [PR release notes](https://github.com/electron/clerk/blob/main/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/main/README.md#examples).

#### Release Notes

Notes: none

2023-10-16 16:35 UTC, jkleinsc requested changes
This change removes functionality currently supported by Electron and replaces it with Chromium specific logic around allowing devices when a specific extension is installed.  I'm not sure I see the use case to do this.

2023-10-17 10:01 UTC, codebytere commented
Changes addressed following offline conversation ☝️

2023-10-17 10:01 UTC, codebytere commented
Changes addressed following offline conversation ☝️

2023-10-17 15:32 UTC, jkleinsc requested changes
Overall LGTM; just needs a few tweaks to more closely follow the changes in https://chromium-review.googlesource.com/c/chromium/src/+/3809913

2023-10-17 15:32 UTC, jkleinsc commented on shell/browser/hid/electron_hid_delegate.cc
> +  return chooser_context->HasDevicePermission(origin, device);
We should more closely mirror upstream here, eg:
```suggestion
  return browser_context && GetChooserContext(browser_context->HasDevicePermission(origin, device);
```

2023-10-17 15:32 UTC, jkleinsc commented on shell/browser/hid/electron_hid_delegate.cc
> +  chooser_context->RevokeDevicePermission(origin, device);
We should more closely mirror upstream here, eg:
```suggestion
  return browser_context && GetChooserContext(browser_context)->RevokeDevicePermission(origin, device);
```

2023-10-17 15:32 UTC, jkleinsc commented on shell/browser/hid/electron_hid_delegate.cc
> +  return chooser_context->GetHidManager();
We should more closely mirror upstream here, eg:
```suggestion
  if (!browser_context) {
    return nullptr;
  }
  return GetChooserContext(browser_context)->GetHidManager();
```

2023-10-17 15:32 UTC, jkleinsc commented on shell/browser/hid/electron_hid_delegate.cc
> +    return nullptr;
This matches upstream, but if we keep it as is we need to change `GetChooserContext` to return nullptr if !browser_context.

2023-10-17 15:32 UTC, jkleinsc commented on shell/browser/hid/electron_hid_delegate.cc
> +  return chooser_context->IsFidoAllowedForOrigin(origin);
This kind of matches upstream, but if we keep it as is we need to change GetChooserContext to return nullptr if !browser_context.

2023-10-18 14:51 UTC, jkleinsc approved these changes

2023-10-18 23:19 UTC, merged