feat: add utility process typescript namespace
electron/electron pull request #40264
Opened 2023-10-18 14:28 UTC by devm33

#### Description of Change

Upgrades docs-parser and typescript-definitions to add new 'electron/utility' namespace added in:
- https://github.com/electron/docs-parser/pull/95
- https://github.com/electron/typescript-definitions/pull/246

#### Checklist

- [ ] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/main/docs/development/testing.md)
- [ ] relevant documentation, tutorials, templates and examples are changed or added
- [ ] [PR release notes](https://github.com/electron/clerk/blob/main/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/main/README.md#examples).

#### Release Notes

Notes: Added utility process TypeScript namespace.

2023-10-19 20:31 UTC, jkleinsc requested changes
Due to security restrictions, yarn.lock changes are restricted to maintainers only.

Additionally, it appears that this change does not pass lint: https://app.circleci.com/pipelines/github/electron/electron/75605/workflows/dcf582a9-b884-415b-8c2f-56bf047d13d0/jobs/1622825

2023-10-19 20:44 UTC, devm33 commented
Thanks for taking a look!

> Due to security restrictions, yarn.lock changes are restricted to maintainers only.

Should the PR only include package.json changes or does a maintainer need to do this PR?

> Additionally, it appears that this change does not pass lint: https://app.circleci.com/pipelines/github/electron/electron/75605/workflows/dcf582a9-b884-415b-8c2f-56bf047d13d0/jobs/1622825

Sorry yes working on fixing! https://github.com/electron/electron/pull/40017#issuecomment-1769813375

2023-10-26 02:48 UTC, devm33 commented
@jkleinsc I've updated here with the fix for the typescript-definitions change https://github.com/electron/typescript-definitions/pull/247 and dropped the yarn.lock changes. Unfortunately, that does mean lint is now failing due to the package.json and yarn.lock being out of sync.

``error Your lockfile needs to be updated, but yarn was run with `--frozen-lockfile`.`` https://app.circleci.com/pipelines/github/electron/electron/75794/workflows/7803b286-c927-4c3f-b3a2-48cfa187f9d5/jobs/1626190

2023-10-27 18:39 UTC, dsanders11 commented
I've added the `yarn.lock` changes myself and pushed them, but it should be noted this lands multiple changes from these packages (including dropping the remote interface stuff), so I think the title should probably be more generic so it better matches all of the functional changes, e.g. "build: update @electron/docs-parser and @electron/typescript-definitions".

FYI @devm33, I think you may be using an older version of `yarn` which is causing your `yarn.lock` changes to be bigger than necessary. Your original `yarn.lock` changes were in the thousands of lines, while mine is less than 10.

2023-10-27 18:44 UTC, devm33 commented
Thanks @dsanders11! Updated the PR title and description

2023-10-31 20:36 UTC, jkleinsc approved these changes

2023-10-31 20:36 UTC, merged