refactor: ensure IpcRenderer is not bridgable
electron/electron pull request #40330
Opened 2023-10-25 15:25 UTC by MarshallOfSound

It's a security footgun that IpcRenderer (unlike everything else) can go over the context bridge by accident.  Let's just make it so it can't

Notes: no-notes

2023-10-25 15:40 UTC, codebytere approved these changes

2023-10-25 19:59 UTC, miniak approved these changes

2023-10-25 20:00 UTC, miniak commented
@MarshallOfSound would it make sense to do this as well for consistency?
```ts
class IpcRendererInternal extends EventEmitter implements ElectronInternal.IpcRendererInternal {
  send (channel: string, ...args: any[]) {
    return ipc.send(internal, channel, args);
  }

  sendSync (channel: string, ...args: any[]) {
    return ipc.sendSync(internal, channel, args);
  }

  async invoke<T> (channel: string, ...args: any[]) {
    const { error, result } = await ipc.invoke<T>(internal, channel, args);
    if (error) {
      throw new Error(`Error invoking remote method '${channel}': ${error}`);
    }
    return result;
  };
}

export const ipcRendererInternal = new IpcRendererInternal();
```

2023-10-25 20:01 UTC, MarshallOfSound commented
@miniak Oh yeah sure

2023-10-30 17:21 UTC, dsanders11 commented
Should this be considered a breaking change? In #40321 the docs are being updated to avoid the footgun pattern, but currently the IPC tutorial said "In the renderer process, use the `event` parameter to send a reply back to the main process [...]" (and gave a code example doing so). If someone followed that tutorial, won't this change break their code?

2023-10-30 17:44 UTC, MarshallOfSound commented
> Should this be considered a breaking change?

In the sense we could note it somewhere, probably, in the sense that it's semver/major no.  Security fixes aren't considered semver/major.  No plans to backport this one though

2023-10-30 18:03 UTC, dsanders11 commented
> In the sense we could note it somewhere, probably

Let's add it to breaking changes then. 👍

2023-10-31 16:12 UTC, jkleinsc requested changes
Looks like this change is causing the `node feature does not hang when using the fs module in the renderer process` test to fail.

2023-10-31 21:29 UTC, jkleinsc approved these changes

2023-10-31 21:29 UTC, merged