fix: titlebar incorrectly displayed on frameless windows
electron/electron pull request #40749
Opened 2023-12-12 12:42 UTC by brhenrique

#### Description of Change

- Fixes a bug where Mica background won't work without the `transparent: true` setting
- Fixes a bug where a title bar is displayed on frameless windows

[A patch was added](https://github.com/electron/electron/pull/39708/) to fix Mica backgrounds on frameless windows, but it caused a side-effects in which a title bar gets displayed on frameless transparent windows.

This happens because, after the patch, `[WM_NCACTIVATE](https://learn.microsoft.com/en-us/windows/win32/winmsg/wm-ncactivate)` would be dispatched to `DefWindowProc` for frameless transparent windows. While this is necessary to make Mica work on these windows, it would cause an incorrect title bar to also be displayed.

To fix this, we are setting -1 as the lParam of `DefWindowProc`, which seems to prevent the non-client area from being displayed on window activation/deactivation:

> When a visual style is not active for this window, this parameter is a handle to an optional update region for the nonclient area of the window. If this parameter is set to -1, [DefWindowProc](https://learn.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-defwindowproca) does not repaint the nonclient area to reflect the state change.

#### Checklist

- [ ] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/main/docs/development/testing.md)
- [ ] relevant documentation, tutorials, templates and examples are changed or added
- [ ] [PR release notes](https://github.com/electron/clerk/blob/main/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/main/README.md#examples).

#### Release Notes

Notes:

2023-12-12 12:43 UTC, brhenrique commented
cc @zcbenz @clavin

2023-12-13 08:31 UTC, zcbenz approved these changes

2023-12-15 11:43 UTC, michalzaq12 commented
Good job, but I noticed two things (regarding frameless window):
- strange behavior when we set `transparet: true` with Mica enabled. Mica does not work on initial page load. But it starts working after resizing the window. Without `transparet: true`, mica works as intended.
- Maximizing a window with Mica enabled, causes the entire window to crash

2023-12-15 15:00 UTC, brhenrique commented
> Good job, but I noticed two things (regarding frameless window):
> 
> * strange behavior when we set `transparet: true` with Mica enabled. Mica does not work on initial page load. But it starts working after resizing the window. Without `transparet: true`, mica works as intended.
> * Maximizing a window with Mica enabled, causes the entire window to crash

I see, but both issues seem to also be present in the latest stable, right? I think there should be a separate PR for them, since this one is focused on different problems.

2023-12-18 03:19 UTC, Cloudkkk commented
🥹Is there any blocking point for this PR? When can we expect it to be fixed? It's really important to me. Thanks

2023-12-19 21:28 UTC, clavin requested changes
Well done! Thank you so much for investigating and fixing this 😊

I have built and manually tested this change and can confirm it works. ✅

I have one small change to request 😅 but after that this should be good to merge. I'll also make sure the backports for this PR land swiftly after.

2023-12-19 22:16 UTC, ckerr approved these changes

2023-12-22 02:34 UTC, Auhnip commented
I recently came across this pull request and noticed that it contains the exact fix I need for a bug that's been a bit of a roadblock for me. Is there any chance it could be reviewed and merged soon? It's important to me. thanks~

2023-12-26 01:11 UTC, clavin approved these changes
I went and pushed the change I described to your branch—I hope that's alright—so that we can get this fix merged asap 😄

2024-01-02 18:59 UTC, merged

2025-08-04 03:38 UTC, wujunliang commented
最新版本37.2.5依然有这个bug
<img width="469" height="329" alt="wechat_2025-08-04_113601_551" src="https://github.com/user-attachments/assets/65204572-1a8f-4f31-bc67-29acf8e25adf" />

2025-08-04 03:49 UTC, wujunliang commented
37.2.5还是有这个bug
<img width="469" height="329" alt="wechat_2025-08-04_113601_551" src="https://github.com/user-attachments/assets/fdef9771-1699-4a84-8dbe-c60091a4f732" />