fix: crash using powerMonitor before ready event
electron/electron pull request #40888
Opened 2024-01-04 18:07 UTC by codebytere

#### Description of Change

Closes https://github.com/electron/electron/issues/40694.
Refs https://github.com/electron/electron/pull/37937.

This PR fixes a crash resultant in trying to listen to power-related events before the `ready` event is emitted on Linux. This was happening because the `PowerObserverLinux` ctor called `bluez::BluezDBusThreadManager::Get()`, which assumed that `bluez::BluezDBusThreadManager::Initialize()` had already been called and `CHECK`ed if it hadn't been. However, our existing logic did not call `bluez::BluezDBusThreadManager::Initialize()` until `ElectronBrowserMainParts::PostCreateMainMessageLoop()`, which meant that trying to use:

```js
  powerMonitor.on('suspend', () => {
    console.log('suspend')
  });

  powerMonitor.on('resume', () => {
    console.log('resume')
  });
```

before the `ready` event would immediately die. I chose to fix this by calling `bluez::BluezDBusThreadManager::Initialize()` as soon as it was needed, and adding a check to ensure that it was not initialized more than once. Alternately, we can bring back the `ready` event requirement.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] [PR release notes](https://github.com/electron/clerk/blob/main/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/main/README.md#examples).

#### Release Notes

Notes: Fixed a crash resultant from trying to listen to power-related events before the `ready` event was emitted on Linux.

2024-01-04 18:08 UTC, nornagon approved these changes
lazy initialize seems like a good approach to me 👍🏻

2024-01-04 20:44 UTC, VerteDinde approved these changes

2024-01-04 22:59 UTC, ckerr requested changes

2024-01-04 22:59 UTC, ckerr commented on shell/browser/electron_browser_main_parts.cc
> +  bluez::BluezDBusManager::Shutdown();
This function `CHECK()`s that `bluez::BluezDBusManager::Initialize()` has been called first, so  I _think_ we need to wrap this with `if (bluez::BluezDBusManager::IsInitialized())`?

```suggestion
  if (bluez::BluezDBusManager::IsInitialized())
    bluez::BluezDBusManager::Shutdown();
```

2024-01-04 23:02 UTC, ckerr approved these changes

2024-01-05 04:41 UTC, deepak1556 reviewed
Minor nit: wouldn't it be better to continue using the wrapper class to avoid missing any additional bluez initialization or shutdown paths that might get added in future ?

```
if (!bluez::BluezDBusManager::IsInitialized())
  bluez::DBusBluezManagerWrapperLinux::Initialize();
```

2024-01-08 14:26 UTC, codebytere commented
@deepak1556 done!

2024-01-08 16:14 UTC, deepak1556 approved these changes
Thanks!

2024-01-09 08:41 UTC, codebytere commented
Failing test unrelated: 
> reporting api sends a report for an intervention

2024-01-09 08:41 UTC, merged