refactor: type-safe imports in lib/node/init.ts
electron/electron pull request #41148
Opened 2024-01-27 01:22 UTC by miniak

Follow-up to #41080 and #41118

2024-01-29 01:40 UTC, zcbenz approved these changes

2024-01-29 07:32 UTC, zcbenz requested changes
This change makes node tests crash, is it because of using `import`?

```
ELECTRON_RUN_AS_NODE=1 electron ../third_party/electron_node/test/parallel/test-shadow-realm-preload-module.js
[process 20208]: --- stderr ---

  #  /Users/zcbenz/codes/be/src/out/Default/Electron.app/Contents/MacOS/Electron[20208]: void node::performance::SetupPerformanceObservers(const FunctionCallbackInfo<Value> &) at ../../third_party/electron_node/src/node_perf.cc:129
  #  Assertion failed: (realm->kind()) == (Realm::Kind::kPrincipal)

----- Native stack trace -----

 1: 0x12ee54eb5 node::Abort() [/Users/zcbenz/codes/be/src/out/Default/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 2: 0x12ee54b4c node::Assert(node::AssertionInfo const&) [/Users/zcbenz/codes/be/src/out/Default/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 3: 0x12eecde7d node::performance::SetupPerformanceObservers(v8::FunctionCallbackInfo<v8::Value> const&) [/Users/zcbenz/codes/be/src/out/Default/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 4: 0x12687d057 Builtins_CallApiCallbackGeneric [/Users/zcbenz/codes/be/src/out/Default/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]

----- JavaScript stack trace -----

1: node:internal/perf/observe:568:1
2: compileForInternalLoader (node:internal/bootstrap/realm:401:7)
3: requireBuiltin (node:internal/bootstrap/realm:432:14)
4: node:net:158:5
5: compileForInternalLoader (node:internal/bootstrap/realm:401:7)
6: requireBuiltin (node:internal/bootstrap/realm:432:14)
7: node:internal/child_process:40:13
8: compileForInternalLoader (node:internal/bootstrap/realm:401:7)
9: requireBuiltin (node:internal/bootstrap/realm:432:14)
10: node:child_process:89:23



[process 20208]: --- stdout ---

[process 20208]: status = null, signal = SIGABRT
/Users/zcbenz/codes/be/src/third_party/electron_node/test/common/child_process.js:86
    throw new Error(`${failures.join('\n')}`);
          ^

Error: - process terminated with status null, expected 0
- process terminated with signal SIGABRT, expected null
    at logAndThrow (/Users/zcbenz/codes/be/src/third_party/electron_node/test/common/child_process.js:86:11)
    at expectSyncExit (/Users/zcbenz/codes/be/src/third_party/electron_node/test/common/child_process.js:91:5)
    at spawnSyncAndExitWithoutError (/Users/zcbenz/codes/be/src/third_party/electron_node/test/common/child_process.js:125:10)
    at main (/Users/zcbenz/codes/be/src/third_party/electron_node/test/parallel/test-shadow-realm-preload-module.js:12:3)
    at Object.<anonymous> (/Users/zcbenz/codes/be/src/third_party/electron_node/test/parallel/test-shadow-realm-preload-module.js:20:1)
    at Module._compile (node:internal/modules/cjs/loader:1392:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1452:10)
    at Module.load (node:internal/modules/cjs/loader:1215:32)
    at Module._load (node:internal/modules/cjs/loader:1031:12)
    at Module._load (node:electron/js2c/node_init:773:32)
```

2024-01-30 09:55 UTC, miniak commented
@zcbenz that `import` is a syntactic thing just to make it type-safe AFAIK

2024-01-30 10:32 UTC, zcbenz commented
> Can I run those node tests on Mac locally to test it?

The failure can be reproduced on mac, just build and run this command:

```
ELECTRON_RUN_AS_NODE=1 electron ../third_party/electron_node/test/parallel/test-shadow-realm-preload-module.js
```

2024-01-30 23:12 UTC, zcbenz approved these changes

2024-01-30 23:38 UTC, merged