documentation: add note about fuses to our security documentation
electron/electron pull request #41210
Opened 2024-02-01 11:52 UTC by Kilian

#### Description of Change

This adds a new item to the security checklist to review the fuses values. IT also adds item number 18 to the ToC up top.

#### Checklist

- [ ] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/main/docs/development/testing.md)
- [x] relevant documentation, tutorials, templates and examples are changed or added
- [x] [PR release notes](https://github.com/electron/clerk/blob/main/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/main/README.md#examples).

#### Release Notes

Notes: none

2024-02-01 18:20 UTC, felixrieseberg approved these changes

2024-02-01 18:20 UTC, felixrieseberg commented on docs/tutorial/security.md
> +18. [Avoid usage of the `file://` protocol and prefer usage of custom protocols](#18-avoid-usage-of-the-file-protocol-and-prefer-usage-of-custom-protocols)
Good catch!

2024-02-01 18:20 UTC, felixrieseberg commented on docs/tutorial/security.md
> +Some fuses, like `runAsNode` and `nodeCliInspect` allow the application to behave differently
```suggestion
Some fuses, like `runAsNode` and `nodeCliInspect`, allow the application to behave differently
```

2024-02-01 19:11 UTC, erickzhao approved these changes

2024-02-01 19:11 UTC, erickzhao approved these changes
docs: lgtm

2024-02-01 19:38 UTC, dsanders11 requested changes
Can we move the new section above the reference link definitions so they stay at the bottom of the doc?

2024-02-02 07:41 UTC, Kilian commented
@dsanders11 change made!

2024-02-02 07:45 UTC, dsanders11 approved these changes

2024-02-02 23:28 UTC, merged