chore: remove deprecated inputFieldType
electron/electron pull request #41239
Opened 2024-02-05 10:35 UTC by miniak

#### Description of Change

#### Checklist

- [ ] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/main/docs/development/testing.md)
- [ ] relevant documentation, tutorials, templates and examples are changed or added
- [ ] [PR release notes](https://github.com/electron/clerk/blob/main/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/main/README.md#examples).

#### Release Notes

Notes:

2024-02-08 16:05 UTC, ckerr requested changes
The current changes all LGTM.

The removal probably also deserves a mention in `breaking-changes.md`, e.g. 

> Removed: deprecated `docs/inputFieldType`.

2024-02-17 12:01 UTC, miniak commented
@ckerr definitely, that's why the PR is marked as `wip` and draft. Formal deprecation needs to happen first however. Doing that in #41362

2024-02-20 20:16 UTC, miniak commented
@ckerr the deprecation checklist should be complete now, including updating breaking-changes.md

2024-02-21 10:53 UTC, codebytere approved these changes

2024-02-21 10:53 UTC, codebytere commented
API LGTM

2024-02-21 16:04 UTC, jkleinsc approved these changes
API LGTM

2024-02-23 15:01 UTC, ckerr approved these changes
API LGTM

2024-02-26 12:47 UTC, merged