docs: fix docs/api/base-window.md
electron/electron pull request #41240
Opened 2024-02-05 10:44 UTC by miniak

#35658 added docs/api/base-window.md with outdated APIs from docs/api/browser-window.md

2024-02-05 11:35 UTC, miniak commented
@nornagon can we avoid duplicating the docs somehow?

2024-02-06 09:28 UTC, codebytere approved these changes

2024-02-06 17:18 UTC, dsanders11 requested changes
Good catch, just one minor tweak requested.

2024-02-06 17:18 UTC, dsanders11 commented on docs/api/base-window.md
> +**Note:** On macOS, fullscreen transitions take place asynchronously. If further actions depend on the fullscreen state, use the ['enter-full-screen'](browser-window.md#event-enter-full-screen) or ['
```suggestion
**Note:** On macOS, fullscreen transitions take place asynchronously. If further actions depend on the fullscreen state, use the ['enter-full-screen'](base-window.md#event-enter-full-screen) or ['leave-full-screen'](base-window.md#event-leave-full-screen) events.
```

2024-02-06 17:22 UTC, ckerr approved these changes
LGTM, approving pending the change @dsanders11 requested

2024-02-07 17:54 UTC, dsanders11 approved these changes

2024-02-07 20:36 UTC, codebytere approved these changes

2024-02-08 01:13 UTC, zcbenz approved these changes

2024-02-08 01:13 UTC, merged