Improve gin stuff
electron/electron pull request #41534
Opened 2024-03-06 16:01 UTC by codebytere

#### Description of Change

Refs https://chromium-review.googlesource.com/c/chromium/src/+/5104930
Refs https://github.com/microsoft/vscode/issues/192119

We should still make it a goal to use upstream `gin/function_template`, but that'll be perhaps a longer-term venture as there are several critical things we do differently than they do. This updates our forked `gin/function_template.{h|cc}` to apply those differences to the latest upstream version of those files. A key critical change is from the above CL:

> gin previously relied exclusively on garbage collection in order to
trigger cleanup of function templates. This is unreliable as garbage
collection is never guaranteed to run, especially for short-lived
isolates.

Now, we add observers for isolate disposal in order to clean up function templates once an isolate is disposed.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [x] [PR release notes](https://github.com/electron/clerk/blob/main/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/main/README.md#examples).

#### Release Notes

Notes: none

2024-03-06 18:09 UTC, nornagon approved these changes
seems legit

2024-03-07 00:11 UTC, deepak1556 approved these changes

2024-03-08 00:08 UTC, zcbenz approved these changes

2024-03-13 14:58 UTC, jkleinsc requested changes
Looks like node tests are failing as a result of this change.

2024-03-25 00:07 UTC, jkleinsc approved these changes

2024-03-25 09:01 UTC, merged