docs: backslash escape parametrized TypeScript types
electron/electron pull request #41575
Opened 2024-03-12 22:45 UTC by erickzhao

#### Description of Change

#### Checklist

- [ ] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/main/docs/development/testing.md)
- [ ] relevant documentation, tutorials, templates and examples are changed or added
- [ ] [PR release notes](https://github.com/electron/clerk/blob/main/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/main/README.md#examples).

#### Release Notes

Notes:

2024-03-14 08:52 UTC, codebytere approved these changes

2024-03-14 09:17 UTC, dsanders11 requested changes
Spot checking this with the new `@electron/lint-roller` rule, it looks like there's a handful of ones this PR misses. I need to tweak the rule (coming up with some false positives) but I think these are legit - if any aren't point them out so I can add test cases for the rule.

```
docs/api/session.md:1219 EMD002/no-angle-brackets No unescaped opening angle brackets in text (does not play nice with MDX) [Unescaped opening angle bracket]
docs/api/web-contents.md:240 EMD002/no-angle-brackets No unescaped opening angle brackets in text (does not play nice with MDX) [Unescaped opening angle bracket]
docs/api/web-contents.md:273 EMD002/no-angle-brackets No unescaped opening angle brackets in text (does not play nice with MDX) [Unescaped opening angle bracket]
docs/api/web-contents.md:303 EMD002/no-angle-brackets No unescaped opening angle brackets in text (does not play nice with MDX) [Unescaped opening angle bracket]
docs/api/web-contents.md:327 EMD002/no-angle-brackets No unescaped opening angle brackets in text (does not play nice with MDX) [Unescaped opening angle bracket]
docs/api/web-contents.md:358 EMD002/no-angle-brackets No unescaped opening angle brackets in text (does not play nice with MDX) [Unescaped opening angle bracket]
docs/api/web-contents.md:686 EMD002/no-angle-brackets No unescaped opening angle brackets in text (does not play nice with MDX) [Unescaped opening angle bracket]
docs/breaking-changes.md:1689 EMD002/no-angle-brackets No unescaped opening angle brackets in text (does not play nice with MDX) [Unescaped opening angle bracket]
```

2024-03-21 20:23 UTC, erickzhao commented
Thanks @dsanders11, fixed those. Awesome lint rule.

2024-03-21 20:24 UTC, dsanders11 approved these changes

2024-03-25 10:19 UTC, merged