Chore fix notes stack updates
electron/electron pull request #41600
Opened 2024-03-14 22:22 UTC by mlaurencin

#### Description of Change

This PR fixes an issue that would appear when there were multiple Chromium stack upgrades between versions. The notes script did not correctly handle the comparisons needed to determine which stack upgrade superceded which. An example of the previous issue can be seen here: https://github.com/electron/electron/releases/tag/v29.1.1 lists Chromium 122.0.6261.95, however according to https://github.com/electron/electron/blob/v29.1.1/DEPS it's 122.0.6261.111.

#### Checklist

- [ ] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/main/docs/development/testing.md)
- [ ] relevant documentation, tutorials, templates and examples are changed or added
- [ ] [PR release notes](https://github.com/electron/clerk/blob/main/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/main/README.md#examples).

#### Release Notes

Notes: None

2024-03-14 22:25 UTC, VerteDinde approved these changes
Good find!

2024-03-14 23:10 UTC, dsanders11 approved these changes

2024-03-14 23:10 UTC, dsanders11 commented on script/release/notes/notes.js
> +    const replacementSplit = version.split('.');
```suggestion
    const replacementSplit = version.split('.');
    if (newestSplit.length !== replacementSplit.length) {
      throw new Error(`Expected version strings to have same number of sections: ${newest[dep].version} and ${version}`);
    }
```

Might help catch malformed lines or changes in version string formats.

2024-03-15 18:43 UTC, ckerr approved these changes

2024-03-18 10:08 UTC, codebytere reviewed
Can we add a test?

2024-03-18 10:08 UTC, codebytere commented on script/release/notes/notes.js
> +      if (parseInt(replacementSplit[i]) < parseInt(newestSplit[i])) {
We might also clean this up a little bit by using a comparison function instead, something like:

```js
const compareVersions = (v1, v2) => {
  const [split1, split2] = [v1.split('.'), v2.split('.')];
  
  for (let i = 0; i < split1.length; i++) {
    const p1 = parseInt(split1[i], 10);
    const p2 = parseInt(split2[i], 10);
    
    if (p1 === p2) return 0;
    return p1 > p2 ? 1 : -1;
  }
  
  return 0;
}

const [, dep, version] = match;
if (!newest[dep] || compareVersions(version, newest[dep].version) > 0) {
  newest[dep] = { commit, version };
}
```

2024-03-18 12:40 UTC, sham601 commented
[electron-main.zip](https://github.com/electron/electron/files/14636270/electron-main.zip)
Thanks

2024-03-19 19:22 UTC, mlaurencin commented on script/release/notes/notes.js
> +      if (parseInt(replacementSplit[i]) < parseInt(newestSplit[i])) {
Ok, thanks for the suggestion. I implemented something similar in the latest commit, as I think this code would only check the major version.

2024-03-19 19:22 UTC, mlaurencin commented
> Can we add a test?

Yes, I will work on adding a unit test next

2024-03-21 14:04 UTC, jkleinsc requested changes
Test(s) should be added before we merge this.

2024-04-29 15:41 UTC, merged