fix(ClientRequest): recognize the 'undefined' header value
electron/electron pull request #41615
Opened 2024-03-18 02:19 UTC by daihere1993

#### Description of Change
There was an issue I encountered that I mistakenly used `undefined` as a header value when using `electron.net.request()`, then threw an error "Cannot read properties of undefined (reading ‘toString’)". It's a non-semantic error and unfriendly for debug. 

I've check the source code, then found out there do have a `empty` check but it's only checked the `null` and miss out `undefined`.

Please let me know if this correction is need, then I'll add ut for it.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [ ] `npm test` passes

#### Release Notes

Notes:

2024-03-19 09:04 UTC, codebytere approved these changes
Thanks! This looks good to me as `value` is required and can only be a string if passed. Once there's a test for this we can get it moving.

2024-03-19 17:46 UTC, nornagon requested changes
This change is a no-op because `null == undefined`.

```
> null == undefined
true
```

2024-03-19 19:21 UTC, codebytere commented
Ah you're right, missed that it was a double and not triple equals already!

2024-03-20 16:32 UTC, daihere1993 commented
@nornagon thanks for you point that out. New correction updated, I've encapsulated a new function `headerValidation()` as there are two places need it, feel free to comment @codebytere 

By the way, I'm working on to setup my local electron dev env(not easy~) after that I'll add few ut cases.

2024-03-25 22:54 UTC, nornagon approved these changes
lgtm other than the function name, thanks for the fix!

2024-03-26 01:45 UTC, daihere1993 commented on lib/common/api/net-client-request.ts
> +function headerValidation (name: any, value: any): void {
DONE

2024-03-26 06:23 UTC, daihere1993 commented
I see the type `ClientRequestConstructorOptions` not including parameter `headers` but accessing `headers` in `parseOptions()`.  @nornagon is `headers` missed in `ClientRequestConstructorOptions`?

2024-03-27 23:42 UTC, nornagon commented
> I see the type `ClientRequestConstructorOptions` not including parameter `headers` but accessing `headers` in `parseOptions()`. @nornagon is `headers` missed in `ClientRequestConstructorOptions`?

whoops, yes, that does look like an omission. Good catch—made https://github.com/electron/electron/pull/41723 to add it.

2024-03-27 23:44 UTC, nornagon approved these changes

2024-03-27 23:46 UTC, merged