feat(serial): allow Bluetooth ports to be requested by service class ID
electron/electron pull request #41638
Opened 2024-03-20 14:49 UTC by codebytere

#### Description of Change

Refs CL:4522192.

In https://github.com/electron/electron/pull/38465 we added a parameter to `ElectronSerialDelegate::RunChooser` to account for upstream changes but never actually implemented the feature the parameter was added to support. This PR adds support for Bluetooth ports being requested by service class ID, thereby bringing our WebSerial implementation into alignment with the current state of the web platform api. Now, users can do e.g:

```js
const port = await navigator.serial.requestPort({
     filters: [{bluetoothServiceClassId: 0x1101}]
});
```

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] [PR release notes](https://github.com/electron/clerk/blob/main/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/main/README.md#examples).

#### Release Notes

Notes: Added support for Bluetooth ports being requested by service class ID in `navigator.serial`.

2024-03-21 13:54 UTC, jkleinsc requested changes
Looks like the GN checks are failing, eg:
https://app.circleci.com/pipelines/github/electron/electron/79480/workflows/73955dd2-f239-4a89-b9e7-527b90a9ac22/jobs/1689290

2024-03-21 14:31 UTC, codebytere commented
@jkleinsc fixed!

2024-03-22 01:58 UTC, jkleinsc approved these changes

2024-03-22 01:58 UTC, jkleinsc reviewed
API LGTM

2024-03-22 04:42 UTC, deepak1556 approved these changes

2024-03-28 16:54 UTC, MarshallOfSound approved these changes
API LGTM

2024-03-28 17:23 UTC, merged