fix: subclasses should show in `BrowserWindow.getAllWindows()`
electron/electron pull request #41795
Opened 2024-04-08 09:08 UTC by codebytere

#### Description of Change

Closes https://github.com/electron/electron/issues/41785.

Adapts the `isBrowserWindow` helper in `lib/browser/api/browser-window.ts` to account for windows being subclasses of `BrowserWindow`. `win.constructor.name === 'BrowserWindow'` is a rigid check for an exact match which excludes subclasses. Additionally, instanceof operates directly on the object's prototype chain, and is therefore usually more performant.

Also adds some tests.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] tests are [changed or added](https://github.com/electron/electron/blob/main/docs/development/testing.md)
- [x] [PR release notes](https://github.com/electron/clerk/blob/main/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/main/README.md#examples).

#### Release Notes

Notes: Fixed an issue where `BrowserWindow.getAllWindows()` did not return subclasses of `BrowserWindow`.

2024-04-08 09:12 UTC, MarshallOfSound commented
This has come up before (will find ref in the am) and this is intentional, subclassing any of electrons built-in classes is not supported and will cause various issues, mostly over the binding / lifecycle boundaries. I think we even explicitly document somewhere not to subclass our api

2024-04-08 12:22 UTC, codebytere commented
ah gotcha - we should document that more visibly then i'd say as i checked around a bit and couldn't find anything in the ts commit history about intentionality of it

2024-04-08 23:53 UTC, nornagon commented
We should probably make BrowserWindow's constructor throw if it's being instantiated as a subclass.

2024-04-10 08:20 UTC, codebytere commented
@nornagon done - if you have a better idea of where I should throw let me know but trying in `BrowserWindow::BrowserWindow` via `GetConstructorName()` looked like it'd be a headache so i went with `_init`.

2024-04-10 16:13 UTC, nornagon requested changes

2024-05-30 12:27 UTC, closed without merging