feat: Use default URLLoaderFactory if protocal.handle was callbacked without arg.
electron/electron pull request #41929
Opened 2024-04-22 18:35 UTC by mrchaofan

We want to build a offline app and render our pages with https protocol. We want to use protocol.handle api to implement it. But We've found some problem while using it. We need cookie, localStorage, pwa, etc. So We have to use https protocol to render our pages. If not we have to change a lot of code to adapt Electron environment.

The protocol handle api doesn't allow you to write
```javascript
protocol.interceptProtocol('https', (req, callback) => {
    // map request to file.
    if (req.url.startsWith('https://docs.qq.com/foo')) {
        callback({
            path: require.resolve('foo.html')
        })
        return
    }
    // trigger the default behavior of loading https request
    callback();
})
``` 
I've seen your official document that you recommended to use net.fetch with bypass. But you can't pass req received to fetch api directly. You have to transform it. And after transformed the behavior is different from without setup intercept. I met missing body if body is blob and hard to handle redirect.

So I change some lines of cpp to support callback without argument.

2024-04-22 18:54 UTC, codebytere requested changes
As this is an user-facing API change, we'll need to update API documentation as well as add tests to ensure coverage for this change.

2024-04-23 04:03 UTC, mrchaofan commented on shell/browser/net/electron_url_loader_factory.cc
> +    target_factory_remote->CreateLoaderAndStart(
To resend http request here and it will be back to the ProxyingURLLoaderFactory::CreateLoaderAndStart again but bypass is true.

2024-04-23 06:22 UTC, mrchaofan commented
> As this is a user-facing API change, we'll need to update API documentation as well as add tests to ensure coverage for this change.

Okay. I'll write some tests for it.

2024-04-23 10:35 UTC, mrchaofan commented
@codebytere @nornagon  I've add some test for protocol.interceptProtocol api. But It is a private api so I don't know how to write document for it. But It is ok to work with calling protocol.interceptHttpProtocol api.
```javascript
protocol.interceptHttpProtocol('https', (req, callback) => {
    // a Electron.ProtocolResponse or undefined or null or {};
    const maybeSpecialRes = getSpecialRes(req); // null or {url, uploadData}
    // If maybeSpecialRes is not a Electron.ProtocolResponse then the behavior should perform like no interceptor.
    callback(maybeSpecialRes);
})
```
But the interceptHttpProtocol api forces you to send only http.But protocol.interceptProtocol has more exciting features. 
```javascript
protocol.interceptProtocol('https', (req, callback) => {
    if (/^https:\/\/docs\.qq\.com\/desktop($|\?|\/)/.test(req.url)) {
        // Map request to local file.
        callback({
            path: path.join(__dirname, 'index.html')
        })
        return
    }
    // Perform default http request behavior.
    callback();
});
```

2024-04-24 05:54 UTC, mrchaofan commented
ElectronURLLoaderFactory can be used for protocol intercept and protocol register. There are much differences. If start loading was called by intercept, the receiver is ProxyingURLLoaderFactory, so you can call remote to trigger it. But if it was called by protocol register, you can't call remote to attempt to take the benefit of the default behavior, the receiver is its self, that will lead to death loop. We should treat intercept and register differently.
I'm totally wrong. 😂 The issue dialog made me feel socially dead.

2024-04-25 05:44 UTC, mrchaofan reviewed
@codebytere @nornagon If you have time, please could you review my code? 
I've done my changes. I think I'm back on the right way to support that you can call callback() to call the Remote<URLLoaderFactory> created in the ElectronBrowserClient::WillCreateURLLoaderFactory only if you are intercepting a protocol. If the new protocol you registered you can't, you have to call callback function with argument.

I changed the ProxingURLLoaderFactory to treat  intercept differently from register a new protocol and updated test files.

And I see a test of webview-spec.ts failed. I think it's irrelevant.

2024-05-02 00:26 UTC, Imperat commented
Hi @mrchaofan 
Thanks for this change 🙏 

> @codebytere @nornagon I've add some test for protocol.interceptProtocol api. But It is a private api so I don't know how to write document for it. But It is ok to work with calling protocol.interceptHttpProtocol api.
Please just made relevant changes inside https://github.com/electron/electron/tree/main/docs/api 👍

2024-05-02 13:05 UTC, mrchaofan commented
@Imperat I've just updated the document and It seems electron.d.ts was automatically updated too.
@codebytere I think it is reasonable to do nothing in the protocol interception handler and just perform as if it hasn't been intercepted. But just for the interception. So I changes some codes to treat registration and interception differently.

2024-05-10 15:51 UTC, closed without merging