feat: exit app instance when main package throws error on load
electron/electron pull request #42029
Opened 2024-05-03 14:51 UTC by Mrnikifabio

#### Description of Change
This PR should fix #40606. Please let me know if any test is needed. I really didn't find anything related to `default_app:main.ts` in `spec`.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/main/docs/development/testing.md)
- [x] [PR release notes](https://github.com/electron/clerk/blob/main/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/main/README.md#examples).

#### Release Notes

Notes: Fixed an issue where if an error occurred while loading the main package an error message was not displayed and the app was not exited with an error code.

2024-05-10 08:21 UTC, codebytere approved these changes

2024-05-10 08:22 UTC, codebytere commented
@Mrnikifabio could you rebase this?

2024-05-10 12:11 UTC, Mrnikifabio commented
I had to force push because I initially did a merge in place of rebase. I think this is what you wanted. 
Let me know if anything else is needed :+1:

2024-05-14 08:54 UTC, codebytere requested changes
Took a deeper look into why this was initially added and unfortunately I don't think we'll be able to move this forward.

Exiting when the main package throws an error on load makes the error uncatchable from app code. That would then make it inconsistent with packaged app behavior - as of now, if the app bundle sets up an uncaught error handler and then did something that threw an error they could catch their own issue. This change would remove that ability which would be a blocking issue for a nontrivial number of apps.

2024-05-17 09:03 UTC, closed without merging