refactor: remove klaw dependency
electron/electron pull request #42529
Opened 2024-06-17 17:24 UTC by ckerr

#### Description of Change

A side refactor I found while working on something nearby.

We don't need a klaw devdep anymore, since Node 20 has a recursive option for `fs.readdir()`.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [x] [PR release notes](https://github.com/electron/clerk/blob/main/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/main/README.md#examples).

#### Release Notes

Notes: none

2024-06-17 18:12 UTC, codebytere approved these changes

2024-06-17 18:14 UTC, samuelmaddock approved these changes
nice

2024-06-17 20:23 UTC, jkleinsc requested changes

2024-06-18 02:18 UTC, ckerr commented on script/lib/utils.js
> +    .map((filename) => path.join(top, filename));
fixed in 1b96256e258ef3ac86708a983897af7a2a9f5fad

2024-06-18 22:52 UTC, jkleinsc approved these changes

2024-06-18 22:54 UTC, jkleinsc approved these changes

2024-06-18 22:54 UTC, merged

2024-06-28 06:30 UTC, ckerr commented
/trop run backport-to 31-x-y

/trop run backport-to 30-x-y

2024-06-28 06:30 UTC, ckerr commented
/trop run backport-to 31-x-y

2024-06-28 06:30 UTC, ckerr commented
/trop run backport-to 30-x-y

2024-06-28 06:32 UTC, ckerr commented
/trop run backport-to 32-x-y

2024-06-28 06:34 UTC, ckerr commented
Backporting this after all, since it will make the fs-extra removal troppable