build: remove all publish & build on macOS
electron/electron pull request #42828
Opened 2024-07-08 18:10 UTC by codebytere

Backport of #42763.

See that PR for details.

Notes: none

2024-07-08 18:29 UTC, dsanders11 requested changes
This is going to need the changes from #42829 as well.

2024-07-09 14:18 UTC, dsanders11 approved these changes

2024-07-09 20:19 UTC, jkleinsc approved these changes

2024-07-11 20:10 UTC, jkleinsc approved these changes

2024-07-11 20:10 UTC, jkleinsc commented
Merging as CI failure unrelated to PR change.

2024-07-11 20:10 UTC, merged