build: remove CircleCI
electron/electron pull request #42844
Opened 2024-07-09 18:08 UTC by VerteDinde

#### Description of Change

🫡 This PR removes CircleCI from e/e CI runs.

#### Checklist

- [ ] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/main/docs/development/testing.md)
- [ ] relevant documentation, tutorials, templates and examples are changed or added
- [ ] [PR release notes](https://github.com/electron/clerk/blob/main/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/main/README.md#examples).

#### Release Notes

Notes: none

2024-07-09 20:16 UTC, jkleinsc requested changes
Just a small cleanup is needed on the spec comment.

2024-07-09 20:16 UTC, jkleinsc commented on spec/api-app-spec.ts
> +    // disallows syscalls that Chrome requires for setting up sandboxing.
This whole comment should be removed (we don't use VSTS anymore).

2024-07-09 20:17 UTC, jkleinsc commented
- Do not merge until #42722 is merged.

2024-07-15 10:11 UTC, MarshallOfSound reviewed
Few places we ref "circle" still

* https://github.com/electron/electron/blob/1e1dc22e167a9b7313aaa914fb400a19edbbeb7f/spec/lib/codesign-helpers.ts#L22
* https://github.com/electron/electron/blob/1e1dc22e167a9b7313aaa914fb400a19edbbeb7f/script/push-patch.js#L4
* https://github.com/electron/electron/blob/1e1dc22e167a9b7313aaa914fb400a19edbbeb7f/.env.example#L5
* https://github.com/electron/electron/blob/1e1dc22e167a9b7313aaa914fb400a19edbbeb7f/spec/version-bump-spec.ts#L93
* https://github.com/electron/electron/blob/1e1dc22e167a9b7313aaa914fb400a19edbbeb7f/.devcontainer/devcontainer.json#L39

2024-07-15 16:43 UTC, jkleinsc approved these changes

2024-07-15 18:26 UTC, merged