Tolerate multiple calls to `registerSchemesAsPrivileged`
electron/electron pull request #43031
Opened 2024-07-24 16:43 UTC by rotu

#### Description of Change

#### Checklist

- [ ] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/main/docs/development/testing.md)
- [ ] relevant documentation, tutorials, templates and examples are changed or added
- [ ] [PR release notes](https://github.com/electron/clerk/blob/main/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/main/README.md#examples).

#### Release Notes

Notes:

2024-07-24 17:59 UTC, timfish commented
#40362 proposes a few different options but this PRs description does not state which way this fixes it!

2024-07-24 23:20 UTC, rotu commented
> #40362 proposes a few different options but this PRs description does not state which way this fixes it!

True. I haven't figured out the implementation details, and I think I'm going to switch to `DuplicateSwitchHandler` once I figure out how.

2024-10-04 22:04 UTC, samuelmaddock commented
@rotu The API working group is discussing defining how to approach extensible designs in https://github.com/electron/governance/pull/586. Once that's settled, we'll likely ask to take the approach defined there.

Thanks for opening this PR btw! It does seem like a good idea if we can avoid the hacks needed by library authors to workaround this 👍

2024-10-10 18:46 UTC, samuelmaddock commented
@rotu We've updated our guidelines for designing APIs with third-party libraries in mind.
https://github.com/electron/governance/blob/main/wg-api/best-practices.md#provide-createreadupdatedelete-options-when-dealing-with-arrays

For `registerSchemesAsPrivileged`, it'd be great if the APIs could follow those guidelines and avoid breaking the existing behavior. The existing method can be deprecated following our [breaking changes guidelines.](https://github.com/electron/governance/blob/main/wg-api/best-practices.md#does-this-api-change-alter-any-existing-behavior-in-what-way)

2024-10-10 18:48 UTC, samuelmaddock commented
API CHANGES REQUESTED

(letting our bots know)

2024-10-10 18:50 UTC, samuelmaddock requested changes
API CHANGES REQUESTED

See above comment

2024-11-04 17:46 UTC, samuelmaddock commented
@rotu do you still have interest in moving this work forward? I may be interested in working on this as well.

2024-11-04 17:56 UTC, closed without merging