refactor: migrate deprecated `platform_util_mac` calls
electron/electron pull request #43161
Opened 2024-08-01 11:28 UTC by codebytere

#### Description of Change

Closes https://github.com/electron/electron/issues/43126.
Do not merge until https://github.com/electron/electron/pull/43087 has merged!

Migrates deprecated macOS APIs after Chromium upgrade to macOS 11*

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] [PR release notes](https://github.com/electron/clerk/blob/main/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/main/README.md#examples).

#### Release Notes

Notes: none

2024-08-01 22:04 UTC, VerteDinde commented
Is this going to be a breaking change? Just want to make sure we also call it out in the breaking-changes doc if so

2024-08-02 13:12 UTC, codebytere commented
@VerteDinde it shouldn't be, no! It's just being split into a separate PR on the off chance that it _does_ unexpectedly break/change functionality so we can revert it more easily

2024-08-12 20:05 UTC, jkleinsc requested changes
macOS testing appears to be crashing with the following error:
```
#
# Fatal error in HandleScope::HandleScope
# Entering the V8 API without proper locking in place
✗ Electron tests failed with kill signal SIGTRAP.
#
```

2024-08-15 14:49 UTC, jkleinsc approved these changes

2024-08-15 14:53 UTC, merged