docs: add guide for web api permissions
electron/electron pull request #43306
Opened 2024-08-13 00:38 UTC by erickzhao

#### Description of Change

As a follow-up to https://github.com/electron/electron/pull/41419, I wanted to write a guide on using the FS API in Electron.

However, I found myself wanting a bit more explanation on what exactly `setPermissionCheckHandler` and `setPermissionRequestHandler` are and how they map to different concepts within Electron/Chromium. I personally found this to be confusing, and found an existing issue that references this ambiguity: https://github.com/electron/electron/issues/19405

This PR adds a doc for that with the hope that we can create a new section in our guides for individual web capabilities that we want to document. Note that we already have a great guide on [Device Access](https://www.electronjs.org/docs/latest/tutorial/devices) that documents four different web APIs that would fit under this umbrella.

cc @electron/docs 

#### Release Notes

Notes: none

2024-08-13 04:19 UTC, dsanders11 commented on docs/api/session.md
> -  }
I think it's worth leaving the example here as a quick reference.

2024-08-13 16:39 UTC, erickzhao commented on docs/tutorial/web-api-permissions.md
> +In general, Electron’s renderer processes inherits its API permissions model from Chromium.
Definitely a grammar mistake from the above :)

aa4c597d5631148f7e698935631f4b60083fcceb

2024-08-13 21:08 UTC, jkleinsc requested changes
Overall, I think this is a good start and I think it is fine if we can adjust the example a bit.

Long term, we should test each of the permissions and verify if/when the particular handlers fire.

FWIW... some of the device apis use the permission check handler to verify if they can request device permission which is kind of the security use case of using the permission check handler to verify if certain permissions can even be asked for.

2025-10-23 19:38 UTC, jkleinsc commented
@erickzhao do you plan on working on this?  If not please close this PR.

2026-08-13 08:00 UTC, MarshallOfSound commented
Heads up: Windows CI builds moved to new runners on Monday and the old ones have now been removed. This branch predates that, so its Windows build jobs still point at the old runners and will sit queued forever if CI runs again. Rebasing on `main` (or "Update branch") picks up the change, nothing else needed.

2026-09-21 08:11 UTC, MarshallOfSound commented
Superseded by #53657

2026-09-21 08:11 UTC, closed without merging