fix: touch bar functionality on BaseWindow
electron/electron pull request #43353
Opened 2024-08-19 10:00 UTC by codebytere

#### Description of Change

Closes https://github.com/electron/electron/issues/43344.

`SetTouchBar` was implemented internally on `BaseWindow` but not properly at the ts layer. Fix that.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [x] tests are [changed or added](https://github.com/electron/electron/blob/main/docs/development/testing.md)
- [x] relevant documentation, tutorials, templates and examples are changed or added
- [x] [PR release notes](https://github.com/electron/clerk/blob/main/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/main/README.md#examples).

#### Release Notes

Notes: Fixed an issue where `BaseWindow.setTouchBar` didn't work as expected.

2024-08-19 10:05 UTC, MarshallOfSound reviewed
I don't see which part of this adds the missing method to `BaseWindow`, these appear to be type system changes not runtime changes?

2024-08-20 17:05 UTC, VerteDinde approved these changes

2024-08-20 19:13 UTC, jkleinsc requested changes
Can you add a test in spec/api-touch-bar-spec.ts for BaseWindow?

2024-08-21 19:56 UTC, jkleinsc approved these changes

2024-08-22 10:48 UTC, merged