chore: fix typos in 'patches/' folder.
electron/electron pull request #43375
Opened 2024-08-20 17:42 UTC by Sajjon

Fixes typos in the `patches/` folder

@ckerr [suggested](https://github.com/electron/electron/pull/43366#pullrequestreview-2248182635) I split what was originally a single PR with changes into 39 files into many.

2024-08-20 19:28 UTC, jkleinsc requested changes
Some of the changes here break the patches because the misspellings are from upstream code.  For this PR, please only update the patch descriptions in order to not break the patches.

2024-08-20 19:29 UTC, jkleinsc commented
> Some of the changes here break the patches because the misspellings are from upstream code. For this PR, please only update the patch descriptions in order to not break the patches.

Patch descriptions are the text before the first line that starts with
```
diff --git ....
```

2024-08-20 19:31 UTC, ckerr requested changes
Mostly LGTM. There are a couple of fixes that need to be unfixes because the spelling errors are coming from Chromium or Node, but the rest are good.

Fixing spelling errors in `.patch` files is a little tricky: if the typo is coming from Electron -- e.g. if it's in the summary or in the code changes that we're injecting, then they should be fixed. But if the typo is in the original upstream source files, we need to leave it alone here in order for the patch to apply cleanly.

For those upstream typos, consider submitting the fixes to Node or Chromium :+1:

2024-08-20 19:31 UTC, ckerr commented on patches/chromium/fix_media_key_usage_with_globalshortcuts.patch
> +   // true if register successfully, or false if 1) the specified |accelerator|
This typo belongs to Chromium's file `chrome/browser/extensions/global_shortcut_listener.h` that is being patched here. We need to leave the spelling alone in order for the patch to succeed

2024-08-20 19:31 UTC, ckerr commented on patches/chromium/worker_context_will_destroy.patch
> +   // An empty URL is returned if the URL is not overridden.
This typo belongs to Chromium's file `content/public/renderer/content_renderer_client.h` that is being patched here. We need to leave the spelling alone in order for the patch to succeed.

2024-08-20 19:31 UTC, ckerr commented on patches/node/build_enable_perfetto.patch
> + // on the convertible value will be called at flush time.
This typo belongs to Node's file `src/tracing/trace_event.h` that is being patched here. We need to leave the spelling alone in order for the patch to succeed.

(And in fact the typo goes further upstream than that; the file in Node's repo is copied from Chromium's `base/trace_event/trace_event.h` :smile_cat:)

2024-08-21 06:24 UTC, Sajjon commented
@ckerr Thanks, I reverted the three you highlighted, I went from some of the other files and think you found them all, those three.

2024-09-09 16:21 UTC, ckerr commented
> I have profile photo - and CyonAlexRDX is my work Github user, I have not stolen any picture, I control both Github accounts...

That sounds reasonable. To verify that claim, could you please respond in this PR with a comment from that account?

2024-09-09 16:25 UTC, CyonAlexRDX commented
@ckerr sure, I am @Sajjon. My employer prefers me using a GitHub handler they have full control over.

2024-09-09 16:28 UTC, ckerr commented
@vivoxfold3 I agree that the volume of PRs might look like a red flag. FWIW the PRs submitted to Electron seem helpful enough and uncontroversial. Also, @Sajjon was responsive when I asked how he found the spelling errors and we discussed ways that this might be automated in Electron's CI.  Do you have any evidence that there's something malicious going on here?

2024-09-09 16:38 UTC, Sajjon commented
> I agree that the volume of PRs might look like a red flag.

He got angry because I flagged him... 

YES I'm an extremely active Github User - which I have 10 years of open source github activity to show for. 

And since 6 months ago I've had the hobby of fixing typos in many repo/z Work which I spend 30-120 min per PR on. Silly hobby, but quite pleasing and satisfactory. In contrast this new GH user spent 1 min on trivial PRs and try to counterfit commit signing by manually adding message "Signed-Off-By".

Have a great evening!

2024-09-27 14:33 UTC, closed without merging