chore: fix typos in 'shell/' folder.
electron/electron pull request #43373
Opened 2024-08-20 17:42 UTC by Sajjon

Fixes typos in the `shell/` folder

@ckerr [suggested](https://github.com/electron/electron/pull/43366#pullrequestreview-2248182635) I split what was originally a single PR with changes into 39 files into many.

2024-08-20 19:06 UTC, ckerr requested changes
LGTM except for the V8 naming

2024-08-20 19:06 UTC, ckerr commented on shell/browser/javascript_environment.cc
> +class ConvertibleToTraceFormatWrapper final
Even though `Convertible` is the correct spelling for the word, this class is a wrapper for the V8 `ConvertableToTraceFormat` class. We should use V8's spelling, whether it's correct or not :dizzy:

2024-08-20 19:08 UTC, ckerr commented
I'm marking as `target/33-x-y` and am unsure about how much further back to backport spelling fixes. Any other maintainers have an opinion?

2024-08-20 19:09 UTC, ckerr commented on shell/browser/javascript_environment.cc
> +    std::unique_ptr<v8::ConvertibleToTraceFormat>> {
I don't think this will compile with the spelling fix, since the upstream v8 class has the same spelling error  :smile_cat:

2024-08-21 06:11 UTC, Sajjon commented
@ckerr Thanks! I've reverted the `shell/browser/javascript_environment` changes and force pushed.

2024-08-23 00:32 UTC, ckerr approved these changes

2024-08-23 00:48 UTC, merged