fix: -Wunsafe-buffer-usage warnings in IsUrlArg()
electron/electron pull request #43477
Opened 2024-08-24 02:46 UTC by ckerr

#### Description of Change

Upstream is starting to use `-Wunsafe-buffer-usage` as part of a [larger C buffer hardening project at Google](https://bughunters.google.com/blog/6368559657254912/llvm-s-rfc-c-buffer-hardening-at-google). We should be doing this too.

This is part 1 in a small series to fix `-Wunsafe-buffer-usage` warnings. My intent is to fix all of them and then add the clang warning to our cflags.

We have 44 such warnings in `shell/`. This PR fixes the first three :smile_cat: 

```sh
46362:../../electron/shell/app/command_line_args.cc:18:20: warning: unsafe pointer arithmetic [-Wunsafe-buffer-usage]
46365:../../electron/shell/app/command_line_args.cc:18:20: note: pass -fsafe-buffer-usage-suggestions to receive code hardening suggestions
46366:../../electron/shell/app/command_line_args.cc:18:35: warning: unsafe pointer arithmetic [-Wunsafe-buffer-usage]
46369:../../electron/shell/app/command_line_args.cc:18:35: note: pass -fsafe-buffer-usage-suggestions to receive code hardening suggestions
46370:../../electron/shell/app/command_line_args.cc:24:18: warning: unsafe pointer arithmetic [-Wunsafe-buffer-usage]
46373:../../electron/shell/app/command_line_args.cc:24:18: note: pass -fsafe-buffer-usage-suggestions to receive code hardening suggestions
```

#### Checklist

- [x] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [x] [PR release notes](https://github.com/electron/clerk/blob/main/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/main/README.md#examples).

#### Release Notes

Notes: none.

2024-08-26 15:06 UTC, codebytere approved these changes

2024-08-26 15:24 UTC, jkleinsc requested changes
instead of rolling our own URL validation, we should instead use Chromium's GURL to check for URL validity (eg like we do here: https://github.com/electron/electron/blob/main/shell/browser/ui/inspectable_web_contents.cc#L643)

2024-08-26 18:18 UTC, ckerr commented
> we should instead use Chromium's GURL to check for URL validity

The reason I cloned the existing behavior was I couldn't tell from GitHub history whether or not we were intentionally being more permissive here.

This original commit for this is pretty old; but IIRC the GURL class predates Electron, so it would have been available to the original authors.

But it was submitted by a non-maintainer, so maybe they didn't know?

Either way, agree on using upstream code unless we find a reason not to.

2024-08-27 01:57 UTC, codebytere commented
@ckerr it was originally submitted by a Teams person who used to work on Electron to address a CVE if i remember right - i'm also down to use the GURL validator as long as we confirm that the checks present in ours are covered upstream

2024-08-27 02:11 UTC, ckerr commented
> @ckerr it was originally submitted by a Teams person who used to work on Electron to address a CVE if i remember right - i'm also down to use the GURL validator as long as we confirm that the checks present in ours are covered upstream

@codebytere yep, you are right! I did some more research on it earlier today. The draft I've pushed up has some new code comments that explain what's going on in the code & why it works that way :+1:

2024-08-28 19:24 UTC, ckerr commented
@jkleinsc I've reverted to the previous non-GURL implementation as discussed in person this morning with us & Sam

2024-09-04 01:51 UTC, jkleinsc approved these changes

2024-09-04 01:51 UTC, merged