fix: Launch apps with XDG_ACTIVATION_TOKEN in ozone/wayland
electron/electron pull request #43480
Opened 2024-08-25 16:44 UTC by ogarai

Ensure apps are launched with the activation token received from xdg_activation_v1 protocol.

#### Description of Change

Retrieve the activation token from xdg_activation_v1 protocol when running with ozone/wayland
backend and pass it to the launched app via `XDG_ACTIVATION_TOKEN` environment variable.

For reference, see:
- https://wayland.app/protocols/xdg-activation-v1
- https://issues.chromium.org/issues/40747285
- https://chromium-review.googlesource.com/c/chromium/src/+/5331811

Fixes an issue that still remains for https://github.com/electron/electron/issues/30912.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/main/docs/development/testing.md)
- [ ] relevant documentation, tutorials, templates and examples are changed or added
- [x] [PR release notes](https://github.com/electron/clerk/blob/main/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/main/README.md#examples).

#### Release Notes

Notes: Fixed other apps not being focused when launched from electron ozone/wayland

2024-08-27 22:54 UTC, ckerr requested changes
@ogarai this is a very nice PRl Thanks for submitting it!

Two questions:

- Can this token be cached and reused for subsequent calls? It doesn't hurt to ask, even though I think the answer is "no": the Wayland XDG activation spec refers to the return value of `get_activation_token()` as being a "unique token for this activation."

- I'm a little concerned about requesting a token for tasks without a UI, e.g. `MoveItemToTrash()` calling `XDGUtil()`. If I'm reading [xdg_activation.cc](https://chromium.googlesource.com/chromium/src/+/main/ui/ozone/platform/wayland/host/xdg_activation.cc#119) correctly, it's possible fill up a fixed-sized pool of unused tokens. Maybe we should pass an argument to `XDGUtil()` to indicate whether we want the process being launched to assume focus? That way we could avoid requesting tokens for non-UI use cases.

2024-08-29 23:32 UTC, ogarai commented
Thanks for the review and taking the time to look through the upstream change as well!

> * Can this token be cached and reused for subsequent calls? It doesn't hurt to ask, even though I think the answer is "no": the Wayland XDG activation spec refers to the return value of `get_activation_token()` as being a "unique token for this activation."

That's correct. It's a single use token that needs to be requested each time when launching apps.

> * I'm a little concerned about requesting a token for tasks without a UI, e.g. `MoveItemToTrash()` calling `XDGUtil()`. If I'm reading [your upstream xdg_activation.cc code](https://chromium.googlesource.com/chromium/src/+/5fd07430e5f69e88a7dbb5268fad686039f09aff) correctly, it's possible fill up a fixed-sized pool of unused tokens. Maybe we should pass an argument to `XDGUtil()` to indicate whether we want the process being launched to assume focus? That way we could avoid requesting tokens for non-UI use cases.

That's an excellent point! Updated.

2024-09-05 02:31 UTC, ckerr approved these changes
@ogarai This might need to be rebased on `main` in order to make CI happy, but otherwise LGTM, thanks!

2024-09-05 13:29 UTC, ogarai commented
> @ogarai This might need to be rebased on `main` in order to make CI happy, but otherwise LGTM, thanks!

@ckerr done, thx!

2024-09-05 18:07 UTC, merged