build: update appveyor to node 20.17
electron/electron pull request #44026
Opened 2024-09-30 12:45 UTC by VerteDinde

#### Description of Change

This PR updates our Appveyor build images from Node 20.9 to Node 20.17

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] tests are [changed or added](https://github.com/electron/electron/blob/main/docs/development/testing.md)
- [x] relevant documentation, tutorials, templates and examples are changed or added
- [x] [PR release notes](https://github.com/electron/clerk/blob/main/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/main/README.md#examples).

#### Release Notes

Notes: none

2024-09-30 13:37 UTC, jkleinsc approved these changes

2024-09-30 13:51 UTC, jkleinsc requested changes
Testing is failing with this change:
https://ci.appveyor.com/project/electron-bot/electron-x64-testing/builds/50702825/job/tfmpy7df8s2hsvks

2024-09-30 20:14 UTC, jkleinsc approved these changes

2024-09-30 20:14 UTC, merged

2025-04-07 18:12 UTC, VerteDinde commented
We fixed this in a later PR, it does not need a manual backport