build: use new Issue Template types in templates
electron/electron pull request #44224
Opened 2024-10-14 09:55 UTC by codebytere

#### Description of Change

Use new Issue Types in our templates for improved sorting and categorization.

#### Release Notes

Notes: none

2024-10-14 16:18 UTC, dsanders11 commented
Tentatively LGTM, but want to further consider our existing automation to ensure none of it relies on those labels and will need to be updated.

2024-10-14 22:42 UTC, ckerr reviewed
I approve of this change, but am marking as "comment" for now so that it doesn't get merged accidentally before @dsanders11 is done checking the automation :+1:

2024-10-15 20:00 UTC, dsanders11 requested changes
Here's what I've found for our automation using these labels. It looks like the automation usage is isolated to this repo (I did an org-wide search), which is nice.

We exempt feature request issues from the stale bot - I don't see a migration path here if we drop that label since `actions/stale` does not yet have the concept of issue types.

https://github.com/electron/electron/blob/36b7cf341e814bc7b7b17440033e68d72d14987b/.github/workflows/stale.yml#L30

The issue triage automation checks for bug issues by the label. I'm not seeing the issue type exposed in the API ([example issue](https://api.github.com/repos/electron/electron/issues/44196)), so I don't think there's a migration path here either without the label.

https://github.com/electron/electron/blob/36b7cf341e814bc7b7b17440033e68d72d14987b/.github/workflows/issue-opened.yml#L12

With these in mind, I think we should continue to use the labels until GitHub better supports issue types in their API and stale action. Let's add back the lines with the labels and we'll make that leap when we have the support we need. The other changes seem fine.

2024-10-16 16:08 UTC, dsanders11 approved these changes

2024-10-16 19:34 UTC, jkleinsc approved these changes

2024-10-16 19:34 UTC, merged