fix: trace-startup crashing child process on macOS (32-x-y)
electron/electron pull request #44292
Opened 2024-10-17 01:36 UTC by deepak1556

#### Description of Change

Backport of https://github.com/electron/electron/pull/44257

#### Release Notes

Notes: fix `trace-startup` not working on macOS

2024-10-17 08:38 UTC, codebytere approved these changes

2024-10-17 13:50 UTC, jkleinsc requested changes
Newly added test fails on linux.

2024-10-17 14:55 UTC, deepak1556 commented
@jkleinsc please see https://github.com/electron/electron/issues/44293 for the context of the crash, it is unrelated to this change. I will just skip on those failing platforms until the root cause is addressed.

2024-10-18 14:45 UTC, jkleinsc approved these changes

2024-10-18 15:16 UTC, merged