docs: clarify that sessions use cache by default
electron/electron pull request #44547
Opened 2024-11-04 15:41 UTC by nikwen

#### Description of Change

Relevant code: https://github.com/electron/electron/blob/48801be8e9e3b898635e55abb0b596c83bb9c17a/shell/browser/electron_browser_context.cc#L332-L335

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] relevant documentation, tutorials, templates and examples are changed or added
- [x] [PR release notes](https://github.com/electron/clerk/blob/main/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/main/README.md#examples).

#### Release Notes

Notes: none

2024-11-04 16:02 UTC, ckerr requested changes

2024-11-04 16:07 UTC, ckerr commented on docs/api/session.md
> +By default, the `cache` option is set to `true`.
Maybe we should even link to docs/api/command-line-switches#--disable-http-cache e.g.

- \`Cache\` boolean - Whether to enable cache. Default is \`true\` unless \[the --disable-http-cache switch\]\(api/command-line-switches#--disable-http-cache\) is used.

2024-11-04 22:45 UTC, nikwen commented on docs/api/session.md
> +By default, the `cache` option is set to `true`.
That's a great suggestion, thanks! Updated the PR.

2024-11-04 22:47 UTC, nikwen commented
Thanks for the review, @ckerr!

2024-11-05 03:14 UTC, ckerr approved these changes
Thanks for the changes!

2024-11-05 16:27 UTC, merged

2024-11-05 16:29 UTC, nikwen commented
Thanks for merging!