fix: set kNoStdioInitialization to avoid node::PlatformInit crash
electron/electron pull request #44619
Opened 2024-11-12 09:04 UTC by yangliu-bytedance

node::InitializeOncePerProcess opens nul devices to replace stdio by default in Electron GUI applications. Disable this feature to avoid electron apps crash on Windows platforms when nul devices are disabled.

#### Description of Change

#### Checklist

- [ ] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/main/docs/development/testing.md)
- [ ] relevant documentation, tutorials, templates and examples are changed or added
- [ ] [PR release notes](https://github.com/electron/clerk/blob/main/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/main/README.md#examples).

#### Release Notes

Notes:

2024-11-12 10:08 UTC, codebytere requested changes
Thanks for looking into this!

2024-11-13 03:05 UTC, deepak1556 reviewed
Have we evaluated the other side effects does this flag have on stdio ?  for ex we skip https://github.com/nodejs/node/blob/598bbf4833f04ed78bc47ce8d2182c76a5994c9c/src/node.cc#L532-L535, but maybe that is already covered by [base::RouteStdioToConsole](https://source.chromium.org/chromium/chromium/src/+/main:base/process/launch_win.cc;l=218-230)

What about disabling handle inheritance to node.js child process https://github.com/nodejs/node/blob/598bbf4833f04ed78bc47ce8d2182c76a5994c9c/src/node.cc#L822 when application is started with `--enable-logging` ?

Additionally, nul file is also used to support `ignore` option of stdio with both [child_process](https://github.com/libuv/libuv/blob/d4ab6fbba4669935a6bc23645372dfe4ac29ab39/src/win/process-stdio.c#L144-L166) and [utilityprocess](https://github.com/electron/electron/blob/80ff7a14c61f09a99c159c0dde14cca66ef844b6/shell/browser/api/electron_api_utility_process.cc#L120-L123) api. Even if we skip this early check in node initialization, the application will later crash when these api calls are made. What should happen for these cases ?

2024-11-14 08:31 UTC, yangliu-bytedance commented
> Have we evaluated the other side effects does this flag have on stdio ? for ex we skip https://github.com/nodejs/node/blob/598bbf4833f04ed78bc47ce8d2182c76a5994c9c/src/node.cc#L532-L535, but maybe that is already covered by [base::RouteStdioToConsole](https://source.chromium.org/chromium/chromium/src/+/main:base/process/launch_win.cc;l=218-230)
> 
> What about disabling handle inheritance to node.js child process https://github.com/nodejs/node/blob/598bbf4833f04ed78bc47ce8d2182c76a5994c9c/src/node.cc#L822 when application is started with `--enable-logging` ?
> 
> Additionally, nul file is also used to support `ignore` option of stdio with both [child_process](https://github.com/libuv/libuv/blob/d4ab6fbba4669935a6bc23645372dfe4ac29ab39/src/win/process-stdio.c#L144-L166) and [utilityprocess](https://github.com/electron/electron/blob/80ff7a14c61f09a99c159c0dde14cca66ef844b6/shell/browser/api/electron_api_utility_process.cc#L120-L123) api. Even if we skip this early check in node initialization, the application will later crash when these api calls are made. What should happen for these cases ?

In old versions, electron used to not open nul device as stdio. At that time, electron works fine on Windows with nul device disabled.
With option kNoInitializeNodeV8Platform, our app just works fine, and we are conducting online grayscale verification now.
Considering it is allowed to disabled nul device on Windows, I think it is every module's responsibility to handle the error when failing to open a nul device, but not crash.

2025-01-11 04:27 UTC, deepak1556 commented
Should we close this in favor of https://github.com/electron/electron/pull/44882 ?

2025-01-13 06:39 UTC, closed without merging

2025-01-13 06:39 UTC, yangliu-bytedance commented
I finally got this account back, but I don't plan to use it anymore. I support closing this pull request.