test: mac context-menu using native right-click
electron/electron pull request #44998
Opened 2024-12-11 21:30 UTC by samuelmaddock

#### Description of Change

Updates a skipped test introduced in https://github.com/electron/electron/pull/44978 to now perform a native right-click.

With this, I'm proposing we maintain a new native module, [electron-native-utils](https://github.com/samuelmaddock/electron-native-utils) (name bikeshedding welcome).

- Node native module
- Namespaced APIs
- Prebuilds included with GitHub releases
- `nativeInput` APIs including `setMousePosition` and `click`
- Our own replacement for robotjs and nutjs

##### Todo

- [ ] Move `electron-native-utils` to electron org
- [ ] Publish as `@electron/electron-native-utils`

#### Checklist

- [ ] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/main/docs/development/testing.md)
- [ ] relevant documentation, tutorials, templates and examples are changed or added
- [ ] [PR release notes](https://github.com/electron/clerk/blob/main/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/main/README.md#examples).

#### Release Notes

Notes: none

2024-12-11 23:19 UTC, VerteDinde approved these changes

2024-12-11 23:19 UTC, VerteDinde requested changes
Actually, sorry, test looks great, but let's migrate the package over before merge 😄

2025-02-06 10:15 UTC, codebytere commented
@samuelmaddock is this still being worked on/pursued? or should we close it out for now?

2026-08-13 08:00 UTC, MarshallOfSound commented
Heads up: Windows CI builds moved to new runners on Monday and the old ones have now been removed. This branch predates that, so its Windows build jobs still point at the old runners and will sit queued forever if CI runs again. Rebasing on `main` (or "Update branch") picks up the change, nothing else needed.

2026-08-28 06:32 UTC, MarshallOfSound commented
Closing as drifted and abandoned, re-open if we still want this

2026-08-28 06:32 UTC, closed without merging